### ISSUE TITLE
Use images from RSS feed [4h]

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1014]
If rss items contain images, use those images.

See http://www.lanaken.be/rss.jsp?objectid=b6b62225-405d-4b02-ad5f-e78246774f89

Needs https://github.com/our-city-app/mobicage-backend/issues/34

**Comment by RubenMattan** [comment]
I would always keep our aspect ratio of 16:6 but when they click on the image (https://github.com/our-city-app/oca-backend/issues/1174) we should show the full image
- server side i would remove the ratio check (we need to check if current clients can handle those images)

### Estimate 4h
