### ISSUE TITLE
Posting news on facebook suddenly asks to post as individual user

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1043]
`service-ae9e2a1a-22ef-43a1-9096-debb1dd4816a@rogerth.at`

> Voorheen had ik nooit problemen om onze nieuwsberichten ook te delen via facebook. Nu krijg ik plots de melding 'zorg dat rogerthat kan posten als individuele gebruiker'. Dit kreeg ik voorheen nooit? Moet ik ergens iets aanpassen?

In the past I never had issues to post our news items on facebook as well. Now I get the message 'Make sure rogerthat can post as an individual user'. I never got this before. Do I have to change something?

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/1048
