### ISSUE TITLE
More visibility for the e-commerce

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1054]
- In the sidebar
  - [x] move the ORDER item from the toolbar to the sidebar (before community services)
    - title: E-Shop
  - [x] move AGENDA to the toolbar
  - [x] remove PROFILE
  - [x] remove the "qrcode" item for recent apps (all apps released after 1st of June)
    - for those apps, add the ORDER item to the toolbar. then the items are RESERVE / ORDER / AGENDA / JOYN

**Comment by abom** [comment]
http://gitlab.mobicage.com/rogerthat/apps/merge_requests/1
http://gitlab.mobicage.com/rogerthat/app-configurator/merge_requests/1
