### ISSUE TITLE
Service didn't have any broadcast types

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#1071]
Newly created service `service-00950b22-1c38-465c-8b3c-8774a3fbe56b@rogerth.at` didn't had any broadcast types. However the dashboard showed 2 types ...

**Comment by abom** [comment]
The issue can be reproduced locally too, and it looks like a caching problem.
setting rogerthat.dal.profile._get_profile() **read_cache_in_transaction** to _False_ fixes the problem, but i don't know if it'd affect the fix in https://github.com/our-city-app/mobicage-backend/commit/ee26c5e97ca82867c719ca50355e6bbfd3afe3e1 

@lucasvanhalst can you check this please?

**Comment by lucasvanhalst** [comment]
@abom we can't set that to false else we get a ton of transaction collisions during publishing

We'll have to find where we need to update (or clear) the cache during publishing to fix the issue

**Comment by abom** [comment]
@lucasvanhalst I tried this approach by clearing the cache after/before setting broadcast types, but didn't work (maybe i got it wrong!)

**Comment by RubenMattan** [comment]
Can you create a unit test for this and test before and after your fix.

**Comment by bart-at-mobicage** [comment]
@abom, can we somehow detect which services have this problem? Eg. if service_profile.broadcastType != sln_settings.broadcast_types? And can we then publish them again (if sln_settings.update_pending == False) in a migration?

**Comment by abom** [comment]
Maybe related: 
https://github.com/our-city-app/oca-backend/issues/957
