### ISSUE TITLE
Local and regional news open the same news feed in be-aalter

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1094]
Is the javascript code wrong in the custom home branding? :/

**Comment by RubenMattan** [comment]
android fixes:
- https://github.com/our-city-app/mobicage-android-client/commit/6d0347030b27708b47a5b7e1f1ac0dc6c0f8a56f
- https://github.com/our-city-app/cordova-mobicage-plugin/commit/747eca4f9181136fca3be733d04238ffef0602bb

**Comment by RubenMattan** [comment]
ios fixes:
- (cordova) https://github.com/our-city-app/mobicage-ios-client/commit/0f8f39fa8fbf5877f971b2b4dc869a224c3eecfd
- (normal) TBD
