### ISSUE TITLE
Customer card email

### ISSUE THREAD

**Issue by OSAMaureen** [our-city-app/oca-backend#1098]
There is still a tutorial of the OCA customer card in the email that is sent to new users.
This needs to be removed. Needs to happen for the customers in Flanders!
(Needs to be translated for future foreign customers)

![image](https://user-images.githubusercontent.com/40057810/45612443-3cd63500-ba63-11e8-8d75-de20aaea9fd4.png)

**Comment by bart-at-mobicage** [comment]
@abom, we'll have to skip this smart email about OSA Loyalty in case Joyn is available for that customer (see `is_joyn_available`).

**Comment by abom** [comment]
Which one of these emails? https://github.com/our-city-app/oca-backend/blob/master/src/solutions/common/bizz/service.py#L44

I think we already stopped sending OSA Loyalty smart email in #858.

The email shown in this screenshot is the welcome email, it should be edited or another one without loyalty is created so we can send it to customer who have joyn?

**Comment by bart-at-mobicage** [comment]
Ok. Thank you @abom. We'll create a version without OSA Loyalty and we'll update this ticket once completed.
