### ISSUE TITLE
Error when sending news from 2nd location

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1100]
I created a 2nd location for service-3703330d-99c5-4c83-b3e9-1be919918381@rogerth.at, and changed the app id of the service identity afterwards.

There is an error when they try to send local news from their 2nd location: Insufficient budget.

**Comment by abom** [comment]
> There is an error when they try to send local news from their 2nd location: Insufficient budget.

Are they sending news from non-shop session?, this service has no budget!

**Comment by bart-at-mobicage** [comment]
yes, from non-shop session. I think the problem is that the code checks the app id of the default service identity, instead of the current service identity.

**Comment by abom** [comment]
Still the insufficient budget error is normal.
I was about to ask, budget ordering/checking/updating...etc is done over the service user, it will be the same between different identities, this need to be changed, right? so every identity can order and consume the budget without affecting others?

**Comment by bart-at-mobicage** [comment]
That's true, but they were trying to send out local news from that identity, which doesn't require budget.

**Comment by abom** [comment]
>  I think the problem is that the code checks the app id of the default service identity, instead of the current service identity.

no, it checks the default app id of the current service identity.

I just didn't notice it was a local news problem, sorry.
The problem is that the 2nd location identity has different app ids than the default one, and when loading the dashboard, if a customer is found, it just gets the app ids of that customer not the current service identity.
