### ISSUE TITLE
Mail friends doesn't arrive

### ISSUE THREAD

**Issue by OSAMaureen** [our-city-app/oca-backend#1125]
When you try to send a friend request, the mail never arrives.
![vrienden uitnodigen](https://user-images.githubusercontent.com/40057810/46473120-6e7b2a00-c7df-11e8-8dd5-5380caa70252.jpg)

**Comment by bart-at-mobicage** [comment]
@abom, can you investigate this issue plz? It happens when the third button in the screenshot is used.

**Comment by abom** [comment]
I tested it more than once with latest android client (locally), and on Veurne app (production).
Both worked normally and the email arrives.

Can you please provide more info? time, which app...(and version).
