### ISSUE TITLE
Icons remain after being deleted in 'statische inhoud'

### ISSUE THREAD

**Issue by OSAMaureen** [our-city-app/oca-backend#1129]
Customer deleted button 'video' (static content). But it is still noticable in the app.
I manually removed it in service panel for now. But I think there is a bug in place. (3th customer with same issue).

![image](https://user-images.githubusercontent.com/40057810/46598309-ff098100-cae3-11e8-8a5d-7816125d12a8.png)

![image](https://user-images.githubusercontent.com/40057810/46598529-b30b0c00-cae4-11e8-8870-1e1bc1367ad7.png)
![image](https://user-images.githubusercontent.com/40057810/46598640-172dd000-cae5-11e8-9a3f-79ae30f578f4.png)

**Comment by lucasvanhalst** [comment]
Can't reproduce this. Next time it happens can you notify me? Don't remove the item or publish so I can investigate what happened
