### ISSUE TITLE
Quotations - adding text

### ISSUE THREAD

**Issue by OSAMaureen** [our-city-app/oca-backend#1131]
Each of our quotations should have the line 'this offer only stands for 3 months" or Dutch "deze offerte is slechts 3 maand geldig". 

This is crucial. If our prices change we can say that the offer was only valid until xxx and the new prices are in order. If not we can not say this.

**Comment by bart-at-mobicage** [comment]
In case of a quotation, rename the word "Order" (NL: Bestelling) to "Quotation" (NL: Offerte) and add the text that Maureen has mentioned.
![quotations](https://user-images.githubusercontent.com/17762105/46805785-42732200-cd66-11e8-88b6-a5d3c4ccadd1.png)

Quotations are new in the shop, you can find a test example in the quotations tab for customer `service-195b4e91-4508-4369-89bf-4d0bcb20504b@rogerth.at`. We built this feature such that price lists that are sent to a customer are stored in the shop as well.
