### ISSUE TITLE
Poll 

### ISSUE THREAD

**Issue by OSAMaureen** [our-city-app/oca-backend#1150]
Making polls in our Dashboard.
For this we need to add this as a feature.  Logo: https://fontawesome.com/v4.7.0/icon/list-ul

1) choose your type of poll
Vote (nl: "stemming") --> for this you can use the code of the Hoeilaart poll - you can integrate this in OSA. https://github.com/our-city-app/plugin-light-parade
Here you can only vote for eg top 5 / top 3 / number one choice 
Poll (nl:"enquête") --> for this we will base ourselves on google forms. 
Goal: merchant can enter questions + each question needs to have a specific type of answer
answer types: 	
- multiple choice
- checkboxes
- short answer text (= open answer)
- lang answer text (= open answer)

2) In Dashboard people need to be able to see previous, current and pending polls and need to be able to make a new poll (when clicking on ‘make a new poll’ they need to have the 2 choices as stated above)

Eg: 
![image](https://user-images.githubusercontent.com/40057810/47161416-44069200-d2f2-11e8-999b-7794c27b5d66.png)

 
Make 3 subcategories: 
 	1. Pending polls
	→ name of poll + icons: start (), edit (), trash can () 
	2. current polls 
	→ name of poll + 2 icons: stop(), see results (), trash can () 
3. Previous polls
	→ name of poll + 2 icons: see results (), trash can () 
![image](https://user-images.githubusercontent.com/40057810/47161477-66001480-d2f2-11e8-9188-dfdbc435f33c.png)

3) For the results 
     → graph/table to represent the results

**Comment by RubenMattan** [comment]
No need to implement yet.

Do not show any results of a poll as long people can vote

**Comment by RubenMattan** [comment]
### Remarks

answer types should only be single/multi select for now

branding will load polls via an api call ascending
- If the user didn’t vote yet there will be a button ‘Vote now’
- If the user already voted but poll is still in progress show ‘You already voted, results will be available once this poll has ended’
- If the poll has ended show a button ’Show results’ => This will goto a public website where a graph of the results will be shown

You should be able to send news linked to a poll (dynamic flow) same logic as above

After the user has answered all the questions add an extra step ‘Do you want to be notified of these results’ with yes/no button

Polls should have an end date but you should able to close sooner

Once the poll is closed its possible to view the results for users/service
Once the poll is closed the service should see how many users want to receive an update of the results
  - The message will be pre filled with ’The voting of XXX has ended. You can view the results by clicking the button below’  + a button to the public results
