### ISSUE TITLE
Customizable signup text

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1159]
<img width="710" alt="screen shot 2018-10-22 at 15 59 56" src="https://user-images.githubusercontent.com/17762105/47296806-af62a380-d613-11e8-99d9-d5770bafeb0d.png">

The text "_Welcome, you can register yourself under a city. Select a city and enter the required information to submit the application. On successful submission, you will be contacted very soon._" doesn't fit threefold. Maybe we can use app translations to customize this per app. For ThreeFold, let's change to: "_Welcome to the ThreeFold community! Here you can register yourself as a merchant in a few steps. Once the registration is successful, you can explore the possibilities of your application. Good luck and enjoy!_"

Make sure to test the normal registration on dashboard.onzestadapp.be after implementation

**Comment by lucasvanhalst** [comment]
The dutch translation for that is just `Welkom. Registreer uw onderneming of vereniging in enkele stappen.` which is more generic. Should we just change the english translation to that too and not bother with custom translations?

**Comment by bart-at-mobicage** [comment]
Let's use the generic text for now.
