### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#116]
The buttons to rename the "Agenda" @settings are gone

![schermafbeelding 2016-11-29 om 15 39 36](https://cloud.githubusercontent.com/assets/23034120/20713981/b5f202f8-b64a-11e6-9acd-47fb84c6c667.png)

The button to add an event ad "Agenda" @ dashboard is gone

![schermafbeelding 2016-11-29 om 15 40 42](https://cloud.githubusercontent.com/assets/23034120/20713985/b9c4c5a0-b64a-11e6-80ee-1e9851f21ab6.png)

**Comment by RubenMattan** [comment]
On what service did this problem occur?

**Comment by OSATOM** [comment]
Do not know anymore but I have checked several agenda's and i did not found the problem anymore so close the issue.

Could temporary issue due to updates ?
