### ISSUE TITLE
cannot accept/deny signups in TF

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1160]
The buttons aren't visible. Is this because signup is not enabled for this app?

<img width="954" alt="screen shot 2018-10-22 at 17 01 49" src="https://user-images.githubusercontent.com/17762105/47300215-3ddb2300-d61c-11e8-93d7-8cbdb2288e14.png">

**Comment by lucasvanhalst** [comment]
Most likely. Enabling signup will make it visible in the list to everyone though, so I'm not sure what the best solution is. Another boolean 'show in list' or something?
