### ISSUE TITLE
IVAREM trash calendar

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1164]
There are too many street numbers returned, my iPhone raised an exception (`RangeError: Maximum call stack size exceeded.`). 

Are the street numbers required in the IVAREM API? If not, we could just skip the 2nd step. 
If it's required I suggest we replace the street number selection with a numeric text input. Server-side we can validate the input by checking the possible street numbers.

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/plugin-trash-calendar/pull/8
