### ISSUE TITLE
Facebook / twitter not longer available

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#117]
When the cities / merchants/... broadcast news the facebook & twitter integration is not longer available please add this again and try to add instagram too.

**Comment by bart-at-mobicage** [comment]
A little bit more context... In the old way of sending out news we could configure that the message was also posted on a facebook page or a twitter account. This facebook page / twitter account can be configured under "Settings > General"

To see the old way of broadcasting set news_enabled=False in src/solutions/flex/handlers.py and reload the dashboard.
