### ISSUE TITLE
Broadcast types aren't stored

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1170]
A new broadcast types 'Wegeniswerken' was added in the dashboard by`service-77a9c413-fa3a-43c9-a68a-b990811e64fe@rogerth.at`. However, after publishing, the type didn't appear in the Notification Settings. Probably related to db.get in the uber transaction.

![screen shot 2018-11-08 at 11 31 00](https://user-images.githubusercontent.com/17762105/48193037-ce6a7080-e349-11e8-98fd-76a8e1e6d94e.png)
![screen shot 2018-11-08 at 11 32 07](https://user-images.githubusercontent.com/17762105/48193122-070a4a00-e34a-11e8-88fe-e804b1eb832c.png)

**Comment by bart-at-mobicage** [comment]
Hi @abom, can you have a look at this before you continue working on the polls feature?

**Comment by RubenMattan** [comment]
I added a unit test and moved a line to the end of the function. Needs a proper fix but as long we use the uber transaction no real fix is possible. OSA and RT should be split to properly work.

https://github.com/our-city-app/oca-backend/commit/2680cad0847aa34a66ab82e34c1556d4871538eb
