### ISSUE TITLE
BadValueError: Property pause_settings.message is not multi-line

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1172]
### BadValueError: Property pause_settings.message is not multi-line

**Request**
POST rogerthat-server.appspot.com/common/order/settings

**Status**
500

**HTTP Referrer**
https://dashboard.onzestadapp.be/flex/

**User agent**
Mozilla/5.0 (iPad; CPU OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D100 Safari/604.1

**Service**
default

**Version**
20181031t083640

**Comment by RubenMattan** [comment]
already fixed
