### ISSUE TITLE
Clicking a news item

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1174]
Not the first time we hear this comment. People dont think it's logical that clicking the title or image opens the service home screen.

In Aalter, they think it would make more sense to open the website in the action button.

**Comment by lucasvanhalst** [comment]
it'd make more sense if the photo was enlarged when clicking on it.

**Comment by RubenMattan** [comment]
Lets discuss how clicking on something should work. Then i can add an estimate
