### ISSUE TITLE
File attached in newsbroadcast

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#118]
It is not longer possible to attache a file in the news broadcast.

Please make possible that our clients can attache pdf, png, video, ... as in the OSA messenger

**Comment by bart-at-mobicage** [comment]
Add 'Attachment' as possible action of a news item, next to the options 'website', 'phone number' and 'mail'.

You can find inspiration for the look&feel and implementation from the old broadcast UI. On your development dev, set news_enabled=False in in src/solutions/flex/handlers.py

Make a suggestion for the implementation first, and present it to Geert or Tom before implementing.
