### ISSUE TITLE
News upload Picture

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#119]
when you choose to import the coverphoto and then try to switch to upload own picture you get stuck in the two pictures on the screen

![schermafbeelding 2016-11-28 om 15 53 46](https://cloud.githubusercontent.com/assets/23034120/20717007/58f8f4bc-b654-11e6-8f6b-4f50d908aa9d.png)

**Comment by abom** [comment]
@OSATOM Can you give me the detailed steps to reproduce this? i a uploaded the picture and completed the next steps normally.

**Comment by abom** [comment]
@OSATOM  The problem still exists?

**Comment by OSATOM** [comment]
yes the problem still excists.
When you choose the coverphoto & then choose your own picture you get the two of them and you cannot remove any picture that you have chosen.

![schermafbeelding 2017-01-18 om 09 07 37](https://cloud.githubusercontent.com/assets/23034120/22055896/a3482dc8-dd5d-11e6-9a20-1a8ee1f4f183.png)

**Comment by abom** [comment]
@OSATOM The right way to re-produce this issue is by choosing own picture, then instead of saving after the resizing is done, we just remove the picture, after that you cannot choose neither own picture nor the cover photo.
