### ISSUE TITLE
QR-Code Dashboard

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#120]
The QR-Codes of the services in the new OSA have the old lay-out.

Please connect to the correct branding.

![schermafbeelding 2016-11-29 om 19 09 18](https://cloud.githubusercontent.com/assets/23034120/20722649/aea908d0-b667-11e6-8973-24f373dcb8a9.png)

**Comment by bart-at-mobicage** [comment]
@GertCornelis: Did you upload the QR template when creating this app in BOB? If you didn't, then you'll need to upload it at https://rogerth.at/mobiadmin/apps and all newly created services will have that new QR template.
