### ISSUE TITLE
RSS scraper for wichelen doesnt work anymore

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1208]
Also for geraardsbergen & ninove

**Comment by RubenMattan** [comment]
Problem is a caching issue, don't know why urlfetch lib is caching requests yet...

**Comment by lucasvanhalst** [comment]
try `result = urlfetch.fetch(url, headers = {'Cache-Control' : 'max- 
age=300'})`

**Comment by RubenMattan** [comment]
yeah i tried but no luck, going to add a query param for now
```
headers1 = {'Cache-Control' : 'no-cache', 'Pragma' : 'no-cache'}
headers2 = {'Cache-Control' : 'max-age=0, must-revalidate'}
headers3 = {'Cache-Control' : 'no-cache,max-age=0', 'Pragma':'no-cache'}
```

**Comment by RubenMattan** [comment]
Deployed and dry-runned
