### ISSUE TITLE
Update NL welcome text

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1209]
> Kan je het welkomsttekstje ook eens bekijken en verbeteren dat je als nieuwe abonnee krijgt voor de stadsapp. ‘Je’ en ‘u’ worden door mekaar gebruikt in deze welkomsttekst.

**Comment by RubenMattan** [comment]
Its welcome text and registration text that uses 'je' and 'u'. An app update is required.

Firsts we need to determine what text we will change
