### ISSUE TITLE
When coupling a news feed, all rss items are posted in the news feed

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1218]
Normally the rss sync should be dry ran, but for Koksijde, 25 items were posted immediately.

**Comment by lucasvanhalst** [comment]
Can't reproduce. I think it's because we already had a (custom) scraper for koksijde

**Comment by bart-at-mobicage** [comment]
I don't think we had a custom scraper for Koksijde. The news items were created the day the RSS feed was coupled (22/01/19). Can you see anything related in the server logs?
