### ISSUE TITLE
OSA Terminal - Touches are handled twice

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#122]
Sylvie has a customer who has installed the OSA Terminal app with revenue discount. But every touch on the calculator is executed twice. So if the user presses '3', the screen shows '33'. If the user tries to remove only one '3' using the backspace button, than both '3's disappear.

This is the device info:
![image](https://cloud.githubusercontent.com/assets/17762105/20761821/916d31e8-b724-11e6-92ed-1caec09f2aa9.png)

**Comment by RubenMattan** [comment]
![2016-12-07 12 46 34](https://cloud.githubusercontent.com/assets/1122760/20966585/4faf86dc-bc7b-11e6-8ae6-71275c8fa0c7.jpg)
