### ISSUE TITLE
Cannot unfollow 2 associations

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1240]
Probably these associations were originally created as community services, because they are auto-connected.
- `service-64db6dba-f90a-4d83-a1f6-1555a6c283b4@rogerth.at`
- `service-d1e23d77-64a5-4b9c-92ba-b4b48e2d699d@rogerth.at`

Remove them as auto-connected services.

**Comment by RubenMattan** [comment]
removed
