### ISSUE TITLE
Cannot post news on facebook

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1241]
Again

> Ik kan weer niets posten vanuit de app op facebook. wanneer ik facebook wil aanvinken komt er een pop-up vak van Facebook waarbij je hen de rechten moet geven om te posten en wanneer ik dan op continue klik blijft er in die app een blauwe balk laden maar er komt niets meer. Indien ik dan refresh is heel mijn opgestelde nieuwsbericht weg.

`service-ae9e2a1a-22ef-43a1-9096-debb1dd4816a@rogerth.at`

**Comment by RubenMattan** [comment]
This works perfectly
