### ISSUE TITLE
Trash messages

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1242]
On March 1, Maureen received 2 messages of the trash calendar (about 27 and 28 feb). 

![image](https://user-images.githubusercontent.com/17762105/53728248-921bcc80-3e72-11e9-9350-8fdc62ba3a90.png)

Were there issues server-side or was Maureen's Sint-Truiden app inactive for 2-3 days?
In case of the 2nd use case, is there a way we can prevent this? With a timeout or whatever? 
No need to implement anything yet, just think about a possible solution.

**Comment by RubenMattan** [comment]
@bart-at-mobicage Better picture?

**Comment by bart-at-mobicage** [comment]
@RubenMattan, here it is:

![image](https://user-images.githubusercontent.com/17762105/53793230-b38dbe80-3f2d-11e9-802c-c65d43b5193e.png)

**Comment by RubenMattan** [comment]
Messages where sent correctly. I would not change anything. However maybe we should change the way notifications work in our app.

**Comment by lucasvanhalst** [comment]
This is caused by https://github.com/our-city-app/mobicage-android-client/issues/106
