### ISSUE TITLE
Block updating the publication date of a published news item

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1254]
It's possible to edit the publication date of a scheduled news item AFTER it's scheduled date. It should only be possible to edit before the scheduled date.

**Comment by lucasvanhalst** [comment]
Is this only a dashboard UI change? because it looks fine: https://github.com/our-city-app/mobicage-backend/blob/cc94b57d89ea9a52aec23bad9d97a420dd5c3c47/src/rogerthat/bizz/news/__init__.py#L973-L975

**Comment by bart-at-mobicage** [comment]
indeed, only UI
