### ISSUE TITLE
Create trash calendars

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1259]
These apps don't have a trash calendar yet
- [x] Edegem 2650 (IGEAN)
- [ ] Oudenaarde 9700 (IVLA)

For the apps below, only add it in the community service, not in the sidebar yet
- [x] Aalter 9880 (IVM )
- [x] Maldegem 9990 (IVM)
- [ ] Affligem 1790 (ILvA)
- [ ] Ninove 9400, 9401, 9402, 9403, 9404, 9406 (ILvA)
- [ ] Herzele 9550, 9551, 9552 (ILvA)
- [x] Dendermonde 9200 (VERKO)
- [ ] Erpe-Mere 9551 (ILvA)
- [ ] Geraardsbergen 9500, 9506, 9571 (ILvA)
- [ ] Haaltert 9451 (ILvA)
- [x] Laarne 9270 (VERKO)
- [ ] Lede 9340 (ILvA)
- [ ] Sint-Lievens-Houtem 9520, 9521 (ILvA)
- [x] Wetteren 9230 (VERKO)
- [ ] Zottegem 9620 (ILvA)

**Comment by RubenMattan** [comment]
All calendar for with i have data are done
