### ISSUE TITLE
Limit number of news items a day

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#126]
A service scheduled 5 news items at the same day, hour with the same content ...

**Comment by bart-at-mobicage** [comment]
Investigate if the user clicked the submit button 5 times, or if something retried in our code.

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!
