### ISSUE TITLE
PSP: embedded app scans for QR and shows project [4d]

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1301]
- [x] startScanning
- [x] send request to record the scan (or scan=null to just get the project)
- [x] process the scan response to render the project page
- [x] click through to merchant list
  - now open/closed
- [x] Also support scanning via the 'scan' button in the sidebar, should open the embedded app with the correct context

**Comment by lucasvanhalst** [comment]
Also support scanning via the 'scan' button in the sidebar, should open the embedded app with the correct context (that being the full url, I think)
