### ISSUE TITLE
Updates in About page

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1308]
- [ ] Should mention Our City App for city apps (and not mention "Rogerthat")
  - I suggest to add an ABOUT_PRODUCT_FAMILY constant to build.yaml
- [ ] Should show Green Valley Belgium footer for city apps
![about_footer](https://user-images.githubusercontent.com/17762105/56566395-ce39f680-65b2-11e9-8f99-b041abbf8963.png)
- [ ] Also for new apps created by app-cfg

**Comment by RubenMattan** [comment]
android: https://github.com/our-city-app/mobicage-android-client/commit/64948f6a3a4569c595512b8f92934312ed524a0e

**Comment by RubenMattan** [comment]
ios: https://github.com/our-city-app/mobicage-ios-client/commit/bcb80dba5902d40587aee152c02d5cd23688650b

**Comment by bart-at-mobicage** [comment]
Only the first of the 3 tasks in this issue is solved. The mobicage footer is still shown instead of the GV footer.

**Comment by RubenMattan** [comment]
I thought alls logo's where changed, because be-loc was changed
point 3 is already done see https://gitlab.ourcityapp.xyz/rogerthat/app-configurator/merge_requests/4

**Comment by lucasvanhalst** [comment]
Footers are updated now
