### ISSUE TITLE
Wrong rotation for RSS image

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1309]
![image1](https://user-images.githubusercontent.com/17762105/56566566-42749a00-65b3-11e9-845c-13fcba01cf9c.png) ![image2](https://user-images.githubusercontent.com/17762105/56566565-41dc0380-65b3-11e9-996b-fb6bd7171c7a.png)

**Comment by RubenMattan** [comment]
News item is not shown in the app anymore, bug in rss?
So can't investigate
