### ISSUE TITLE
News streams for new apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1312]
Ideally, developers shouldn't be needed to setup news streams of a new app. 
- City news, Events, Traffic, Actions and Press could be created automatically when a new city app is created
- NEWS_STREAM should be set in the build.yaml
- A 2:1 image should ideally be configurable for city news

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/plugin-mobicage-control-center/pull/36
https://gitlab.ourcityapp.xyz/rogerthat/app-configurator/merge_requests/4
