### ISSUE TITLE
TOPdesk integration for Halle

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1324]
Has less free fields than Niel. 
Eg. the location should be linked to CRAB

**Comment by bart-at-mobicage** [comment]
![unnamed-1](https://user-images.githubusercontent.com/17762105/58006112-92c61580-7ae7-11e9-89d9-e0a0ae0058be.png)
![unnamed-2](https://user-images.githubusercontent.com/17762105/58006113-92c61580-7ae7-11e9-8049-f026370fed9e.png)

> - Naam aanmelder (het gaat in de omgeving om ongeregistreerde aanmelders): Voornaam + achternaam
> - Vestiging aanmelder: altijd  ‘Burgers’
> - Soort binnenkomst: altijd ‘OnzeStadApp’
> - Soort melding: altijd ‘Burgermelding’
> - Korte omschrijving: leeg laten (wordt door behandelaars zelf ingevuld)
> - Categorie: altijd ‘Openbaar Domein’
> - Verzoekveld : hier mag de melding of de vraag worden ingevuld
> - Vestiging (ruimte): dit is straatnaam - ophalen via API branch via ID
> - Ruimte: dit is huisnummer – ophalen via API location (soms is het mogelijk dat er enkel een straatnaam [branch] ingevuld wordt. In dat geval wordt het veld Ruimte leeggelaten)
>   - Indien de burger het adres niet vindt in de opzoeklijst (en de straat en eventueel huisnummer niet gekend zijn in de TOPdesk-omgeving), moet er een vrij veld worden voorzien in de app. De invulling van het vrij veld mag onder de melding of de vraag van de burger komen te staan in het verzoekveld.
>   - Indien er een locatie wordt aangeduid op een kaart, mag de link naar een Google Maps locatie ook in het verzoekveld komen te staan onder de burgermelding.
> - Behandelaarsgroep: altijd ‘OD-meldingenbeheer’
> - Behandelaar: altijd ‘OD-meldingenbeheer’
> - Status: altijd ‘Geregistreerd’
> - Foto’s en bijlagen moeten automatisch onder bijlagen komen te staan
> 
> **Niet besproken velden mogen leeg gelaten worden.

**Comment by lucasvanhalst** [comment]
For this, the following needs to happen:
- Add an option per 'city' to enable anonymous calls, then implement it.
- Add 'operatorGroup' and 'operator' to a city
- Add 'location' to mapping (this depends on the value of 'branch')
- Extend / rework the 'mapping' so that it is possible to create a flow out of it.
- Create flow based on the mapping & publish it to the service using the rt service api.
- Perhaps add a button to manually trigger an update of the flow.

**Comment by lucasvanhalst** [comment]
We've skipped the following:
- Vestiging aanmelder: altijd ‘Burgers’ -> We can't find 'vestiging' in any field
- Behandelaarsgroep: altijd ‘OD-meldingenbeheer’ -> there is no operator group with this name
- Behandelaar: altijd ‘OD-meldingenbeheer’ -> there is no operator with this name

**Comment by lucasvanhalst** [comment]
https://github.com/our-city-app/plugin-topdesk-integration/pull/9

**Comment by lucasvanhalst** [comment]
Waiting for apple review & after that we can publish the new messageflow

**Comment by lucasvanhalst** [comment]
All done
