### ISSUE TITLE
AppStore promotion video

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#133]
In iTunesConnect we can upload a promotion video. Maybe we can upload the videos which are made for Lochristi, Herzele...

**Comment by RubenMattan** [comment]
On the play store you can do the same

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!
