### ISSUE TITLE
Polls news group

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1339]
We want to be able to temporarily add a news group to the Hoeilaart app that will contain all news about the current polls.

- [ ] Create the news group with the attached image 
- [ ] Add the required broadcast type and mapping to Hoeilaart
- [ ] The news items about polls should be added to this group (when sent via forms)

![plush-design-studio-555452-unsplash](https://user-images.githubusercontent.com/17762105/58328269-fa56ca80-7e31-11e9-981d-a30434c2ae20.jpg)

**Comment by bart-at-mobicage** [comment]
We would like to see the following layouts, so we can see which one to choose:

Option 1:
- Polls
- City news
- Events | Traffic
- Actions
- Press

Option 2:
- City news
- Polls | Traffic
- Actions
- Events | Press

**Comment by RubenMattan** [comment]
i need a title, description, promo image and also a title and description in case there are no items

**Comment by RubenMattan** [comment]
do old news items need to be deleted when the poll ends?

**Comment by bart-at-mobicage** [comment]
- title: Polls / Polls
- subtitle: Current polls / Lopende bevragingen
- title empty: No polls / Geen poll
- subtitle empty: There are no polls at this time / Er zijn geen polls op dit moment

- I think we can leave it, so inhabitants have some history. Once they click the button, they will see that this poll is finished.
- yes, notifications enabled by default
- enable for every app. We can test it by creating a new poll in osa-demo2. At this moment there is a poll until Aug 31 in Halle. Maybe we can enable this in Halle once it's tested in the demo app.

**Comment by RubenMattan** [comment]
On hold until new News UI is ready and Lucas added an end date on news items with category poll

**Comment by lucasvanhalst** [comment]
@RubenMattan is this done?

**Comment by RubenMattan** [comment]
Its code complete yes, but only enabled for osa-demo2 for now (testing)
