### ISSUE TITLE
Sort news history by publication date

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1340]
I think news is sorted by update timestamp instead of publication time

The "Partners" news item should have been listed somewhere at the bottom, under all the news items of 15/05 

![Screenshot 2019-05-24 at 15 26 00](https://user-images.githubusercontent.com/17762105/58331005-75bb7a80-7e38-11e9-813d-4fbc2775fe26.png)

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-backend/commit/cd1cd3f21aa785be6b29dfb2006ad16fe806a2ef
