### ISSUE TITLE
News dashboard remarks

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1348]
- [x] label for 'reached' and 'liked' on statistics page should be 'liked' and 'reached' (they are switched)

**Comment by OSAMaureen** [comment]
- [ ] bij kiezen van foto - optie om coverfoto te gebruiken is verdwenen

- [ ] keuze maken in teksten - ofwel allemaal in 'u-vorm' ofwel in 'je-vorm'. Stad Beringen zal hier zeker commentaar op geven anders. Zij verkiezen de u vorm :)

- [ ] hoe sturen we regionaal nieuws uit nu? Ik vind de optie hiervoor niet terug.

- [ ] bovenaan staat er 'create message'

- [ ] foutmelding nadat ik bericht aangemaakt had + ingepland had - bericht is ook gewoon weg
![Screen Shot 2019-06-20 at 12 03 39](https://user-images.githubusercontent.com/40057810/59840872-8ede1b00-9353-11e9-99cb-6be611f36bd2.png)

**Comment by OSAMaureen** [comment]
Geprobeerd om nieuws onmiddellijk uit te sturen, maar ik krijg een foutmelding:

![Screen Shot 2019-06-20 at 12 06 52](https://user-images.githubusercontent.com/40057810/59841125-fdbb7400-9353-11e9-974a-e722ab82b1c0.png)

Ook nu is alles van het bericht verdwenen!

**Comment by lucasvanhalst** [comment]
Solutions on the remarks:
- "use cover picture" added
- Texts from old dashboard were unchanged but can be changed if needed
- Ruben should have enabled regional news for osa gemeente, but it won't actually sent items to other apps. The UI will be usable for testing though.
- Translations are not done yet, so those can be ignored for now.
- The error was due to the button url not starting with `htttps://`, I've made it so that it always prefixes it now.

**Comment by OSAMaureen** [comment]
Bij testen krijg ik terug foutmelding 
![image](https://user-images.githubusercontent.com/40057810/60333674-f15d9980-9999-11e9-8ec8-c60526a44c88.png)

dit wanneer ik limit on location aanzet 
- add address : er verschijnt niets bij mij  - kaartje ook niet

gebruik coverfoto zie ik er niet tussen staan

**Comment by lucasvanhalst** [comment]
- [ ] Attachment from a newsitem which had an attachment isn't shown so you can't save the newsitem after it was published
- [ ] action button url https://www.blabla.com is being saved as 'w' for some reason

**Comment by lucasvanhalst** [comment]
- [ ] new step: 'category': news group
- [ ] horizontal instead of vertical
- [ ] remove fb & twitter from news & cleanup server code (keep db properties & settings)
- [ ] bold the sliders their text & indent explanation
