### ISSUE TITLE
Unable to edit news items

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1355]
Beringen says:

> ik heb terug problemen met het wijzigen of aanmaken van berichten via de webmodule in de stadsapp.
> Als ik een aangemaakt bericht wil wijzigen, gebeurt er niets ofwel verschijnt even dit bericht en dan verdwijnt het weer. Op dit moment kan ik ook geen berichten aanmaken.
> 
> Bedankt!

Can you investigate plz?

**Comment by RubenMattan** [comment]
Can you attach the screenshot, i don't see any issues in our server logs.
Yesterday the city created/updated 7 news items and Tuesday 4

**Comment by lucasvanhalst** [comment]
Sounds like a UI issue, I wouldn't bother with this since the new UI will replace it anyway

**Comment by RubenMattan** [comment]
Customer reported its working again, so some caching issue in javascipt or so?

**Comment by bart-at-mobicage** [comment]
closing because of new UI
