### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#136]
Location in new app does not work in report card.

it is also strange that we see no google maps image @ when and where - button.
maybe it is due to that problem.

![screenshot_20161206-083721](https://cloud.githubusercontent.com/assets/23034120/20917127/ed0bafa6-bb8f-11e6-983a-088b74189d76.png)

**Comment by RubenMattan** [comment]
If we could not parse the location the map is not shown

**Comment by OSATOM** [comment]
what is wrong with the location.
I have the feeling we didn't have to deal with this issue before the new lay-out or am i wrong ?

the thing is, I need to give a solution to the customers. what is the solution ?

**Comment by RubenMattan** [comment]
No its always been like this.
Google just could not parse the address. However i think it looks oke...

**Comment by RubenMattan** [comment]
Same issue as #138
