### ISSUE TITLE
Beringen report card contains demo stuff

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1361]
- [ ] I encountered a link in the text to some staging environment, should be production environment. The link wasn't clickable on iOS. Is it clickable on Android?
- [ ] The same component had an explanation about an optional register number (such that he can check the status on the GV environment), but that step was required.
  - if the step is required, then update the text
  - if it should be optional, then remove the required validation

**Comment by lucasvanhalst** [comment]
url fixed
