### ISSUE TITLE
Regional news

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1365]
News item 762187019 (Jul 5, Aqua Green Strandhanddoek, service-3703330d-99c5-4c83-b3e9-1be919918381@rogerth.at, location Oostduinkerke-bad) should have arrived in local news in be-koksijde, not in regional news, because be-koksijde is the main app of this service identity. This service has multiple identities. Probably not related, but just for your information.

**Comment by RubenMattan** [comment]
The default app id of the customer is be-hooglede and is not service identity based, so multiple locations will always have the same default app_id for news.

**Comment by bart-at-mobicage** [comment]
Before July the news items arrived in local news. As far as I know the default app id was always be-hooglede. The news items in June were sent with the identity in be-koksijde and also sent via Regional News.

So I think the code should use the app id of the current service identity and not the default app id of the customer.

<img src="https://user-images.githubusercontent.com/17762105/61293406-e7c69500-a7d3-11e9-84aa-369ae907b0b2.PNG" width="300px"> <img src="https://user-images.githubusercontent.com/17762105/61293405-e7c69500-a7d3-11e9-911a-bf156dccd67c.PNG" width="300px">

**Comment by RubenMattan** [comment]
Fixed by https://github.com/our-city-app/mobicage-backend/commit/b814aaee5917fa0fdf769f2ff0e9e1790c8d6437
