### ISSUE TITLE
messages from the app - branding

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#137]
Wrong branding.

**Comment by RubenMattan** [comment]
Can you add a screenshot?

**Comment by OSATOM** [comment]
yes of course my dear

![screenshot_20161206-094819](https://cloud.githubusercontent.com/assets/23034120/20918838/3f790b54-bb99-11e6-9e95-921eef7f87f1.png)

**Comment by bart-at-mobicage** [comment]
The fix is to download the main branding of the merchtem community service and to upload it in the app details page of be-merchtem (https://rogerth.at/mobiadmin/apps)

**Comment by OSATOM** [comment]
@GertCornelis, can you handle this and please give me a timing when this will be done.
Thanks @bart-at-mobicage

**Comment by GertCornelis** [comment]
Done
