### ISSUE TITLE
PSP project list sorting

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1370]
The list shows the projects in some random order, maybe we should order them by start/end date?

![Screenshot 2019-07-12 at 14 52 51](https://user-images.githubusercontent.com/17762105/61129456-bdfc2e00-a4b4-11e9-8af5-2ed74ddf59a2.png)

**Comment by lucasvanhalst** [comment]
They're ordered by start date atm. Should it be changed to end date? Or should it just show both the start and end date in the list

**Comment by lucasvanhalst** [comment]
@bart-at-mobicage so what's the answer then?

**Comment by bart-at-mobicage** [comment]
I would
- order by start date first, then end date.
- show start and end date (From xxx until yyy)
