### ISSUE TITLE
Around You: Addresses improvements

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1376]
<img src="https://user-images.githubusercontent.com/17762105/61283386-56e4bf00-a7bd-11e9-8f3a-28a3356c4afd.png" height="500px">

- [ ] The list should be case insensitive sorted
- [ ] The encoding of the last street isn't correct. Is it wrong in CRAB or did we parse it wrong?

```
In [2]: print u"de B\u00dathunestraat"
de BÚthunestraat
```
Should have been `de Béthunestraat`. 
> Google:
> Showing results for de béthunestraat aalter
> No results found for de búthunestraat aalter 
>

**Comment by RubenMattan** [comment]
The dbf library i used was broken...
https://gitlab.ourcityapp.xyz/rogerthat/apps/commit/a2c5404a88fc81c1d7c7e72f5921e81d1ff3ffde
