### ISSUE TITLE
Search merchants

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#138]
When you search merchant
even if you are connected to several

"around you" - is empty
"A-Z" - there you can find them

Because it is the "around you" search result is the first they see, they think the app is empty, or that there are no merchants in the app.

![screenshot_20161206-084759](https://cloud.githubusercontent.com/assets/23034120/20917314/1ca30aa6-bb91-11e6-9da8-76176a2c3755.png)

![screenshot_20161206-084831](https://cloud.githubusercontent.com/assets/23034120/20917318/24396ef4-bb91-11e6-9dd0-9ae25861280a.png)

**Comment by bart-at-mobicage** [comment]
Show a warning next to the address field in settings when the address could not be geocoded.

Warning text: 
The address could not be converted to GPS coordinates. Please revise the format of your address to be more standard. Eg. 

```
Antwerpsesteenweg 19
9080 Lochristi
```

**Comment by OSATOM** [comment]
this is the solution, Thank You Bart !

**Comment by RubenMattan** [comment]
@donatogomez The error message should be translated to the users language

**Comment by OSATOM** [comment]
Dutch translation 

Het opgegeven adres kan niet in GPS-coördinaten omgezet worden. 
Gelieve uw adres naar onderstaand voorbeeld aan te passen.

Antwerpsesteenweg 19
9080 Lochristi
België

Is this ok guys ?
