### ISSUE TITLE
Poll: bug in end date component

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1381]
When typing an end date (Eg 23/07/2019) the widget is disabled (because first you type a "2" and 2/07/2019 is in the past) and the switch becomes disabled.

I suggest to validate the date on focus out, and maybe not auto-disable the end date switch.

**Comment by lucasvanhalst** [comment]
No longer relevant I guess, since we've disabled manual typing in the textfield. The picker is always opened now
