### ISSUE TITLE
Should we limit the amount of news items per day for a merchant?

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#139]
Should a merchant be able to post 5 (different) news items on the same day?

**Comment by OSATOM** [comment]
answer is no.

they should have the possibility to schedule as much as they want but indeed no spam and no more then 5 a day is already a lot.

Maby after 3 we could show a message : Is your message relevant and don(t you think you are spamming your audience now ?

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!
