### ISSUE TITLE
Enable Polls for every user

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1397]
- [ ] Make a migration to remove the polls module from every SolutionSettings
- [ ] Make the polls tab visible for everyone (do not deploy before the release date of the "Around you" storycard)

**Comment by lucasvanhalst** [comment]
Is this still correct, because what I understand from maureen is:
- forms should be enabled for some cities only (paying customers probably)
- merchants from those cities should be able to send forms too

**Comment by bart-at-mobicage** [comment]
Enabling polls for everyone was decided in the beginning of August, but in the mean time I heard something different from Steven. Let's verify with Tom if this is still valid.
