### ISSUE TITLE
Refactor photo/video upload

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#14]
After all chunks have been received, collect all chunks on the server and store the final image on cloudstorage. the image handler then just permanently redirects to the cloudstorage url. Make a handler which removes chunks older than a week if the TransferResult's status isn't STATUS_VERIFIED. Don't forget to write a migration to migrate existing chunks to cloudstorage

- [ ] Store image on cloudstorage after all chunks are received
- [ ] Permanent redirect (301) to cloudstorage in handler
- [ ] Cron to remove chunks / failed/pending TransferResults older than a week
- [ ] Migration for existing chunks

Perhaps also increase the chunk size, 100 kb isn't much and the less roundtrips the faster it goes

**Comment by lucasvanhalst** [comment]
Why was this closed?

**Comment by RubenMattan** [comment]
When we refactor photo upload we should make it better not just save it somewhere else
