### ISSUE TITLE
Loyalty system is broken. People cannot add revenue for a visit.

### ISSUE THREAD

**Issue by FastGeert** [our-city-app/oca-backend#140]
Steps to reproduce:
- Scan loyalty card
- Screen shows up with three buttons
- Press the first button [Add loyalty]

Then you see the screen popup to add the loyalty, but it disappears again as well in a blink of an eye.

**Comment by bart-at-mobicage** [comment]
Is this still valid?

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!
