### ISSUE TITLE
Maldegem events/traffic in city news as well

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1400]
Maldegem wants to display their news items of the events/traffic group in city news as well (so in both city news and events or traffic).

Is this just some configuration or does it require code changes?

**Comment by RubenMattan** [comment]
This does not exist yet.

What with notifications, will we create doubles or only for the city group?

**Comment by bart-at-mobicage** [comment]
I suggest that the notification points to the news item of the "events" or "traffic" group, and that the news item in the "city" group is a duplicate.

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/mobicage-backend/pull/219

**Comment by bart-at-mobicage** [comment]
Configured for Maldegem
