### ISSUE TITLE
Estimation for web-based polls 

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1409]
What if we build a system to distribute polls via web/facebook and let people submit these web forms. Let's work this out and give it an estimation.

**Comment by lucasvanhalst** [comment]
- authentication (ask email, explain why + mention tombola if relevant)
- 7 components
- sections (header/title/description)
- navigation (between sections)
- maybe register intent action

**Comment by bart-at-mobicage** [comment]
± 10d
