### ISSUE TITLE
PSP backend improvements

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1414]
- [x] It would be logical to be able to add a merchant admin only for a certain city. That way the city can handle the search for a job student theirselves.
- [ ] Manually entering opening hours for a new merchant are wrong by 1 day (compare L&L Lochristi on Google Maps with PSP in osa-demo2)
- [x] Need better server logging. There is always an error when I scan, but there's no logging on the server.
Client debug logs: 
`08-22 15:02:05.972 (UI) [BRANDING] {"payload":{"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":"https://participatiespaarpot.be/api/plugins/psp/v1.0/app/scan","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://participatiespaarpot.be/api/plugins/psp/v1.0/app/scan: 0 Unknown Error","error":{"isTrusted":true}},"type":"[projects] Add participation failed"}`
- [x] Error shown when scanned too much should have localized date. Now it shows the date in English. "Uw laatste scan was op Sep 13, 2019, 2:21:11 PM" --> "Uw laatste scan was om 14:21."

**Comment by lucasvanhalst** [comment]
>  It would be logical to be able to add a merchant admin only for a certain city. That way the city can handle the search for a job student theirselves.
this implies changing literally every api handler, sure about that?

**Comment by lucasvanhalst** [comment]
> Manually entering opening hours for a new merchant are wrong by 1 day (compare L&L Lochristi on Google Maps with PSP in osa-demo2)

This should've been fixed already, are you sure that address wasn't added when the dates were shown incorrectly?

**Comment by lucasvanhalst** [comment]
> There is always an error when I scan, but there's no logging on the server.

probably because the request never reached the server

**Comment by bart-at-mobicage** [comment]
> > There is always an error when I scan, but there's no logging on the server.
> 
> probably because the request never reached the server

I saw the request, but there were no log lines from us

**Comment by bart-at-mobicage** [comment]
I added an extra bullet point about the date format
