### ISSUE TITLE
Server load

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1416]
I guess service api calls of `service-5ddcc881-e5f0-4803-ab10-e134b94244b3@rogerth.at` (and maybe others) triggered this peak between 11:09 and 13:00.

![Screenshot 2019-08-22 at 15 22 36](https://user-images.githubusercontent.com/17762105/63519256-e7b46600-c4f2-11e9-8d22-8127ceba657a.png)

What happened? Why are there 107 `news.get` and `news.publish` calls? Looks like we might do some performance optimization there (by handling the news item updates in bulk?).

RSS feed content at 15:40: [rss.xml.txt](https://github.com/our-city-app/oca-backend/files/3530388/rss.xml.txt)

Service logs:

Timestamp | Type | Status | Function | +
-- | -- | -- | -- | --
11:10:04 | Call | Success | news.publish | +
11:10:03 | Call | Success | news.publish | +
11:10:03 | Call | Success | news.publish | +
11:10:03 | Call | Success | news.publish | +
11:10:03 | Call | Success | news.publish | +
11:10:03 | Call | Success | news.publish | +
11:10:03 | Call | Success | news.publish | +
11:10:03 | Call | Success | news.get | +
11:10:02 | Call | Success | news.get | +
11:10:02 | Call | Success | news.get | +
11:10:02 | Call | Success | news.publish | +
11:10:02 | Call | Success | news.get | +
11:10:02 | Call | Success | news.publish | +
11:10:02 | Call | Success | news.get | +
11:10:01 | Call | Success | news.get | +
11:10:01 | Call | Success | news.publish | +
11:10:01 | Call | Success | news.get | +
11:10:01 | Call | Success | news.publish | +
11:10:01 | Call | Success | news.get | +
11:10:01 | Call | Success | news.get | +
11:10:01 | Call | Success | news.publish | +
11:10:01 | Call | Success | news.get | +
11:10:01 | Call | Success | news.publish | +
11:10:00 | Call | Success | news.publish | +
11:10:00 | Call | Success | news.get | +
11:10:00 | Call | Success | news.get | +
11:10:00 | Call | Success | news.publish | +
11:10:00 | Call | Success | news.get | +
11:10:00 | Call | Success | news.get | +
11:10:00 | Call | Success | news.publish | +
11:10:00 | Call | Success | news.publish | +
11:10:00 | Call | Success | news.publish | +
11:10:00 | Call | Success | news.get | +
11:10:00 | Call | Success | news.publish | +
11:09:59 | Call | Success | news.get | +
11:09:59 | Call | Success | news.publish | +
11:09:59 | Call | Success | news.get | +
11:09:59 | Call | Success | news.get | +
11:09:59 | Call | Success | news.publish | +
11:09:59 | Call | Success | news.publish | +
11:09:59 | Call | Success | news.get | +
11:09:59 | Call | Success | news.get | +
11:09:59 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.get | +
11:09:58 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.get | +
11:09:58 | Call | Success | news.get | +
11:09:58 | Call | Success | news.get | +
11:09:58 | Call | Success | news.get | +
11:09:58 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.publish | +
11:09:58 | Call | Success | news.publish | +
11:09:57 | Call | Success | news.get | +
11:09:57 | Call | Success | news.publish | +
11:09:57 | Call | Success | news.publish | +
11:09:57 | Call | Success | news.get | +
11:09:57 | Call | Success | news.get | +
11:09:57 | Call | Success | news.get | +
11:09:57 | Call | Success | news.get | +
11:09:57 | Call | Success | news.publish | +
11:09:57 | Call | Success | news.get | +
11:09:57 | Call | Success | news.get | +
11:09:57 | Call | Success | news.publish | +
11:09:57 | Call | Success | news.publish | +
11:09:57 | Call | Success | news.get | +
11:09:56 | Call | Success | news.get | +
11:09:56 | Call | Success | news.publish | +
11:09:56 | Call | Success | news.get | +
11:09:56 | Call | Success | news.publish | +
11:09:56 | Call | Success | news.publish | +
11:09:56 | Call | Success | news.get | +
11:09:56 | Call | Success | news.publish | +
11:09:56 | Call | Success | news.get | +
11:09:56 | Call | Success | news.publish | +
11:09:56 | Call | Success | news.get | +
11:09:55 | Call | Success | news.get | +
11:09:55 | Call | Success | news.publish | +
11:09:55 | Call | Success | news.publish | +
11:09:55 | Call | Success | news.get | +
11:09:55 | Call | Success | news.publish | +
11:09:55 | Call | Success | news.get | +
11:09:55 | Call | Success | news.publish | +
11:09:55 | Call | Success | news.publish | +
11:09:55 | Call | Success | news.get | +
11:09:54 | Call | Success | news.publish | +
11:09:54 | Call | Success | news.get | +
11:09:54 | Call | Success | news.get | +
11:09:54 | Call | Success | news.get | +
11:09:54 | Call | Success | news.publish | +
11:09:54 | Call | Success | news.publish | +
11:09:54 | Call | Success | news.get | +
11:09:54 | Call | Success | news.publish | +
11:09:54 | Call | Success | news.get | +
11:09:54 | Call | Success | news.get | +
11:09:54 | Call | Success | news.publish | +
11:09:53 | Call | Success | news.publish | +
11:09:53 | Call | Success | news.get | +
11:09:53 | Call | Success | news.publish | +
11:09:53 | Call | Success | news.get | +
11:09:53 | Call | Success | news.publish | +
11:09:53 | Call | Success | news.publish | +
11:09:53 | Call | Success | news.get | +
11:09:53 | Call | Success | news.get | +
11:09:52 | Call | Success | news.publish | +
11:09:52 | Call | Success | news.get | +
11:09:52 | Call | Success | news.publish | +
11:09:52 | Call | Success | news.get | +
11:09:52 | Call | Success | news.get | +
11:09:52 | Call | Success | news.publish | +
11:09:52 | Call | Success | news.publish | +
11:09:52 | Call | Success | news.get | +
11:09:52 | Call | Success | news.get | +
11:09:52 | Call | Success | news.publish | +
11:09:52 | Call | Success | news.publish | +
11:09:52 | Call | Success | news.publish | +
11:09:51 | Call | Success | news.publish | +
11:09:51 | Call | Success | news.get | +
11:09:51 | Call | Success | news.get | +
11:09:51 | Call | Success | news.get | +
11:09:51 | Call | Success | news.publish | +
11:09:51 | Call | Success | news.get | +
11:09:51 | Call | Success | news.publish | +
11:09:51 | Call | Success | news.get | +
11:09:51 | Call | Success | news.publish | +
11:09:50 | Call | Success | news.get | +
11:09:50 | Call | Success | news.publish | +
11:09:50 | Call | Success | news.get | +
11:09:50 | Call | Success | news.publish | +
11:09:50 | Call | Success | news.get | +
11:09:50 | Call | Success | news.get | +
11:09:50 | Call | Success | news.publish | +
11:09:50 | Call | Success | news.get | +
11:09:49 | Call | Success | news.publish | +
11:09:49 | Call | Success | news.get | +
11:09:49 | Call | Success | news.publish | +
11:09:49 | Call | Success | news.publish | +
11:09:49 | Call | Success | news.get | +
11:09:49 | Call | Success | news.publish | +
11:09:49 | Call | Success | news.get | +
11:09:49 | Call | Success | news.get | +
11:09:48 | Call | Success | news.publish | +
11:09:48 | Call | Success | news.publish | +
11:09:48 | Call | Success | news.get | +
11:09:48 | Call | Success | news.publish | +
11:09:48 | Call | Success | news.get | +
11:09:48 | Call | Success | news.get | +
11:09:48 | Call | Success | news.publish | +
11:09:48 | Call | Success | news.publish | +
11:09:48 | Call | Success | news.get | +
11:09:48 | Call | Success | news.get | +
11:09:48 | Call | Success | news.publish | +
11:09:48 | Call | Success | news.publish | +
11:09:47 | Call | Success | news.get | +
11:09:47 | Call | Success | news.publish | +
11:09:47 | Call | Success | news.publish | +
11:09:47 | Call | Success | news.get | +
11:09:47 | Call | Success | news.get | +
11:09:47 | Call | Success | news.publish | +
11:09:47 | Call | Success | news.get | +
11:09:47 | Call | Success | news.publish | +
11:09:47 | Call | Success | news.get | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.get | +
11:09:46 | Call | Success | news.get | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.get | +
11:09:46 | Call | Success | news.publish | +
11:09:46 | Call | Success | news.get | +
11:09:45 | Call | Success | news.publish | +
11:09:45 | Call | Success | news.get | +
11:09:45 | Call | Success | news.publish | +
11:09:45 | Call | Success | news.get | +
11:09:45 | Call | Success | news.publish | +
11:09:45 | Call | Success | news.get | +
11:09:45 | Call | Success | news.get | +
11:09:45 | Call | Success | news.publish | +
11:09:45 | Call | Success | news.get | +
11:09:45 | Call | Success | news.get | +
11:09:45 | Call | Success | news.publish | +
11:09:44 | Call | Success | news.get | +
11:09:44 | Call | Success | news.get | +
11:09:44 | Call | Success | news.get | +
11:09:44 | Call | Success | news.publish | +
11:09:44 | Call | Success | news.publish | +
11:09:44 | Call | Success | news.get | +
11:09:44 | Call | Success | news.get | +
11:09:44 | Call | Success | news.publish | +
11:09:43 | Call | Success | news.get | +
11:09:43 | Call | Success | news.get | +
11:09:43 | Call | Success | news.publish | +
11:09:43 | Call | Success | news.publish | +
11:09:43 | Call | Success | news.publish | +
11:09:43 | Call | Success | news.get | +
11:09:43 | Call | Success | news.publish | +
11:09:43 | Call | Success | news.get | +
11:09:42 | Call | Success | news.get | +
11:09:42 | Call | Success | news.get | +
11:09:42 | Call | Success | news.get | +
11:09:42 | Call | Success | news.publish | +
11:09:42 | Call | Success | news.publish | +
11:09:42 | Call | Success | news.publish | +
11:09:42 | Call | Success | news.get | +
11:09:42 | Call | Success | news.get | +
11:09:41 | Call | Success | news.get | +
11:09:41 | Call | Success | news.get | +

**Comment by RubenMattan** [comment]
The rss scraper triggered these updates, probably something changed in the content ... But will investigate some more

(We don't scrape https://www.bree.be/rss.xml but we scrape https://www.bree.be/news.xml so provided rss feed content is incorrect)

**Comment by RubenMattan** [comment]
They changed all there link elements in the rss feed from https to http

**Comment by RubenMattan** [comment]
Optimisation: https://github.com/our-city-app/mobicage-backend/pull/220
