### ISSUE TITLE
PSP dashboard improvements

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1417]
- [ ] Show the project list with cards and tabs like forms (current projects, finished projects, new project ...)
- [ ] Time notation should be localized (now it shows 08/22/2019 instead of 22/08/2019)
- [ ] Show sexier statistics. Use horizontal bar graphs and show the results on a hotmap.

**Comment by lucasvanhalst** [comment]
heatmap isn't really interesting - it will just show a 'heat' point if it has 1 or more scans at that location.
