### ISSUE TITLE
Import menu from excel

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#142]
<img width="710" alt="screen shot 2016-12-07 at 09 05 52" src="https://cloud.githubusercontent.com/assets/17762105/20959655/6e408e30-bc5c-11e6-8137-020811da9d08.png">

**Comment by abom** [comment]
I don't understand, can this be in English?

**Comment by RubenMattan** [comment]
https://docs.google.com/a/mobicage.com/spreadsheets/d/1imo_1sW6i1yQ3m2sc-klT64nGooFZgeXLp49mGM6e-M/edit?usp=sharing
