### ISSUE TITLE
News item appears in Local and Regional news

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1423]
NewsItem 784807018 (BROOD VAN DE MAAND) in group "promotions" in osa-demo2 is visible in the LOCAL and REGIONAL tabs. It is sent as local news and is sent the same way as I sent the other news items that day and the other items appear only under local news.

**Comment by bart-at-mobicage** [comment]
It automagically disappeared from Regional news!?

**Comment by RubenMattan** [comment]
iOS probably doesn't clear news_ids when clicking on a notification and calling news. getNewsStreamItems
