### ISSUE TITLE
Stripe API update

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1425]
Starting in September 2019, a new regulation called Strong Customer Authentication (SCA) will require businesses in Europe to request additional authentication for online payments. Checkout fully supports SCA—including exemption logic—and ensures that you only ask customers to provide additional authentication when strictly necessary.

https://stripe.com/docs/payments/checkout/migration

**Comment by RubenMattan** [comment]
@bart-at-mobicage The only place we still want to use stripe is to charge extra balance for news correct?

**Comment by bart-at-mobicage** [comment]
correct

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/1436
