### ISSUE TITLE
UiT API 3

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1426]
More info at http://hunl.mjt.lu/nl2/hunl/ln21h.html?m=AMEAAEEV1BsAAbZ2blYAAHDRpWsAASKBF7AAG498AAgEUwBdCOdd4KItD1h_SOeGcy87BX6segAHoLA&b=6dc4b093&e=7e579a0f&x=2NXnFNGb8bU53Wl6MxPrY3F7m_X5XOkxC2JTFemO_lY

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/1432
