### ISSUE TITLE
RSS: Markdown errors

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1427]
Looks like markdownify doesn't do a great job when handling unnumbered lists. The first list items needs a starting newline.

Can we fix/workaround this?

![Screenshot 2019-08-27 at 11 35 45](https://user-images.githubusercontent.com/17762105/63772764-0db67d80-c8da-11e9-92cf-42724d6f2456.png)

`...<h2>TOEKENNINGSPROTOCOL</h2> <p>Het 'Ereteken van de Arbeid' telt twee klassen:<ul><li> Het Ereteken van de Arbeid tweede klasse: toegekend na 25 jaar arbeid; </li> <li>Het Ereteken van de Arbeid eerste klasse: toegekend na 30 jaar arbeid. </li></ul>...`

<img src="https://user-images.githubusercontent.com/17762105/63771435-705a4a00-c8d7-11e9-9198-66e6b8113d0d.png">

----

Same for headers (but actually this is because of an html error, the <p> tag before the header isn't closed). But anyway, the header hashtags should always have a newline before them.

![Screenshot 2019-08-27 at 15 04 03](https://user-images.githubusercontent.com/17762105/63773789-317ac300-c8dc-11e9-937d-dabe55d75d15.png)

`...<h2>Voor welke kaarten of soort betalingen?</h2><br> <p>Voor alles. België besliste om te kiezen voor een algemeen verbod voor de handelaar om kosten aan te rekenen voor het gebruik van alle soorten betaalinstrumenten. Voor alle transacties met debetkaarten (zoals Bancontact, Maestro, V-pay) en kredietkaarten (Mastercard, Visa, American express, Diners Club,…) mag de handelaar dan ook geen kosten meer doorrekenen aan de consument. Ook voor overschrijvingen en domiciliëringen in de SEPA-zone (de Europese Unie en enkele andere Europese landen zoals Ijsland, Noorwegen en Zwitserland) mag de handelaar geen kost meer aanrekenen.<p> <h2>Waarom een algemeen verbod?</h2><br> <p>Dat zorgt voor meer duidelijkheid...`

**Comment by lucasvanhalst** [comment]
Solution: update markdownify 
```
# Update to non-git repo once the commit d0f688d2e4e225b65da1d6745687f00b0ce839f6 is published
# markdownify==0.4.1
markdownify=https://github.com/matthewwithanm/python-markdownify.git#master
```
