### ISSUE TITLE
News: Investigate why loading news items is slow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1429]
It takes about 5 to 7 seconds before the list is shown. Let's measure what takes so much time.

**Comment by bart-at-mobicage** [comment]
https://github.com/our-city-app/mobicage-backend/pull/222

**Comment by RubenMattan** [comment]
Until a year ago news.list never returned any stats then it was changed (https://github.com/our-city-app/mobicage-backend/commit/c15bba62748daefa007b3d719eaa6751410b7357)

So loading the statistics was not optimized for loading multiple items.
