### ISSUE TITLE
QR-codes new Apps

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#143]
The Qr-Codes of the community and the new merchants, care or associations is wrong.

It is the old version
![schermafbeelding 2016-12-07 om 13 37 25](https://cloud.githubusercontent.com/assets/23034120/20968005/730c2570-bc82-11e6-905c-2e2cf11df452.png)

**Comment by GertCornelis** [comment]
While creating the app I uploaded the new QR-code design, but this is not used?

**Comment by bart-at-mobicage** [comment]
Can you verify the QR code of a recently created merchant? If this merchant has the correct QR, then the community service must have been created before the template was uploaded.

If needed you can recreate the QR codes of Gemeente Merchtem by removing the QR_CODES functionality (in the Service tab of the customer popup in the shop). Then save, then add it again and save again.

**Comment by GertCornelis** [comment]
The QR code of a newly created merchant (Supra) is correct. I just tried to recreate the QR codes for Gemeente Merchtem as instructed but that did not change anything.

**Comment by bart-at-mobicage** [comment]
Sry, I forgot a step. Go to the service panels of Gemeente Merchtem. Upload the QR template there as well. Remove the old QR template.

Remove the QR_CODES functionality (in the Service tab of the customer popup in the shop) and save. Then add it again and save again.
