### ISSUE TITLE
Wrong time shown in event list

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1441]
Wrong time shown in event list (10:00-01:00) instead of 10:00-11:00.

![IMG_86F5DA23DF39-1](https://user-images.githubusercontent.com/17762105/64240446-2c33fe80-cf02-11e9-9cd7-7a9887c68301.jpeg)

![IMG_DFFF4FA7AD12-1](https://user-images.githubusercontent.com/17762105/64240455-30601c00-cf02-11e9-9be7-74ef30a67503.jpeg)

<img width="941" alt="Screenshot 2019-09-04 at 10 53 26" src="https://user-images.githubusercontent.com/17762105/64240490-3e15a180-cf02-11e9-974c-109841168add.png">

https://www.uitinvlaanderen.be/agenda/e/lessenreeks-pilates/e0ef43ee-a320-4e66-ac95-fd8273333631

![Screenshot 2019-09-04 at 10 35 20](https://user-images.githubusercontent.com/17762105/64240464-33f3a300-cf02-11e9-9aae-067b08c873d9.png)

**Comment by bart-at-mobicage** [comment]
@RubenMattan, this one is probably fixed by _"Fix uitdatabank end dates #1450"_, right?

**Comment by RubenMattan** [comment]
Yes
