### ISSUE TITLE
News statistics design upgrade

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#145]
* Bar charts instead of line chars
* ...

**Comment by bart-at-mobicage** [comment]
![screen shot 2016-12-09 at 08 50 39](https://cloud.githubusercontent.com/assets/17762105/21041709/17524c16-bded-11e6-8011-0f78a6bde9d0.png)

@abom, some translations to give you some context:
- bereikt = reached
- actie = action
- leeftijd = age
- man = male
- vrouw = female
- onbekend = unknkow
- tijd = time


- change the **Leeftijd** (age) charts into bar charts (a bar per app)
- change the **Tijd** (time) chats by a cumulative line chart (a line per app), just like we do on the statistics page. see screenshot below. however, the area underneath the lines doesnt need to be colored.
![screen shot 2016-12-09 at 09 01 51](https://cloud.githubusercontent.com/assets/17762105/21041863/29ddfac8-bdee-11e6-9cba-335d8197089f.png)

**Comment by RubenMattan** [comment]
Also the button caption of the last news item is incorrect

![screen shot 2016-12-12 at 08 46 22](https://cloud.githubusercontent.com/assets/1122760/21091598/7c12746c-c047-11e6-8e6b-dbfa7231eee0.png)
