### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by aimbhau** [our-city-app/oca-backend#1452]
Getting a warning message from Facebook. It says
"Your app doesn’t comply with the following:

Platform Policy 8.1: Verify that you have integrated Login correctly. Your app shouldn’t crash or hang during the testing process.

During Login, your app or website is crashing or hanging excessively, creating a broken experience for people trying to use your Login integration. To make sure this flow runs smoothly, check that you’ve integrated Facebook Login correctly. We recommend that you test Login on all integrations."
I have tested every thing But I haved not found any error please help

**Comment by bart-at-mobicage** [comment]
This is not the place to report this kind of issues. Maybe better to post your question on stackoverflow.com

Kind regards,
Bart
