### ISSUE TITLE
Problems with regional news

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1458]
service-952f6d5a-8dad-4dd3-9332-4002b55adc5a@rogerth.at has problems with sending regional news.

> Geachte
> Ik probeer al een aantal dagen een regionaal bericht te zetten bij promoties. Ik krijg echter telkens de boodschap dat er een fout is opgetreden. Het bericht lokaal publiceren gaat dan wel. Ik heb gisteren pas een bijkomende betaling gedaan om regionaal te publiceren omdat ik dacht dat er niet voldoende budget zou zijn. Ik heb momenteel nog een budget van 10388. Kan je dit eens nakijken aub? Alvast bedankt.

**Comment by lucasvanhalst** [comment]
Problem is here
https://github.com/our-city-app/mobicage-backend/blob/89aac244f2c01f43a316c811e2aff9dcc07e9aca/src/rogerthat/bizz/news/matching.py#L186

Newsitem was sent in 9 groups, you can only add 5 transactional defers at once iirc

**Comment by RubenMattan** [comment]
Update:
problem is https://github.com/our-city-app/mobicage-backend/blob/master/src/rogerthat/bizz/news/__init__.py#L1198 because oca calls news.publish from inside a transaction

**Comment by RubenMattan** [comment]
Fixed by https://github.com/our-city-app/mobicage-backend/commit/95124599a1fe9ffaf240a0e8ff77a888bb9ee132
