### ISSUE TITLE
Emergency numbers

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#146]
De App van destelbergen geeft onjuiste informatie ivm de dokter van wacht. Op momenten van wachtdienst duid deze aan dat er geen wacht is. 
Kan u het nodige dien om de mensen correct te verwijzen naar het centraal wachtnummer en/of de wachtpost. 
Mvg
Diego Schrans. 
Huisarts

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment]
We updated the info
