### ISSUE TITLE
Facebook review feedback

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1466]
## Review Feedback
**Approved**: user_friends
**Not Approved**: user_gender, user_birthday

#### user_gender feedback
While your screencast and notes provide a valid use case, we were unable to verify this use case when we logged into your app. Please ensure that your app has correctly integrated the requested permission, and resubmit for review so that we can complete testing.

#### user_birthday feedback
While your screencast and notes provide a valid use case, we were unable to verify this use case when we logged into your app. Please ensure that your app has correctly integrated the requested permission, and resubmit for review so that we can complete testing.

**Comment by bart-at-mobicage** [comment]
We'll have to find out why they say the cannot test the use case in our app. Should we give them access to a test dashboard?

**Comment by bart-at-mobicage** [comment]
Look at the Jabbeke review request to check the updated explanation of the use case of user_gender and user_birthday

**Comment by bart-at-mobicage** [comment]
Apparantly they still ended up in the Profile screen

> I've attached some screenshots that may help you understand my response better. You can find them here: 
![ss](https://scontent.fbru2-1.fna.fbcdn.net/v/t39.8008-6/73016354_406999013320128_8420809049150324736_n.png?_nc_cat=111&_nc_oc=AQkeWEGMdM8p3JoqpEJkFH0n5GQ31pGG9MdwYmCqRMozA_KkF2dXDebPH37ZeBmRTwk&_nc_ht=scontent.fbru2-1.fna&oh=77b5e320d8141e55b3ffc5c3c4c63fec&oe=5E1AB0E9)

**Comment by paullovachy** [comment]
Did you ever figure this out? Getting the same rejection notice - not sure how to correct it.

**Comment by lucasvanhalst** [comment]
Since they themselves have no idea (they accepted 5 apps, rejected the rest), this is pointless and a waste of time
