### ISSUE TITLE
New Facebook reviews needed

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1469]
Once we know a good procedure to get an approved review from Facebook (see #1466) we need to apply it to all our apps.

> ### App Review required to retain access to specific permissions or features     
> 
> As a result of changes to our platform, xxx will need to submit an App Review request by October 23, 2019 to retain access to platform data for the following permissions or features: **email** 
> 
> If xxx doesn't submit for App Review by the deadline, it may impact how it accesses data.
> 
>  If you are currently in Dev Mode, you will also need to switch your app to Live Mode after successfully completing App Review to maintain your current functionality.

**Comment by bart-at-mobicage** [comment]
user_friends and user_gender are still not approved, but user_friends, email and login are ok.

**Comment by bart-at-mobicage** [comment]
Look at the Jabbeke review request to check the updated explanation of the use case of user_gender and user_birthday

**Comment by lucasvanhalst** [comment]
Requested a review for jabbeke using a new video

**Comment by bart-at-mobicage** [comment]
I received mails for different apps mentioning that the FB integration doesn't work anymore.

> Your app Elisabeth Begijnhof has been restricted for creating a negative user experience in violation of our Platform Policies.
> 
> - Your app cannot be installed by new users.
> 
> For more details about your app's violation, please check your app's Contact Email. 

- Elisabeth Begijnhof
- Niel
- Alken

**Comment by lucasvanhalst** [comment]
- [ ] Beringen
- [ ] Kruisem
- [ ] Lochristi
- [ ] Jabbeke
- [ ] Merchtem
- [ ] Koksijde
- [ ] Lo-Reninge
- [ ] Onze Stad App
- [ ] Putte
- [ ] Staden
- [ ] Horebeke
- [ ] Bocholt
- [ ] Rogerthat
- [ ] Anzegem
- [ ] Elisabeth Begijnhof
- [ ] Zulte
- [ ] Zandhoven
- [ ] Wielsbeke Leeft
- [ ] Aalter
- [ ] Diksmuide
- [ ] Nazareth
- [ ] Herentals
- [ ] Bree
- [ ] Halle
- [ ] Herk-de-Stad
- [ ] Argenteuil
- [ ] Geetbets City-App
- [ ] Hageland City-App
- [ ] Niel
- [ ] Ninove
- [ ] Edegem
- [ ] Gentbrugge
- [ ] Wichelen
- [ ] Tienen
- [ ] Alken
- [ ] Assenede
- [ ] Borgloon
- [ ] Diepenbeek
- [ ] Dilbeek
- [ ] Halen
- [ ] Heers
- [ ] Hemiksem
- [ ] Herne
- [ ] Hooglede
- [ ] Hove
- [ ] Lanaken
- [ ] Maldegem
- [ ] Meulebeke

**Comment by lucasvanhalst** [comment]
Missing fb app:
- [ ] Pelt

**Comment by ThijsVDE** [comment]
Review complete and accepted

- [ ] Aalter
- [ ] Alken
- [ ] Anzegem
- [ ] Beringen
- [ ] Bocholt
- [ ] Borgloon
- [ ] Bree
- [ ] Diepenbeek
- [ ] Dilbeek
- [ ] Edegem
- [ ] Elisabeth Begijnhof
- [ ] Geetbets City-App
- [ ] Halen
- [ ] Halle
- [ ] Heers
- [ ] Hemiksem
- [ ] Herentals
- [ ] Herk-de-Stad
- [ ] Herne
- [ ] Hooglede
- [ ] Horebeke
- [ ] Hove
- [ ] Jabbeke
- [ ] Koksijde
- [ ] Lanaken
- [ ] Lo-Reninge
- [ ] Lochristi
- [ ] Maldegem
- [ ] Merchtem
- [ ] Meulebeke
- [ ] Nazareth
- [ ] Pelt
- [ ] Niel
- [ ] Ninove
- [ ] Putte
- [ ] Staden
- [ ] Wichelen
- [ ] Wielsbeke Leeft
- [ ] Zandhoven
- [ ] Zulte
- [ ] Affligem
- [ ] Beveren
- [ ] Destelbergen
- [ ] Hoeilaart
- [ ] Pelt
- [ ] Sint-Truiden
- [ ] Wortegem-Petegem

**Comment by lucasvanhalst** [comment]
Screw facebook
