### ISSUE TITLE
Publish news items via the app on your smartphone

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#147]
Our customers just give us an feature where we have to take notice from and put this on priority 1

They like the product but they compare the usability with facebook and tell us that it is not that user friendly when they want to broadcast news.
They need a laptop, desktop computer to do that.

So we have to make it possible with the same steps to broadcast News from their phone.

So these are the steps I have in mind  to do this:

1/ The owner of the application (our client/merchant) - verified by the app-mailadres - should have an extra button on his app to send out News.
2/ When the owner of the application wants to give access to his personnel to do this also he needs to be able to scan a QR-code in the dashboard to grant them acces. 
Idem as the inbox forwarders functionality in the dashboard. It also should be possible to delete them.
4/ All of the functionalities in news should be in there.
5/ It has to synchronize with the dashboard when a message was sent.
6/ Picture: camera, gallery and app-picture
7/ Show the complete message before sending - agree and publish

If you have more questions/suggestions shoot.

@bart-at-mobicage I just assigned this to check if i'm doing the right things ;-)
Thanks guys

**Comment by bart-at-mobicage** [comment]
@OSATOM, no need to assign the issue. We will pick it up :)

**Comment by bart-at-mobicage** [comment]
@abom, please work closely with @RubenMattan on this one.

@RubenMattan, specify small steps for @abom, like
- create the flow manually
- create the service role manually
- create the item manually & assign role
- create the flow, role and item programmatically
- TBD with Geert, Tom and Gert:
  - refactor the "settings > inbox forwarders" page, use 'Permissions and roles' setting page
  - show 'administrator' and 'inbox forwarder' roles
  - make sure that normal people like butchers etc. can understand this page.

**Comment by bart-at-mobicage** [comment]
Add a "App users & Roles" tab to the Settings page which looks like this:

Users (2) [**+**]

| Email | Inbox forwarder | Calendar admin | News publisher | |
|---|---|---|---|---|
| latapacanaria@belgacom.net | [x] | [x] | [x] | **delete** |
| bart@mobicage.com | [x] | [] | [] | **delete** |

* We won't remove the original inbox forwarder and calendar admin configuration pages
* The plus button next to Users (2) opens a popup with 
  * a search textfield (just like "settings > inbox" and "settings > agenda")
  * 3 checkboxes: inbox forwarder, calendar admin, news publisher

**Comment by abom** [comment]
The calendar admin should be added to which calendar? all of them?

**Comment by bart-at-mobicage** [comment]
Good point. You'll need to be able to select which calendar you want to assign that role to.
