### ISSUE TITLE
Jabbeke rss

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1470]
- [x] They want that news about traffic appears in both traffic & city news
  > items die bij verkeer komen komen niet bij nieuws, dit mag gerust dubbel. Bij algemeen hebben we normaal alles staan in rss en bij verkeer enkel de verkeersgerelateerde.
- [x] Skip events with a pubDate older than 7 days ago

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/commit/f44b36fd7ddbcb9538e624a911467fba5410be3f
