### ISSUE TITLE
Integration with Paddle websites 

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#1476]
- Make it possible to configure the integration with Paddle for a city (only for shop users)
- Add a cron to request the information from the city website (every night)
- Save the organisational units (city services) with their address and opening hours
  - Can be textual for now. We'll update the code once we're reworking the services and change the structure of the opening hours.
  - Show this info in When & Where
    - A long scrollable list with name, opening hours and address per organisational unit
    - When there are multiple city services in the app, it should be possible to map an organisational unit to a city service. In this case the opening hours and address of that city service must be synced automatically
- Disable the opening hours and address text areas under Settings when there is an integration with Paddle.

Docs: [PADPRO-Paddle-270919.pdf](https://github.com/our-city-app/oca-backend/files/3669508/PADPRO-Paddle-270919.pdf)
[Test environment details and more info on Monday](https://onzestadapp.monday.com/boards/168291742/views/1602403/pulses/288951749)

**Comment by lucasvanhalst** [comment]
Can be configured on dashboard
![Screenshot 2019-10-09 at 13 13 56](https://user-images.githubusercontent.com/6652304/66476756-aa059f80-ea96-11e9-97d7-9c51a93b72b7.png)

Decided against adding _all_ organisational units to when and where since it's already very long

![Screenshot 2019-10-09 at 13 12 40](https://user-images.githubusercontent.com/6652304/66476693-86daf000-ea96-11e9-81b0-e3eb6259390b.png)

**Comment by bart-at-mobicage** [comment]
- Check with Tom if we need to find a way to show multiple organization units in When & Where (eg. using tabs or accordions or ...)
- Don't show closing days that are in the past
- I think the opening hours are a bit messy, because when there are multiple lines possible per day, the first line makes it messy. In that case it wouldn't render the first opening hour on the same line as the day

> maandag:
> 10:30 - 12:00
> 
> dinsdag: 
> 10:30 - 12:00
> 
> woensdag: 
> 08:30 - 12:00 Gratis koffie
> 13:30 - 16:00 Enkel dienst Burgerzaken.
> 20:00 - 21:00
> 
> donderdag: 
> 08:30 - 12:00
> 
> vrijdag: 
> 08:30 - 12:00
> 
> zaterdag: 
> 09:00 - 11:45 Enkel dienst Burgerzaken

or

> maandag: 10:30 - 12:00
> dinsdag: 10:30 - 12:00
> woensdag: 
> 08:30 - 12:00 Gratis koffie
> 13:30 - 16:00 Enkel dienst Burgerzaken.
> 20:00 - 21:00
> donderdag: 08:30 - 12:00
> vrijdag: 08:30 - 12:00
> zaterdag: 09:00 - 11:45 Enkel dienst Burgerzaken

**Comment by lucasvanhalst** [comment]
the multiple organization stuff is not needed yet for tom, will update formatting
