### ISSUE TITLE
Bug in configuring target audience NEWS

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#1500]
- map is only shown after resize
- hovering the map does not show the name of the city (show not re-color when not editable)
- Budget show unlimited number of views
- [shop question](https://rogerthat-server.appspot.com/internal/shop/questions/6495108206166016)

**Comment by lucasvanhalst** [comment]
question should be fixed by the PR as well, it was just a visual bug and the item was never published regionally
