### ISSUE TITLE
Sint-Truiden: Build New App & fixe Bugs 31/12/2016

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#152]
Please build the new Sint-truiden -App after the bugs are fixed.
This should be ready at least at the end of december.

Please contact me when ready to put in the stores. 
We have to put them in the stores just for a couple of hours.

1/ MYDIGIPASS logo is not visible anymore. Please add the logo.
2/ MYDIGIPASS Button should not be "Authenticeren" but should be "Identificeren"
3/ When they instal the Sint-Truiden app it is still the old logo not the new and correct one as on the application. @GertCornelis 

![screenshot_20161213-141825](https://cloud.githubusercontent.com/assets/23034120/21141748/1e3bce76-c13f-11e6-9da2-b94ccf7a8884.png)

**Comment by bart-at-mobicage** [comment]
Bullets 1 and 2 are fixed. @GertCornelis, you check bullet3?

**Comment by bart-at-mobicage** [comment]
https://bob.rogerthat.net/build/1275/download/android
