### ISSUE TITLE
Opening hours shows 'closed' twice

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1530]
both in the list view and detail view

the second one shouldn't be shown

this happened when the currently shown time is an exception

<img width="499" alt="Screenshot 2020-02-17 at 12 38 44" src="https://user-images.githubusercontent.com/6652304/74650644-72181280-5182-11ea-81f7-cbfd49af19bc.png">

**Comment by RubenMattan** [comment]
also when there are 2 exceptions only 1 is shown

**Comment by RubenMattan** [comment]
1 comment is fixed
