### ISSUE TITLE
Vat validate for Spanish clients

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#154]
Is it possible the have a "VALIDATE" VAT check for Spanish VAT numbers
![schermafbeelding 2016-12-14 om 13 45 37](https://cloud.githubusercontent.com/assets/23034120/21182496/b6f10a68-c203-11e6-9847-2dc047f990c7.png)

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment]
related to https://github.com/our-city-app/oca-backend/issues/279
