### ISSUE TITLE
remove manual work for new services

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1543]
- remove manual work for setting group types on NewsSettingsService
- just set the group types based on organisation type
  - city -> city, events, traffic, polls
  - merchant -> events, promotions
  - emergency -> events
- for group type press, those services will have to be set manually (there's only a few anyway)
- remove broadcast_type option from news.publish

**Comment by RubenMattan** [comment]
don't automate for city services
