### ISSUE TITLE
Multi-step configuration wizard for ordering foods

### ISSUE THREAD

**Issue by FastGeert** [our-city-app/oca-backend#155]
Today the sandwich configurator is really nice to order a sandwich. 
But we want to be able to use this functionality also to order pizza, pasta, ... and multiple of these configurators per merchant application.

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!
