### ISSUE TITLE
fix spelling mistakes

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1561]
- totdate -> tot dat `Uw dienst zal niet zichtbaar zijn in de app totdate u de volgende problemen oplost`
- `Trankstation` -> `tankstation`

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/commit/6ad8bcc7fb715eb2759621fd2692c4ad7506670c
https://github.com/our-city-app/mobicage-backend/commit/1d9238a485a057b311d9ccc10b6cf41b3bd24665
