### ISSUE TITLE
Deleted merchant event was not deleted from the community service agenda

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#160]
In the Horebeke agenda there is an event of IMMO OSA (because merchant events appear in the Horebeke's agenda as well and IMMO OSA was in the Horebeke's app).

In the mean time IMMO OSA doesn't support the Horebeke app anymore and the event has been deleted. It should not be visible in the Horebeke's agenda anymore. Also, the participants are not loaded.

**Comment by bart-at-mobicage** [comment]
Manually removed the merchant event from the agenda. We must find out how it is possible that the event was still in there.

**Comment by bart-at-mobicage** [comment]
could not reproduce

**Comment by RubenMattan** [comment]
This issue occurres when the city service did not publish again...

The publish only happens when uitagenda is coupled

**Comment by abom** [comment]
@RubenMattan What is uitagenda?

**Comment by RubenMattan** [comment]
its a calendar database in belgium
it syncs events with our database & updates service data when finished (cron around 02:00)
