### ISSUE TITLE
News&Actions - determine targetgroup

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#162]
It is not longer possible to determine the target-group of you news&actions-message.

Please make possible that the target possibilities are reintegrated. This is one of the keyfeature to claim that OCA is the correct and marketing high target 1two1 communication tool:

Target-groups : 

- Male
- Female
- Age

Thanks

**Comment by bart-at-mobicage** [comment]
For this, we'll have to extend the code in rogerthat-backend. The `news.publish` service api call should be extended with a target_audience param (just like we had in messaging.broadcast). The target_audience info should be saved on NewsItem. When an app user downloads the news stream, we should filter out news items of the app user's age/gender does not match the configured target audience. Also, the newNewsItem call should not be sent to the app user.

**Comment by RubenMattan** [comment]
We will not do it like this bart.
Every news item will be shown to the user even if target_audience is enabled. but it will be shown lower in the news feed. So the filtering will be done on the clients (android, ios)

**Comment by OSATOM** [comment]
To make this clear why we ask this on marketing/sales side : 

It is powerfull to show on mid-long-term to our merchants what his/her customers are. Age/gender/Postal Code/ area/ what they spent and save/ ... so we can help them to do the correct actions to the correct audience to increase their revenue. Analyse the customers behavior for each merchant in OCA

**Comment by lucasvanhalst** [comment]
We must also not forget about the sort priority on the [news live update server](https://github.com/rogerthat-platform/rogerthat-kickserver/blob/master/src/news/factory.py#L453). It won't be able to correctly set the priority unless we provide it with more information about the user.
