### ISSUE TITLE
New & improved homescreen

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#1648]
Per community, there is a 'Homescreen' model stored on firestore (path /communities/{communityId}/homescreen).

This contains the following properties:
- version: if the model its structure is changed in a backwards-incompatible way, increment this number.
 If the client version < model version, the client is required to upgrade to the newest app version. before he can use the app again.
- homescreen:
  - type: 'embedded-app' | 'native'
  - content:
    - if the type is 'embedded-app', this contains the embedded app name and version.
       -> this means this model will have to be updated each time the embedded app is updated.
    - if the type is 'native': TBD (work for later)
- bottom navigation content:
  - buttons[]: array of buttons (min 2, max 5)
    - icon
    - label (for localization)
    - action: action url
    - badge_key: optional badge key. will be used by client to maybe show badge on some items (`messages` item will show unread message count) 
- bottom sheet content:
  - header:
    - title
    - expanded_title (or maybe not, it'll probably look janky if it changes mid-animation when swiping up or down)
    - subtitle
    - image: image shown on the top right of the bottom sheet when expanded
  - rows[]: rows of widgets. see MAP_SECTION_MAPPING
- languages[]: supported languages. May contain multiple values in case of border cities. this should always be the same as the subproperties of the `translations` property.
- default_language: the language to use when the phone its language is set to for example french, but languages[] array only contains english and dutch -> use this language.
- translations:
  - property per language, e.g. 'en', 'nl' or 'pt-BR'
    - value of this property is a map with the translation keys and values in that language.
    - if the value of a translation is not found in a particular language, we simply show the key. this allows us to be lazy and not translate anything in the first version.

be sure not to index any field of this model, see https://firebase.google.com/docs/reference/firestore/indexes

In case the bottom sheet rows contain opening hours, show open now/closed in the top right of the non-expanded bottom sheet. (only for structured openings hours)

What we need to change about the existing stuff:
 - new component to be added to MAP_LIST_SECTION_ITEM_MAPPING -> some kind of button or list of buttons: stroked button with an action behind it (for the button 'other city services')
 - opening hours needs to change completely. We basically need to move the entire opening hours logic to the client, which sucks. So, basically copy the structure of OpeningHours to this model including type, periods and exceptions. The logic of exceptions etc. all needs to be done by the client. The text needs to update every few minutes as to not show outdated information.
 - new behaviour of the existing bottom sheet: sliding up should change the content of the 'header', when not expanded only the title is visible, and the opening hours (if available). when expanded, show title, subtitle and logo.

**Comment by RubenMattan** [comment]
homescreen -> content ->  'embedded-app' don't save a version here (just use a global config. client should always have the latest version)

**Comment by RubenMattan** [comment]
bottom navigation content -> lets make it so if the action is not supported yet a message is shown to update

**Comment by RubenMattan** [comment]
bottom sheet content:
- remove expanded_title
- title shown when collapsed / subtitle only when opened
