### ISSUE TITLE
channel not reconnecting?

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#175]
Seen this at the development environment and on the tablets of the sales ppl.

When a service is being created a progress bar is shown, but never goes away. It looks like the channel gets disconnected, but doesnt automatically reconnect.

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by RubenMattan** [comment]
will be fixed by implementing new channel https://github.com/rogerthat-platform/rogerthat-backend/issues/49
