### ISSUE TITLE
Creating menu items with a URL behind it

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#197]
Extend the static content page with a new type of content: Web Page
The user should be able to enter a URL (with or without http:// prefix)

See `link` in `system.put_menu_item`
Eg. "mijn bibliotheek" in sint-truiden app

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved label and close the issue.

Thanks!

**Comment by bart-at-mobicage** [comment]
Duplicate of #409
