### ISSUE TITLE
News Via App

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#199]
When you take a picture and don't want to use that one and try to make another one the app crashes.

Thanks

**Comment by abom** [comment]
@OSATOM On the android/IOS app or what? the step of creating a news item? if so, i cannot reproduce it.

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved lable and close the issue.

Thanks!
