### ISSUE TITLE
Wrong event endtime

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#209]
> Geachte,
> 
> Ik weet niet of ik met onderstaand probleem bij jullie moet zijn of iemand anders, maar Het evenement https://www.uitinvlaanderen.be/agenda/e/sprookjesontbijt-aan-huis/31dc3183-05f9-48d7-8d74-a1cd8ba81584 verschijnt niet correct in de agende va stad app van Laarne. Het einduur die verschijnt is 00:09 ipv. 09:00 en ook de tekst is niet de laatste versie.

The end time of [this event](https://www.uitinvlaanderen.be/agenda/e/sprookjesontbijt-aan-huis/31dc3183-05f9-48d7-8d74-a1cd8ba81584) is shown as 00:09 instead of 09:00. The text is not up to date as well.

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved lable and close the issue.

Thanks!

**Comment by abom** [comment]
Cannot reproduce with newer events.
