### ISSUE TITLE
Birthday messages

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#21]
Send a happy birthday message to users who have their birthday.

- cron running every day
- on march the 1st, also query for feb 29 if the current year isn't a leap year

**Comment by OSATOM** [comment]
Branded message like welcome message.
Design has to be birthday-look&feel.
Message has to be customizable in the dashboard of the community/city.
Choice to use this feature has to be like choosing the events of the associations & merchants in the community/city Agenda (red/green button)

**Comment by lucasvanhalst** [comment]
Where do we save the birthday branding? Branding hash configurable per app in the 'App' model or one branding hash to rule them all in server settings?
