### ISSUE TITLE
Shop: FREE subscription product

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#219]
- a new free subscription product
- a FREE button next to Starter / Silver / Gold / Platinum

**Comment by lucasvanhalst** [comment]
What would the description / default comment of this product be? @bart-at-mobicage

**Comment by bart-at-mobicage** [comment]
I think the same as the normal subscription

**Comment by lucasvanhalst** [comment]
"Monthly subscription OUR CITY APP" -> "Free monthly subscription OUR CITY APP" ?

**Comment by bart-at-mobicage** [comment]
k
