### ISSUE TITLE
Kinshasa App's Agenda

### ISSUE THREAD

**Issue by samyongo** [our-city-app/oca-backend#230]
Hi,

On the Kinshasa App, the agenda is not displaying the 3rd date on the same event.
What happen is that I have selected Friday, Saturday and Sunday as event date but when I publish, only Friday and Saturday display and Sunday didn't. Additionally, when you add to the calendar, it also doesn't work.

Regards,

Sam Yongo

**Comment by RubenMattan** [comment]
Dashboard looks fine for me.

![screen shot 2017-02-24 at 16 05 39](https://cloud.githubusercontent.com/assets/1122760/23308366/422bc868-faab-11e6-84a3-3c8cf2ca0b65.png)

But indeed add to calendar does not work for multi date events
![2017-02-24 15 06 27](https://cloud.githubusercontent.com/assets/1122760/23308498/9dca9456-faab-11e6-98fd-a634bbd1a033.png)

**Comment by samyongo** [comment]
Hi,
I did a test on the dashboard and it works. The only issue now is on the IPhone7 when you click on the specific date to add to calendar, it doesn't work. I will try another phone.
