### ISSUE TITLE
Error when creating a service on dashboard

### ISSUE THREAD

**Issue by abom** [our-city-app/oca-backend#236]
When trying to create the first service on dashboard, i get the following exception:

> Traceback (most recent call last):
>   File "/usr/local/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
>     rv = self.handle_exception(request, response, e)
>   File "/usr/local/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
>     rv = self.router.dispatch(request, response)
>   File "/usr/local/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
>     return route.handler_adapter(request, response)
>   File "/usr/local/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
>     return handler.dispatch()
>   File "/usr/local/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
>     return self.handle_exception(e, self.app.debug)
>   File "/usr/local/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
>     return method(*args, **kwargs)
>   File "/home/abom/projects/oca-backend/build/mcfw/restapi.py", line 156, in post
>     result = self.run(f, parameters, kwargs)
>   File "/home/abom/projects/oca-backend/build/mcfw/restapi.py", line 174, in run
>     result = run(f, kwargs)
>   File "/home/abom/projects/oca-backend/build/mcfw/rpc.py", line 165, in run
>     result = function(**kwargs)
>   File "/home/abom/projects/oca-backend/build/mcfw/restapi.py", line 70, in wrapped
>     return f(*args, **kwargs)
>   File "/home/abom/projects/oca-backend/build/mcfw/rpc.py", line 149, in typechecked_return
>     result = f(*args, **kwargs)
>   File "/home/abom/projects/oca-backend/build/mcfw/rpc.py", line 127, in typechecked_f
>     return f(**kwargs)
>   File "/home/abom/projects/oca-backend/build/solutions/common/restapi/services.py", line 177, in rest_put_service
>     logging.warn(u'Service %s tried to save service information for customer %d', city_service_user, customer.id)
> AttributeError: 'NoneType' object has no attribute 'id'
> 

Do i need to do any thing before creating a service on dashboard?

**Comment by abom** [comment]
It happens when creating a new service (not when editing an existing one), while the main service customer's organization's type is not a "City" (community service).

**Comment by abom** [comment]
Sorry, forgot to self-assign the issue.

**Comment by bart-at-mobicage** [comment]
I wouldn't change the behaviour, let's just fix the NullPointerException.
`logging.warn(u'Service %s tried to save service information for customer %d', city_service_user, customer.id)`
Change `customer.id` to `customer_id`
