### ISSUE TITLE
Validate scheduled timestamp when sending news (it needs to be in the future)

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#238]

**Comment by abom** [comment]
On dashboard?, i think it's done and the user cannot select a date/time in the past.

**Comment by RubenMattan** [comment]
Servertime:"2017-02-24T15:45:28.308161Z"
Sceduled time: Fri, 24 Feb 2017 15:45:00 GMT

**Comment by RubenMattan** [comment]
I guess the user selected it and waited 28 seconds before submitting...
Maybe server side just reset scheduled timestamp when its in the past

**Comment by abom** [comment]
We can allow scheduling news only after a preset offset n minutes. Or better, to give a warning/error when submitting the news item that the scheduled date/time has passed and is not valid anymore.

**Comment by RubenMattan** [comment]
Last one is good!
