### ISSUE TITLE
Validate name when updating service

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#244]

**Comment by abom** [comment]
@RubenMattan On shop or dashboard, also anything other than limiting the length (already there)?

**Comment by RubenMattan** [comment]
Well the name should have a max length of 50
see rogerthat.bizz.profile._validate_name

**Comment by abom** [comment]
Yes, it already checks for the name #240 .

**Comment by RubenMattan** [comment]
Yeah can't remember why i created 2 issues...
