### ISSUE TITLE
New Merchants/Care/Associations

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#245]
When users download for the first time their City-App they ask to have their own app.
That messages is sent to info@mobicage.com but should be modified to each city.

So when I am asking for my own app in Lochristi/Sint-Truiden the information should be sent to ........@lochristi.be/ .....@sint-truiden.be

We should be able to modify this emailadress for each city because we don't want that workload anymore.

Thanks

**Comment by bart-at-mobicage** [comment]
At https://rogerth.at/mobiadmin/apps (Gert has access to this page) you can provide the **Contact email address**, which is used by the welcome flow. If the contact email is empty, then info@mobicage.com is used.
