### ISSUE TITLE
A "Try" button next to the "Publish" button

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#249]
Add a "Try" button next to the publish button. When clicking it explain that this will push the updates to only 1 user. Let them fill in the email address (use the search index under the hood, like on the users & roles page under settings). Pre-fill that email address the next time they click try so they don't have to re-enter it every time.

Execute `system.publish_changes` with the `friends` param (list with 1 item in this case). See https://github.com/rogerthat-platform/rogerthat-backend/issues/106

**Comment by siddiquagig** [comment]
Can we have a ETC of this issue so we can update the customer.

Thanks!

**Comment by bart-at-mobicage** [comment]
@siddiquagig, there is no specific customer involved in this ticket

**Comment by siddiquagig** [comment]
ok Bart... Thanks
