### ISSUE TITLE
Dashboard: News - delayed broadcast 

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#25]
![screen shot 2016-11-10 at 14 11 46](https://cloud.githubusercontent.com/assets/17762105/20177984/b0c34058-a74f-11e6-81d1-1c24e9afd215.png)

* Scrolling issue happens when pressing next until that last step, and then press back.
* Calendar icon should be clickable

**Comment by lucasvanhalst** [comment]
Seems to be fixed already

**Comment by bart-at-mobicage** [comment]
On which branch did you test?
* It still occurs when you press next until you reach the last step. Then press back, click the checkbox  and then click the clock icon. 
* The calendar icon is still not clickable.
