### ISSUE TITLE
Error when saving customer

### ISSUE THREAD

**Issue by samyongo** [our-city-app/oca-backend#266]
Hi,

I just want to report that I have been getting this error on Kinshasa App
"Failed to save customer service. Please contact mobicage."
Is there something that I m doing wrong?

Sincerely,

Sam Yongo

**Comment by RubenMattan** [comment]
Hello,

The last error i see regarding to your service is
```DuplicateBroadcastTypeException: 60006 - Duplicate broadcast type - {'broadcast_type': u'Les plats du jour'}```

**Comment by samyongo** [comment]
Yes I did realize that. They were more then 4 which I have removed but now I m getting this error:
"Une erreur inattendue est apparue. S'il vous plaît essayer à nouveau."

Regards,

Sam Yongo

**Comment by samyongo** [comment]
Dear Ruben,

This is happening when I click on the button that say publish the modifications

Regards,

Sam Yongo

**Comment by RubenMattan** [comment]
I removed all duplicates and now its working.
