### ISSUE TITLE
Setting up multiple address or location under one client

### ISSUE THREAD

**Issue by samyongo** [our-city-app/oca-backend#267]
Hi,

I would like to know how I can setup multiple address for a client because the apps allow only one. 

Please advise this can be done and how?

Regards,

Sam Yongo

**Comment by bart-at-mobicage** [comment]
Hi Sam,

**Search** for you customer in the Business Admin, select the **Service** tab and press the **Add location** button. Using this function you can "clone" the service into a new one with a different address. When you login to the dashboard you can choose which location you want to use.

**Comment by samyongo** [comment]
Dear Bart,

When I login on https://mobicagecloudhr.appspot.com/internal/shop and click on the service tab, there is not add location button.

Regards,

Sam Yongo

**Comment by bart-at-mobicage** [comment]
Hi Sam,

I made sure that the button appears for you. Can you close this issue after you verified it works?

Regards,
Bart

**Comment by samyongo** [comment]
Dear Bart,

I have seen the service button but when I try to add an additional location I m getting an error.

Regards,

Sam Yongo
![error](https://cloud.githubusercontent.com/assets/26000733/25221423/f93b7504-25ac-11e7-8a5c-72cc3aed6d56.jpg)
