### ISSUE TITLE
Services page with categorizing, paging and search

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#271]
Right now, the services page of a community service can work, because we have max around 100 services per city. But once we start with very big cities, this list may become too long.

- Group the services by organization types into tabs.
- Implement paging (automatically while scrolling down)
- Implement a search

**Comment by siddiquagig** [comment]
Can we have a ETC of this issue so we can update the customer.

Thanks!

**Comment by bart-at-mobicage** [comment]
@siddiquagig, there is no specific customer involved in this ticket

**Comment by siddiquagig** [comment]
ok 
Thanks Bart
