### ISSUE TITLE
Failed to log client error to server

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#273]
13/Mar/2017:20:01:22 +0100 "POST /mobi/rest/system/log_error HTTP/1.1" 500 225 https://rogerth.at/flex/ "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"

Incorrect type received for parameter 'errorMessage'. Expected <type 'unicode'> and got <type 'dict'> ({}).

**Comment by siddiquagig** [comment]
Hi,
Can we have a ETC of this issue so we can update.

Else If the issue is solved please put the status_resolved lable and close the issue.

Thanks!

**Comment by RubenMattan** [comment]
duplicate of https://github.com/rogerthat-platform/rogerthat-backend/issues/188
