### ISSUE TITLE
News & Actions

### ISSUE THREAD

**Issue by samyongo** [our-city-app/oca-backend#275]
Hi,

I would like to change the style of my news items such as (font size, type, Underline etc...) before publishing, Is there anyway I can change this setting if so owe? The configuration I m looking for is the one similar to the one below> 
![interface](https://cloud.githubusercontent.com/assets/26000733/23932110/6b8eebba-0936-11e7-8888-cb715277b321.png)

Regards,

Sam Yongo

**Comment by RubenMattan** [comment]
Hello,

The only way to underline etc is to use markdown

**Comment by bart-at-mobicage** [comment]
Markdown is not yet supported on iOS. The implementation is almost finished: https://github.com/rogerthat-platform/rogerthat-ios-client/pull/78
