### ISSUE TITLE
When creating an spanish merchant automatically select spain and spanish

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#278]
https://docs.greenitglobe.com/gig/proj_actives/issues/8

**Comment by siddiquagig** [comment]
Can we have a ETC of this issue so we can update.

**Comment by siddiquagig** [comment]
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!
