### ISSUE TITLE
Allow Spanish VAT validation

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#279]
change request: https://docs.greenitglobe.com/gig/proj_actives/issues/7

**Comment by siddiquagig** [comment]
Can we have a ETC of this issue so we can update the customer.

Thanks!

**Comment by bart-at-mobicage** [comment]
Disable the VALIDATE button by default. Enable the VALIDATE button when the entered VAT starts with "BE" or a number. 

![captura](https://cloud.githubusercontent.com/assets/17762105/24141611/48e4e478-0e24-11e7-8638-fcbb6687278f.png)

**Comment by RubenMattan** [comment]
temporary fix is disable vat for other countries https://github.com/our-city-app/oca-backend/issues/291
