### ISSUE TITLE
Customer self-signup

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#282]
Create a (mobile-friendly) unauthenticated signup page in the shop. This page needs to be translated into the customer's language (browser language).

Ask the following things:
- Application
  - City
  - Organization type
    - Checkboxes: Merchant / Care institution / Association
- Enterprise
  - Name
  - Street
  - Zip code
  - City
  - VAT number
- Entrepreneur
  - Name
  - Street
  - Zip code
  - City
  - Email
  - Phone number
  - Website
  - Facebook
- Functionality
  - Checkboxes: Loyalty / E-shop / Reservations

Store this info in the datastore.

Create an inbox message in the inbox of the main community service of the city app.
- Show a summary
- Show two buttons
  - OK
    - Will create the customer + contact + order + service (based on the stored info in the database)
    - Will send the login data in an email to the customer
  - Not OK
    - Ask for the reason why and ask how the customer can contact the city
    - Send an email to the customer with the reason and contact method
    - It must be possible for the city to click the OK button after they're contacted by the customer

**Comment by bart-at-mobicage** [comment]
The signup form needs to replace this paper version

![img_4044-1](https://cloud.githubusercontent.com/assets/17762105/23959129/990fd1da-09a4-11e7-9421-6e8979e169dd.JPG)

**Comment by siddiquagig** [comment]
Can we have a ETC of this issue so we can update the customer.

Thanks!

**Comment by bart-at-mobicage** [comment]
There is no specific customer involved in this ticket
