### ISSUE TITLE
Make the rogerthat start page customizable

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#284]
At www.onzestadapp.be we want to create a login button which will open rogerth.at in an iframe, or maybe some other solution... TBD.

The rogerth.at login page now contains an image with a woman playing with her smartphone. We want to make this customizable. When coming from www.onzestadapp.be, we want to show an other login page. With the OCA logo and the background which is used at www.onzestadapp.be

Maybe we can implement this by using a query parameter at rogerth.at --> rogerth.at?source=ourcityapp
Feel free to suggest another way of implementation.

**Comment by siddiquagig** [comment]
Can we have a ETC of this issue so we can update the customer.

Thanks!

**Comment by bart-at-mobicage** [comment]
There is no specific customer involved in this ticket

**Comment by siddiquagig** [comment]
ok 
Thanks Bart

**Comment by RubenMattan** [comment]
Instead of adding a source param, we should goto https://rogerth.at/ourcityapp and that url should be handled by oca-backend

**Comment by abom** [comment]
@bart-at-mobicage @RubenMattan A new page should be created or just replace the logo, background...etc?

**Comment by bart-at-mobicage** [comment]
I like Ruben's idea to create a new page in oca-backend. This way we have more control about the style of the page.

- The `Sign in` button can still point to `/mobi/rest/user/login`.
- The `Forgot password?` link should also be handled by oca-backend. 
  - The `Send instructions` button can still point to `/mobi/rest/user/reset_password`
- Add a `Sign up` button which goes to the signup page created at #282

When this is finished, we need to add an entry in the apache configuration to proxy `app.onzestadapp.be` to `rogerth.at/ourcityapp`

**Comment by abom** [comment]
@bart-at-mobicage Should follow the same style as the signup page then?

**Comment by bart-at-mobicage** [comment]
I would like you to try with this background image first: http://ourcityapps.com/wp-content/uploads/2015/09/Wallpaper_OnzeStadApp_back.jpg - such that it looks like the website

If it doesn't look good with this green background, then we can change it to the gray one which is used in the signup page.

**Comment by abom** [comment]
I think that the work on the login page would be related to the work on the signup page (#282), the pages that are exposed to public in general, we may have a base layout for all of them...etc.

Even after finishing the work on this (the login page), we will face lots of merge conflicts as the modifications will likely be in the same source files.

So, what to do with the branches? wait for #282 to be merged first?

**Comment by bart-at-mobicage** [comment]
you can start your new branch from the `2_0_x.282.customer_self_signup` branch
