### ISSUE TITLE
Update the events html5 app 

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#296]
In Brussels there are just too many events. Let's store the first 100 events into serviceData and load the other events using rest calls while scrolling down the html5 app.

**Comment by bart-at-mobicage** [comment]
Maybe an idea to build a cache in local storage, and add a param a query on `modified_since` in the API call?

**Comment by RubenMattan** [comment]
Can always improve in the future, for now we need to get rid of events in service data

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/908

For now i only implemented the branding, but the events are still saved in service data (i commented where we need to change some code)
