### ISSUE TITLE
Dashboard: Functionalities page

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#312]
This ticket continues on #307. You can continue working on that branch.

- Remove the functionalities from the new `/customers/signup` page
  - Automatically add these 5 modules
    - BROADCAST
    - BULK_INVITE
    - QR_CODES
    - STATIC_CONTENT
    - WHEN_WHERE
- Remove the `Coaching Sessions / News` (Dashboard) page from the dashboard
- Replace it by the new `Functionalities` page
  - This button has the same style as the `inbox` / `news` / ... navigation buttons
  - Show the 6 major functionalities in tiles
    - News & Actions
    - Loyalty
    - E-Shop (= advanced order)
    - Sandwich reservations
    - Restaurant reservations
    - Menu Card
    - Agenda
  - A tile contains
    - the functionality name (clickable)
    - a `fa-cog` icon to go to the settings of that functionality
    - a video
      - in case the functionality is enabled, this will be a tutorial video
      - in case the functionality is not enabled, this will be a video which shows why people would use this functionality 
    - a description
    - at last, a line which say "Enabled" or "Disabled" on the left, and a switch (like an [ios switch](http://ivomynttinen.com/content/3-blog/20150928-ios-design-guidelines/ios-switch.jpg)) to enable/disable the functionality
      - News cannot be disabled

Roel will create a design for the tiles at Tuesday, you can already start on the basic layout of the page, the modelling, the bizz methods to enable/disable functionalities etc.

On this sketch I've put 2 tiles next to each other, but there will be 3 tiles next to each other.
![img_4094](https://cloud.githubusercontent.com/assets/17762105/24808252/5052ed28-1bbb-11e7-8b83-2cf711b6a7bd.JPG)

**Comment by abom** [comment]
I think that we need to merge #320 first.

**Comment by bart-at-mobicage** [comment]
Ok, no problem. Because we're falling behind in reviewing your work, you can always create your branches from an existing branch that needs review, if you need stuff from that branch.

**Comment by bart-at-mobicage** [comment]
you can implement #340 first

**Comment by bart-at-mobicage** [comment]
I received the mockups from Roel.

[New-dash-OSA.pdf](https://github.com/our-city-app/oca-backend/files/972902/New-dash-OSA.pdf)
[OSA mockedup-CSS.txt](https://github.com/our-city-app/oca-backend/files/972905/OSA.mockedup-CSS.txt)
