### ISSUE TITLE
Contact form error on onzestadapp.be

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#315]
![screen shot 2017-04-10 at 10 44 15](https://cloud.githubusercontent.com/assets/17762105/24853229/a71f75d8-1dda-11e7-91f5-e28d33f45853.png)

**Comment by RubenMattan** [comment]
SMTP Error: Could not authenticate.

**Comment by OSATOM** [comment]
solved

<http://www.onzestadapp.be/>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk ons nieuwjaarsfilmpje! <https://www.youtube.com/watch?v=kc02ZHOMc3g>



2017-04-10 10:44 GMT+02:00 Bart Pede <notifications@github.com>:
