### ISSUE TITLE
Update translation

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [our-city-app/oca-backend#317]
this issue was created on https://docs.greenitglobe.com 

https://docs.greenitglobe.com/gig/proj_actives/issues/23
=================================================================================
We updated some translations and translated new terms. The terms updated are from https://mobicagecloudhr.appspot.com/internal/shop, so no terms in mobile phone are updated.

Can you apply these updates?

Thank you.

**Comment by bart-at-mobicage** [comment]
Done (00be568)
