### ISSUE TITLE
Failed to add a link in a picture (static content)

### ISSUE THREAD

**Issue by AnthonyMaes** [our-city-app/oca-backend#337]
When you try to put a link underneath a picture/image in a static content following screen keeps blocking:
![schermafbeelding 2017-04-27 om 14 39 33](https://cloud.githubusercontent.com/assets/25529887/25483814/afa65232-2b57-11e7-8288-dce54e2e8317.png)

**Comment by bart-at-mobicage** [comment]
Solved by #390
