### ISSUE TITLE
Customer signup improvements

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#340]
I received a comment about #307
- The accept/deny buttons for accepting/denying an application request of a merchant would be more clear and self-explaining if they had text as well:
  - `✓ Accept application`
    - will have to result in an email to the merchant. Roel will design this email.
  - `✖ Deny application`
- The accept/deny buttons also need to be at the inbox message detail page

**Comment by abom** [comment]
Regarding the email sent when accepting the application, it's the same email that's sent when creating a service, should we change it?

**Comment by bart-at-mobicage** [comment]
I think it will be changed to something new. Roel or @OSATOM will create this email.

**Comment by abom** [comment]
@bart-at-mobicage Can you assign @OSATOM or Roel for the email design?

**Comment by abom** [comment]
Blocked until the email design is finished.
