### ISSUE TITLE
Signup procedure review

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#353]
Hi @OSATOM,

Can you and your team provide us with the Dutch and English texts that need to be shown during the different steps in the signup procedure.

After step 5 an e-mail will be sent to the user. Please provide the content for this email as well.

1. 
![screen shot 2017-05-12 at 08 37 12](https://cloud.githubusercontent.com/assets/17762105/25986048/21f48f06-36ee-11e7-85c0-890a1b1af728.png)

2.
![screen shot 2017-05-12 at 08 37 42](https://cloud.githubusercontent.com/assets/17762105/25986064/3356734a-36ee-11e7-88e6-51be6da35209.png)

3. 
![screen shot 2017-04-28 at 12 58 59](https://cloud.githubusercontent.com/assets/17762105/25986081/4c40cfae-36ee-11e7-87b9-d4068df08eaa.png)

4.
![screen shot 2017-04-28 at 13 00 00](https://cloud.githubusercontent.com/assets/17762105/25986089/581d545a-36ee-11e7-9fd3-ece491384b04.png)

5. 
![screen shot 2017-04-28 at 13 00 46](https://cloud.githubusercontent.com/assets/17762105/25986102/655541c8-36ee-11e7-8e10-ef46189da764.png)

**Comment by bart-at-mobicage** [comment]
In step 3 and 4, "Street" should be renamed to "Address", because the user needs to provide street + number.

**Comment by OSATOM** [comment]
translation done
