### ISSUE TITLE
Review of the signup request review procedure

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#354]
Hi @OSATOM,

Can you and your team provide us with the Dutch and English texts that need to be shown during the review by a city of a signup request.

Also, please provide us with the content of the email that will be sent to the merchant when the city accepts the signup request, and when the city denies the request (the city will provide the reason in an input box when they press "Deny")

1. City inbox
<img width="1261" alt="screen shot 2017-05-12 at 08 41 40" src="https://cloud.githubusercontent.com/assets/17762105/25986247/4835b00e-36ef-11e7-8b82-819751903e82.png">

2. Message detail
<img width="1017" alt="screen shot 2017-05-12 at 08 42 06" src="https://cloud.githubusercontent.com/assets/17762105/25986254/53910d7c-36ef-11e7-94ef-5aa85cc37b19.png">

3. Accept application
![screen shot 2017-05-12 at 09 04 05](https://cloud.githubusercontent.com/assets/17762105/25986889/f556093a-36f1-11e7-8abc-cba9f8d3162f.png)

4. Deny application
![screen shot 2017-05-12 at 09 01 35](https://cloud.githubusercontent.com/assets/17762105/25986767/8dabb172-36f1-11e7-856e-c10c7861ef36.png)

**Comment by bart-at-mobicage** [comment]
- 1 & 2. The Accept and Deny buttons shouldn't have a different font
- 4. The Deny popup shouldn't immediately show required fields are missing

**Comment by OSATOM** [comment]
Translation done
