### ISSUE TITLE
Review of the login page

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#355]
Hi @OSATOM,

Can you and your team provide us with the Dutch and English texts that need to be shown at the login page.

1. Login page
![screen shot 2017-05-12 at 08 46 53](https://cloud.githubusercontent.com/assets/17762105/25986278/7a6502dc-36ef-11e7-9210-c0ca4fd6223c.png)

2. This is the forgot-password email

> Dear Lochristi,
> 
> We have received your password reset request for Our City App. Please use this secure URL to reset your password within 5 days.
> 
> https://rogerth.at/customers/setpassword?email=lochristi%40foo.com&data=...
> 
> To reset your password, please enter your password twice on the page that opens.
> 
> Thank you for using Our City App!
> 
> - The Our City App Team
> http://ourcityapps.com
> 

3. Reset password page
![screen shot 2017-05-12 at 09 23 51](https://cloud.githubusercontent.com/assets/17762105/25987521/ae8f07ec-36f4-11e7-8921-cc874fd2847e.png)

**Comment by OSATOM** [comment]
done

**Comment by OSATOM** [comment]
translation is done
