### ISSUE TITLE
Review of the functionalities page

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#356]
Hi @OSATOM,

Can you and your team provide us with the Dutch and English texts that need to be shown at the "Functionalities" page.

Also, please provide us with the youtube links per functionality. One links for a video when the functionality is active, and another link in case the functionality is inactive.

1. The Functionalities page
![screen shot 2017-05-12 at 08 53 26](https://cloud.githubusercontent.com/assets/17762105/25986494/7dee2194-36f0-11e7-9511-2ab6ab92f597.png)

2. Agenda was activated by the user
![screen shot 2017-05-12 at 09 08 00](https://cloud.githubusercontent.com/assets/17762105/25987013/7182bb20-36f2-11e7-8f48-fcca1a466ee8.png)

3. The orange info button was clicked
![screen shot 2017-05-12 at 09 08 19](https://cloud.githubusercontent.com/assets/17762105/25987021/7af597fe-36f2-11e7-95ef-974b7596ee17.png)

**Comment by OSATOM** [comment]
Translation done
