### ISSUE TITLE
Migration: Reschedule scheduled tasks

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#378]
Create a script to reschedule the following tasks:
- [x] scheduled broadcasts
- [x] scheduled broadcasts on social media
- [ ] select loyalty lottery winner
- [ ] select city-wide loyalty lottery winner

<img width="1101" alt="screen shot 2017-06-15 at 14 31 59" src="https://user-images.githubusercontent.com/17762105/27181326-6b7970ac-51d7-11e7-9226-f1b48aed38b1.png">

**Comment by abom** [comment]
As mentioned by @bart-at-mobicage, last two items can be achieved by running the loyalty cron job.
