### ISSUE TITLE
second page registration

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#398]
When the first page is filled in, the second page for contact information of the person is filled in automatically. This should be empty so it has to be filled in.
Because it is most of the time not the same information.

**Comment by FastGeert** [comment]
With the update of @abom yesterday, we filled it up based on the VAT validation, just like we have in the business admin. 

Your comment remains correct if no VAT number if used to sign up.

**Comment by abom** [comment]
@FastGeert Yes, but the VAT validation and auto-filling happens at the first page (enterprise information).
