### ISSUE TITLE
Send emails if City approves

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#400]
![schermafbeelding 2017-07-03 om 12 31 01](https://user-images.githubusercontent.com/26439611/27789167-baf628ec-5feb-11e7-82eb-43492d0dc590.png)
I think the names "info" and "Rogerthat" should be changed if possible, to (name city)app
so that it is immediately clear for the user what the mail is about.
in de second mail i would change "dienst aangemaakt" by login and password
just a suggestion he -:)

**Comment by bart-at-mobicage** [comment]
+ There seem to be placeholders in the email body?

**Comment by abom** [comment]
https://github.com/our-city-app/oca-backend/pull/396/commits/9e8ee19cb9ebaae72473ca4f14ef4a4be2c1602d
