### ISSUE TITLE
interesting extra features

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#402]
Here are some additional features that I think are interesting
 
 - [ ] For static content, the additional click needed now should be left (still in dashboard). #409
 - [ ] The additional QR code (eg stapelstraat) can not be scanned with another city app,
 what makes it more interesting for tourism purposes. rogerthat-platform/rogerthat-backend#223
 - [ ] The appointment system should better make it interesting for many additional sectors (doctors / hairdressers ...). #410

**Comment by bart-at-mobicage** [comment]
@stevendepaepe, thanks for the feature requests.

For your first bullet, do you mean when adding a website to static content?

**Comment by stevendepaepe** [comment]
Yes, now it is possible in Rogerthat but not in the dashboard

**Comment by bart-at-mobicage** [comment]
I created separate feature requests
