### ISSUE TITLE
Changing contact and setting PO number of free orders/charges

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#423]
In the past it was possible to set the PO number or to change the contact of orders. However, since everything is free, orders are immediately signed and it has become impossible to do this.

**Comment by lucasvanhalst** [comment]
Some questions:
- Where should the 'set po number' button go
- Where does the 'Change contact' button go and what exactly does it need to do. Does it have to re-generate the invoice order pdf and invoice? Do we want this to be possible?

**Comment by bart-at-mobicage** [comment]
Talked to Tom. Won't fix.
