### ISSUE TITLE
FB and Twitter integration doesn't work with dashboard.onzestadapp.be 

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#430]
We can not add multiple domains to the Rogerthat facebook app so we'll have to come up with a different solution.

Creating different apps for the dashboard.onzestadapp.be and rogerthat-server.appspot.com domains?

**Comment by bart-at-mobicage** [comment]
![image001](https://user-images.githubusercontent.com/17762105/28769348-6c66d91e-75db-11e7-982b-b122ad0b4a20.jpg)

**Comment by abom** [comment]
For Twitter, it should be working normally?
