### ISSUE TITLE
Memory limits reached when uploading osa-loyalty app 

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#434]
/admin/osa/launcher/app/post --> Exceeded soft private memory limit of 256 MB with 361 MB after servicing 13605 requests total

**Comment by abom** [comment]
Does this mean that the handler of /admin/osa/launcher/app/post is the cause of this memory problem?
Or it's just happened when serving a request to /admin/osa/launcher/app/post?
I'm hardly getting what is really meant by this error.

**Comment by abom** [comment]
I see a little improvement if the uploads to gcs are done in chunks if possible (if it's not already done this way).

**Comment by abom** [comment]
Don't know if uploading the file is the main reason.
Now the file is written to gcs in chunks.

**Comment by bart-at-mobicage** [comment]
> Don't know if uploading the file is the main reason, but now the file is written to gcs in chunks.

Works as a charm
