### ISSUE TITLE
Event with multiple dates only shows first date

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#438]
See https://rogerthat-server.appspot.com/internal/shop/questions/6621295077228544

- Event with multiple dates 
- Only first date is shown in the app

Example: 
<img width="740" alt="screen shot 2017-08-22 at 16 09 07" src="https://user-images.githubusercontent.com/6652304/29569627-5d23e354-8754-11e7-9e0f-ca888318131e.png">
Event is only shown on the 28th in the app, and not on 29, 30 or 31

**Comment by abom** [comment]
As @bart-at-mobicage mentioned, it would be better to list all the dates and their events, instead of just listing the first date, and the user needs to go to event details to see other dates.
