### ISSUE TITLE
No apps shown in target audience step in publish-news message flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#440]
In the message flow to send out a news item, no apps are being shown for this customer. `service.data.broadcast_target_audience` must have been an empty array. The customer has `be-geraardsbergen` as default app and `rogerthat` as second app.

![img_5456](https://user-images.githubusercontent.com/17762105/29158224-8770da9e-7daa-11e7-8f01-78db369f26cf.PNG)

**Comment by abom** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/257
