### ISSUE TITLE
Unexpected error when community service opens merchant dashboard

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#443]
Happened for the service "Veda" when opening merchant dashboard via the "Services" tab.

![2017-08-10 11 30 02](https://user-images.githubusercontent.com/17762105/29164302-440d5b8c-7dbf-11e7-8a8a-b606b8d42bf9.jpg)

**Comment by lucasvanhalst** [comment]
Could only reproduce this once...
