### ISSUE TITLE
Prevent hidden_city_wide_lottery module from being overwritten

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#447]
The `hidden_city_wide_lottery` module of the Berlare service disappeared.

I think this is possible by saving the Berlare customer in the shop. Then the `modules` list is overwritten.

Investigate how this can happen and prevent this. Check all code paths where modules are set/added/deleted.

**Comment by bart-at-mobicage** [comment]
It looks like it wasn't removed from the `modules` list. Still, double-check if it can be removed by accident.

**Comment by bart-at-mobicage** [comment]
It happened for Diskmuide as well. They enabled the LOYALTY functionality, setup a city-wide lottery. And then the LOYALTY tab disappeared.

**Comment by bart-at-mobicage** [comment]
Ok, correction...

If a merchant has the LOYALTY module and enable the city-wide lottery in the settings, this means they don't have their own lottery/stamp card/revenue discount formula. When the user scans at the loyalty terminal, then he only participates in the city-wide lottery

A city should not have the LOYALTY module if they want a city-wide lottery. This is a hidden module (HIDDEN_CITY_WIDE_LOTTERY) that needs to be enabled by us.

Make sure cities can not enable the LOYALTY module if they have HIDDEN_CITY_WIDE_LOTTERY.

**Comment by bart-at-mobicage** [comment]
I had a chat with Tom.

In the "Functionalities" page, if a service has the CITY_APP module, then don't show the LOYALTY functionality. Instead, show the HIDDEN_CITY_WIDE_LOTTERY functionality (with title "City Tombola").

Still add business rules to prevent enabling LOYALTY (eg. from the shop or using another city dashboard which is in the same app).

**Comment by RubenMattan** [comment]
You can't show the HIDDEN_CITY_WIDE_LOTTERY this is hard coded!

**Comment by abom** [comment]
@bart-at-mobicage Then, we have two options

- Enable/Disable this module manually by us
- Make it possible to activate it from dashboard, but we will need to re-write some parts, as @RubenMattan said, it's hard coded.

What do you think?

**Comment by bart-at-mobicage** [comment]
option 2
