### ISSUE TITLE
Agenda & broadcast news by Phone

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#455]
You cannot broadcast news anymore by your phone.
The last step is wrong.

Agenda (Buurtwerking -App) 
The events are duplicated.

**Comment by abom** [comment]
The first issue is a duplication of https://github.com/our-city-app/oca-backend/issues/440

**Comment by abom** [comment]
@OSATOM 
I don't see any duplicated events (on dashboard).
They are duplicated on the app or where exactly? or you have already deleted them?

**Comment by bart-at-mobicage** [comment]
probably in the app: https://play.google.com/store/apps/details?id=com.mobicage.rogerthat.be.elisabeth.begijnhof&hl=en

**Comment by abom** [comment]
At the end, this issue can be reproduced only in an app with city app solution module enabled, what happens exactly is that the cron job of gathering events includes own service events.

**Comment by OSATOM** [comment]
Hi,

in the "Buurtwerking" app you cannot broadcast news from your phone and all
events that are put in the agenda-functionality in the dashboard are
duplicated in the app?

Thanks

[image: Inline afbeelding 1]

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-08-21 11:42 GMT+02:00 Abdelrahman Ghanem <notifications@github.com>:

**Comment by bart-at-mobicage** [comment]
Hi @OSATOM

Both problems are solved :-)
