### ISSUE TITLE
Auto-form complete changed the city of my signup request

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#462]
In step 1 I selected "OSA Demo 3"

In step 2 I started typing "Antw..." in the address field. Chrome suggested "Antwerpsesteenweg 19". I clicked on the suggestion and Chrome pre-filled the city field with "Lochristi".

However. Chrome also changed the city field in step 1 which of course I didn't see.

Is their a way we can prevent this? Maybe by changing the `id` attr of the `select` of step1? Or can we set some metadata to prevent browser from changing the input?

![screen shot 2017-08-23 at 10 31 12](https://user-images.githubusercontent.com/17762105/29606419-86aa321a-87ee-11e7-9060-9e5217670f3c.png)

**Comment by lucasvanhalst** [comment]
autocomplete=off on the form or on form elements

**Comment by abom** [comment]
The problem is the auto-fill feature of the browser, if any address was saved before, it will auto-fill this address.

autocomplete="off" is not supported for "select" elements, i disabled the autocomplete for the whole form.
