### ISSUE TITLE
Signup failed because city_customer_id parameter was missing

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#463]
I tried it myself and it worked.

User-Agent was "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1"

![screen shot 2017-08-23 at 10 39 35](https://user-images.githubusercontent.com/17762105/29606718-644a6428-87ef-11e7-93b7-fdf41e32af71.png)

**Comment by abom** [comment]
Cannot reproduce.
