### ISSUE TITLE
Possibility to add extra logins

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#466]
Let the user add admins in the "Settings > User & Roles" page.

Under the hood this should create a `UserProfile` with the current service added to `owningServiceEmails`

**Comment by RubenMattan** [comment]
I would use service roles for this

**Comment by bart-at-mobicage** [comment]
@RubenMattan. Can you spec first how you would implement this so it can be reviewed by OCA?

We created dashboard.onzestadapp.be to hide rogerth.at from the merchants, because it caused confusion. Are they now going to have to create an account on rogerth.at? And then switch to the correct service? I hope you're not dragging them through this hassle...

**Comment by RubenMattan** [comment]
I will just allow adding admins via the service api

**Comment by RubenMattan** [comment]
and they always need an account on rogerthat to login on any dashboard...

**Comment by bart-at-mobicage** [comment]
Sure, that's what I said in the description of the issue. But I would create it under the hood. And not letting them create a rogerthat account themselves first. Probably you have the same idea, so that's why I asked for a spec.

**Comment by RubenMattan** [comment]
Creating a userprofile with what password?
No they need to create an account manually before they can be granted access

**Comment by bart-at-mobicage** [comment]
Not having them to create an account on rogerthat manually is a requirement from OCA. Forcing them to login to the crappy rogerthat user web ui and then switching to service-kjsdjksdfg-dfgsd-fgiljdf-sglksdf@rogerth.at is crappy user experience. 

So we need to find another solution. Eg. setting a tmp password and sending an email with the set-password link. We already have the mechanism of UserProfiles with owningServiceEmails. Re-use it.

**Comment by bart-at-mobicage** [comment]
Will implement once oca-backend is separated from rogerthat-backend.

**Comment by abom** [comment]
I think we should remove this issue from bug-hunt-5 milestone then.
