### ISSUE TITLE
Switching from merchant dashboard back to city dashboard

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#467]
Now when a city has logged in to a merchant dashboard, he has to login again.
Make sure that the user arrives in the city dashboard after he logs out from the merchant dashboard.

**Comment by abom** [comment]
I think this is the current behavior?

**Comment by bart-at-mobicage** [comment]
we tried, but the city user is logged out.

**Comment by RubenMattan** [comment]
Where u logged in via the shop bart?

**Comment by bart-at-mobicage** [comment]
Yes. Nevermind then...

**Comment by abom** [comment]
While testing something, logged in to a merchant dashboard from the city dashboard, then logged out again, but redirected to the login page instead of the city dashboard.

**Comment by bart-at-mobicage** [comment]
Where you logged in via the shop @abom?

**Comment by abom** [comment]
Logged in to the merchant dashboard via the city dashboard.

**Comment by bart-at-mobicage** [comment]
And how did you login to the city dashboard?

**Comment by abom** [comment]
From both the shop and the signin page "/customer/signin"

**Comment by abom** [comment]
I think the parent (city) session is set when you login to the merchant dashboard from the city dashboard, but the problem is when you logout, the OCA/flex logout handler is the one that's used and it didn't set back the session to the parent session.
