### ISSUE TITLE
UiT event starting at 00:00 is shown as 23:59

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#468]
Our mistake or mistake in UiT api?

https://www.uitinvlaanderen.be/agenda/e/zomerstage-hockey/209deb65-7943-47e4-8e5d-3a4d08177df6
![screen shot 2017-08-24 at 11 25 13](https://user-images.githubusercontent.com/17762105/29659714-63b2e9c4-88bf-11e7-8487-1a8579982dae.png)

![img_4814](https://user-images.githubusercontent.com/17762105/29659856-cbd7081e-88bf-11e7-8795-a8305e5cd5ab.PNG)

**Comment by abom** [comment]
It's from our side, and i think we need to refactor UiT jobs.

**Comment by abom** [comment]
@bart-at-mobicage Do we need the refactoring, or just try to fix the timing problem for now?
