### ISSUE TITLE
Main branding couldn't be loaded

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#472]
... for service-dbca6d48-66fc-4002-b9ee-d5adbc7aa16e@rogerth.at

Investigate what could've happened.

![screen shot 2017-08-24 at 12 24 50](https://user-images.githubusercontent.com/17762105/29662354-500ff9a4-88c7-11e7-94e3-f36aa13cffd1.png)

**Comment by bart-at-mobicage** [comment]
Related to this
![screen shot 2017-08-24 at 12 26 56](https://user-images.githubusercontent.com/17762105/29662414-8fea9642-88c7-11e7-9137-06ce84790896.png)

**Comment by abom** [comment]
I think a previous error when provisioning has occurred, that's possibly the case main_branding.blob is not set, we may call get_and_store_main_branding to create it again in e.g the dal method?

**Comment by bart-at-mobicage** [comment]
Closing because brandings are stored on cloudstorage
