### ISSUE TITLE
Search "Nearby Service"

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#474]
examples are Veurne/ Diksmuide/ all other apps... 90% of the services (merchants) do not appear when you try to find them in "nearby services" - they do appear Alphabetically.

This is not a recent bug. Please try to solve this because the new cities are complaining and we are releasing 11 cities in the next month.

ex this address we can find in google-maps but does not appear in the "nearby services" search.
https://www.google.be/maps/place/Albert+I+laan+17,+8630+Veurne/@51.0613583,2.6723064,17z/data=!3m1!4b1!4m5!3m4!1s0x47dcbe0943d04c43:0x792c89a9134757b8!8m2!3d51.0613549!4d2.6745004
When we delete the postal code in de shop the service appears in the nearby services but that doesn't work all the time.

We have to find a way that we can lead our customers them to a correct input for this feature.
Because this is the way users want to search and find results.
Thanks

**Comment by bart-at-mobicage** [comment]
I think we show a warning in the settings page when the address couldn't be geocoded, right @abom?

@abom, plz investigate why "Albert I laan 17, 8630 Veurne" can't be geocoded.

**Comment by OSATOM** [comment]
We don't show a warning in the setting page

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-08-28 10:15 GMT+02:00 Bart Pede <notifications@github.com>:

**Comment by bart-at-mobicage** [comment]
@OSATOM, the warning message is only shown after the settings are saved. Do you want us to show the warning below the address field when the settings page is loaded?

**Comment by OSATOM** [comment]
yes

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-08-31 10:34 GMT+02:00 Bart Pede <notifications@github.com>:

**Comment by abom** [comment]
I think after the fix, this can only happen after the service is created, as it's impossible that a new service is published before changing any settings, it would add an extra check that isn't really needed.
