### ISSUE TITLE
Clean up index.yaml

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#484]
There's a limit of max 200 indexes in `index.yaml`. See if we can get rid of some indexes by removing some `deleted` properties by creating XxxArchive models.

**Comment by RubenMattan** [comment]
We should deploy oca on another backend instead of patching this up

**Comment by bart-at-mobicage** [comment]
We're gonna do the split in the next milestone. We're gonna finish milestone `bug-hunt-3` first.
