### ISSUE TITLE
Multi-date event ordening

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#487]
![screen shot 2017-08-28 at 16 19 50](https://user-images.githubusercontent.com/17762105/29777693-2ee6e1c2-8c0d-11e7-9dcd-ce3fb367ee18.png)

Looks like there's no ordering on the event date for repeating events? Introduced by #480

![img_4820](https://user-images.githubusercontent.com/17762105/29777671-1765bdac-8c0d-11e7-9df2-ce0da3dbdaa8.PNG)

![img_4821](https://user-images.githubusercontent.com/17762105/29777673-1a0cdcac-8c0d-11e7-9bbe-efa6c6e4f26d.PNG)

**Comment by abom** [comment]
Event dates list, "Add to calendar"...etc in the event details page should contain all the dates or not?

**Comment by bart-at-mobicage** [comment]
I think it might be useful to show all event dates. But for "Add to calendar" I would only add the event which the user tapped on.

**Comment by bart-at-mobicage** [comment]
Diksmuide is complaining about this issue
