### ISSUE TITLE
group-chat

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#491]
It is still not possible to activate the group-chat.
it was possible in the past but for some reason not anymore.

This is very important for our associations and cities if you look @ all chat-apps this is key.
We should invest time an effort in a group-chat !!!

**Comment by bart-at-mobicage** [comment]
@OSATOM, do you mean "Discussion groups"?

**Comment by RubenMattan** [comment]
@OSATOM Can you reply on Bart his question
