### ISSUE TITLE
Appointment

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#497]
@ this time we have no usefull appointment system.

It would be great to generate a good appointment-system.
This could be a feature they have to pay for?
But for now nobody uses the feature because not good enough.

It is crucial for certain categories by ex nail/hair/doctors/....

**Comment by RubenMattan** [comment]
Duplicate of https://github.com/our-city-app/oca-backend/issues/497

**Comment by lucasvanhalst** [comment]
Issue can't be duplicate of itself

**Comment by bart-at-mobicage** [comment]
Duplicate of #410
