### ISSUE TITLE
NEW-USERS: TUTORIAL VIDEO'S

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#513]
When new users create their own app on www.onzestadapp.be the should receive 4 emails:

1/ When the city accept their request they should receive an email with their login and password
#bart they sent the subscription mail!

2/ DAY 1: immediately after login and password email they should receive the "Welcome email" with a tutorial video "how to broadcast news" 
**VIDEO: https://youtu.be/5NvAKVnbEqI**
**WELCOME EMAIL: http://communicatie.onzestadapp.be/t/ViewEmail/i/045376416E4228D6**

3/ DAY 2 - tutorial video "how to configure their loyalty" 
**VIDEO: https://youtu.be/WRwNCNtIQG4**
**LOYALTY EMAIL: http://communicatie.onzestadapp.be/t/ViewEmail/i/99FD2D1F8303DB22**

4/ DAY 4 - tutorial video "how create their own e-shop"  
**VIDEO: https://youtu.be/hHOkurV4IIE**
**E-SHOP EMAIL: http://communicatie.onzestadapp.be/t/ViewEmail/i/B831D037037D875F**

5/ DAY 6 - tutorial video "how to create their own reservation functionality" 
**VIDEO: https://youtu.be/7aFdU2wyTkM**
**RESERVATION VIDEO:  http://communicatie.onzestadapp.be/t/ViewEmail/i/3724C4F0F9AE8355**

SENT FROM "ONZE STAD APP"
Those tutorial video's & emails are ready !!!!
The other tutorial video's of the other functionalities are capture but are not ready for release because we do not have the resources. 

It seems that those tutorial video's are not automated and on this moment nobody has the time to do this.

SIMPEL QUESTION: WHO CAN DO THIS AND WHEN !!! IT IS ALREADY TO LATE.

**Comment by bart-at-mobicage** [comment]
@OSATOM, can you provide the youtube links?

**Comment by svekeman** [comment]
Keep going guys!

**Comment by bart-at-mobicage** [comment]
- [ ] We need to mention that we are going to send campaign emails. So after signup up (after email is verified) show the following text:
  - EN: Congratulations with your application. As soon as your city or town approved your request, you will receive an email with your login and password, so you can start. See you soon. Congratulations and welcome!

  - NL: Beste, proficiat met uw applicatie. Van zodra uw stad of gemeente uw aanvraag heeft goedgekeurd zal u een email ontvangen met uw login en paswoord, zo kan u van start. Nadien zullen wij u per mail informeren over alle mogelijkheden binnen uw eigen applicatie. Mogelijkheden zoals een gratis e-shop, hoe u nieuws en acties kan uitsturen, een gratis klantenkaartsysteem... Tot binnenkort. Veel succes en welkom!

- When the city/town approves, they receive mail with login/password.
  - If the customer's language is NL then
    - [ ] Schedule a defer to run after 2 minutes to send the "Welcome" smart email: `8dd5fe5f-02eb-40f9-b9fa-9a48d52952b4` (on the schedule_queue)
    - [ ] Schedule a defer to run after 2 days to send the "Loyalty" smart email: `f4e19feb-f394-47b4-880f-f7a5a0c163ac`
    - [ ] Schedule a defer to run after 4 days to send the "E-Shop" smart email: `e6b456af-a811-4540-903c-5135cd6e4802`
    - [ ] Schedule a defer to run after 6 days to send the "Reservation" smart email: `c87c3b2c-e1e8-4680-914e-6f81f2bd37f5`

How to send a smart email
- [ ] Add `SolutionServerSettings.createsend_api_key` (Ask me the api key to test with)
- Here is an example with `curl`
```
curl -u ${API_KEY}:. -H "Content-Type: application/json" \
-X POST -d '{
    "To": ["Bart Pede <bart.pede@mobicage.com>"],
    "AddRecipientsToList": true
}' \
https://api.createsend.com/api/v3.1/transactional/smartemail/${SMART_EMAIL_ID}/send
```
- Or with python (However, `pip install createsend` failed in my venv, so just doing the urlfetch ourselves might be faster)
```
# pip install createsend
from createsend import Transactional

# Authenticate with your API Key
auth = {'api_key': settings.createsend_api_key}

# The unique identifier for this smart email
smart_email_id = 'c87c3b2c-e1e8-4680-914e-6f81f2bd37f5'

# Create a new mailer and define your message
tx_mailer = Transactional(auth)

# Send the message and save the response
response = tx_mailer.smart_email_send(smart_email_id, 'Bart Pede <bart@mobicage.com>')
```

**Comment by abom** [comment]
For (1), password and login are sent only to new users (the email used in signup is not linked to any already registered user).
