### ISSUE TITLE
VAT couldnt be validated

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#523]
A customer tries to signup for the Veurne app. His VAT number cant be validated: BE 0406 211 947.

**Comment by abom** [comment]
Used the same VAT number and it worked normally on Chrome and Firefox) (desktop)
![sc](https://user-images.githubusercontent.com/511438/30244435-120e5606-95be-11e7-89b1-5e37bc41796b.png)

Is there any more information about the platform and the browser?

**Comment by abom** [comment]
Also works on Safari (iOS).

**Comment by abom** [comment]
Cannot reproduce

**Comment by abom** [comment]
Sometimes, when entering the VAT of another country, and after showing the error of
"The VAT number could not be verified. Please check if the VAT number is provided correctly and if the correct city is selected."
the next button is always disabled.

Also the message of "VAT number could not be verified" can appear twice or more, and maybe the user thought it's a not validated, despite the information has been populated.
