### ISSUE TITLE
expiration date City-Voucher

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#524]
We are selling the city-Voucher module because this is a functionality that is a paid feature in the City-App and creates revenue.

The problem is - we should have an expiration date on the "city-vouchers".
An expiration date they can adapt them self.
They give the rest-amount to the merchants association.
In that way we and the city get's believers in the City-App !!!

The city should receive each month automatically a list with the expired city-voucher.

Option:
The owner or customer should receive a message 1 month before the expiration date / one day before the expiration date and the day itself.

This is urgent because some off them are already sold.

Thanks

**Comment by bart-at-mobicage** [comment]
@OSATOM, you mentioned that "some vouchers are already sold". Do we need to set an expiration date on those ones?

**Comment by bart-at-mobicage** [comment]
@abom, vouchers already created before this feature should not expire.

**Comment by abom** [comment]
This should be done, we need the answer from @OSATOM about how the expired vouchers will be shown in city dashboard.

**Comment by OSATOM** [comment]
SHOW as EXPIRED with Expiration date - Name owner (email) & the amount

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-15 10:25 GMT+02:00 Abdelrahman Ghanem <notifications@github.com>:

**Comment by bart-at-mobicage** [comment]
@OSATOM, a separate list? Eg. a page with 2 tabs? "Vouchers" and "Expired"?

**Comment by OSATOM** [comment]
ok


<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-16 10:23 GMT+02:00 Bart Pede <notifications@github.com>:

**Comment by RubenMattan** [comment]
Please don't. You can only search for vouchers so having 2 lists bad...

**Comment by OSATOM** [comment]
Maybe we should discuss this face2face because i don't understand everyones
opinion. 11.30u 5min to solve the view on this topic? ok?

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-16 10:38 GMT+02:00 Ruben Mattan <notifications@github.com>:
