### ISSUE TITLE
Registration procedure - Create your own app

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#528]
To many customers get stuck in the registration procedure.
We get 80% phone calls or emails of people who are stuck in the registration.

OSA and technology should asap sit together and redesign the registration flow.
Many cities are getting started and we are losing customers very fast in this way.

What we know already:
1/ Customers do not know they gonna receive an email to confirm their emailaddress - they do not know they have to confirm within 24hours - so 80% forgets about this and gets stuck afterwords.

Some of those issues should be solved at least before Tuesday next week!!

**Comment by abom** [comment]
I think the instructions are clear, for example after submitting the application, this message is shown

> To continue the registration process, you need to verify your e-mail address. An e-mail with further instructions has been sent to tester@tester.com.

Also, the 24-hours validity is mentioned in the email address itself, we might show it with the previous message instead.

**Comment by bart-at-mobicage** [comment]
@stevendepaepe, you can put the specifications here

**Comment by bart-at-mobicage** [comment]
Text to be used after registration:

___
Your registration is almost completed. These are the next steps of your registration.

**Step 1**
To be sure the e-mail address is entered correctly and really exists, we just sent an e-mail with a "Verify" button. You might need to check your Spam of Junk folders.

**Step 2**
Once you click the "Verify" button in the e-mail, your city/town will be notified of your registration.

**Step 3**
When your city/town approves your registration, you will receive an e-mail with your login and password.

[OK, I understand](https://dashboard.onzestadapp.be/customers/signin)

___

"Ok, I understand" should be a button, linking to https://dashboard.onzestadapp.be/customers/signin

**Comment by bart-at-mobicage** [comment]
Dutch:

___

Uw registratie is bijna voltooid. Dit zijn de volgende stappen van uw registratie.

**Stap 1**
Om zeker te zijn dat het e-mailadres correct is ingevuld en wel degelijk van u is, hebben we zonet een e-mail verstuurd met een "Verifiëren" knop. Vergeet niet te kijken in uw Spam of Ongewenste E-mail map.

**Stap 2**
Wanneer u op de "Verifiëren" knop in de e-mail geklikt hebt, zal uw stad/gemeente op de hoogte gebracht worden van uw registratie.

**Stap 3**
Wanneer de stad/gemeente uw registratie aanvaardt, zal u een e-mail ontvangen met uw login en wachtwoord.

[OK, ik begrijp het](https://dashboard.onzestadapp.be/customers/signin)

___
