### ISSUE TITLE
Foto's E-shop

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#540]
On android the foto's from a merchant's E-shop do not appear when clicking on the product.
(sometimes they do, but most of the times not)
On IOS this is not the case (always with photo)
![image 2017-09-14 15 39 37](https://user-images.githubusercontent.com/26439611/30432780-eb012e96-9962-11e7-93c4-97badbc94f6c.jpg)
![image 2017-09-14 15 48 48](https://user-images.githubusercontent.com/26439611/30433243-35b5bd52-9964-11e7-882b-460ce3293ed8.jpg)

**Comment by bart-at-mobicage** [comment]
https://github.com/rogerthat-platform/rogerthat-android-client/issues/236
