### ISSUE TITLE
upload exel/foto's e-shop

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#542]
When a merchant imports an exel for the e-shop the existing foto's should stay

copied from https://github.com/rogerthat-platform/rogerthat-android-client/issues/237

**Comment by RubenMattan** [comment]
related to https://github.com/our-city-app/oca-backend/issues/533

**Comment by abom** [comment]
I think it would be a little hard to find out which menu items are provided as the excel file is a user input.
Maybe the export feature will solve this by exporting the item with an identifier, so it would be easy to get the item information form the imported excel file later.

Also don't know if we can read the images from excel files, does xlrd support this?

**Comment by RubenMattan** [comment]
I would only allow them to add an url in the excel file
