### ISSUE TITLE
There is a border around bree's splash screen image

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#545]
there seems to be a border + the image resolution is very low

![simulator screen shot 15 sep 2017 11 27 56](https://user-images.githubusercontent.com/17762105/30476027-00593526-9a09-11e7-922a-c429d3b43f4d.png)

**Comment by OSATOM** [comment]
?????? Not that I know

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-05 12:16 GMT+02:00 Ruben Mattan <notifications@github.com>:
