### ISSUE TITLE
Pharmacie order

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#554]
The photo taken by users of their prescription is so small in the pharmacy's inbox that it is unreadable. Given that enthusiastic pharmacies start using this and let us know, we need to solve this quickly.
A fair point is that there should also be a possibility for them to print the prescription or photo.
I will put that request in a feature issue.

ex. service-02daa55e-bac5-4623-b069-48dff0bb6617@rogerth.at
![schermafbeelding 2017-09-21 om 08 56 43](https://user-images.githubusercontent.com/23034120/30682705-deb517cc-9eaa-11e7-861b-96563ea217b4.png)
![schermafbeelding 2017-09-21 om 08 56 57](https://user-images.githubusercontent.com/23034120/30682706-deb6cfea-9eaa-11e7-8f82-f1c011b6181f.png)

**Comment by bart-at-mobicage** [comment]
https://github.com/rogerthat-platform/rogerthat-android-client/issues/248
