### ISSUE TITLE
App users & Permission

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#557]
At this time it seems to be impossible to connect a phone to a service/Dashboard.

We get a lot of questions of merchants that wants to receive their orders on the phone.
It seems that the functionality does not work:

1/ Dashboard - Settings - Inbox : their is no QR-code to scan and impossible to find a user with a mailadress
2/ Dashboard - Settings - Users & permissions : impossible to find a user with a mailaddress

![schermafbeelding 2017-09-21 om 11 27 53](https://user-images.githubusercontent.com/23034120/30689202-91543880-9ec0-11e7-8961-cfcb767a4817.png)

**Comment by RubenMattan** [comment]
@OSATOM can you send me details of this service/user (private message)

**Comment by OSATOM** [comment]
it is in the ticket


<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-09-21 12:13 GMT+02:00 Ruben Mattan <notifications@github.com>:

**Comment by RubenMattan** [comment]
Inbox QR-code was only generated when Ask Question was enabled, will be fixed on next deploy

**Comment by OSATOM** [comment]
Thanks

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-09-21 12:41 GMT+02:00 Ruben Mattan <notifications@github.com>:

**Comment by RubenMattan** [comment]
The search issue is probably a race condition, i have added a possible fix for that. However this change will only be reflected after:
- the user updates its profile
- the user adds a new friend
- the user removes a friend

**Comment by OSATOM** [comment]
Hi guys this is not really closed - we have to many new users with this
problem - i cannot give them this explanation, this is not their problem
but ours ???
Can we do this for them and will other users have also this issue in the
future?

 Thanks

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-09-21 13:02 GMT+02:00 Ruben Mattan <notifications@github.com>:

**Comment by bart-at-mobicage** [comment]
Ruben's fix seems to work.
We're re-indexing all users such that those who suffer from this issue now will be fixed.
