### ISSUE TITLE
Turn back to services when you are on a dashboard as a community service

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#563]
When a community service goes to a dashboard in services, it is impossible to go back to their own dashboard without logging out and then logging back in.
This problem exists not only in the shop

**Comment by abom** [comment]
"This problem exists not only in the shop"
If the login to the merchant dashboard is via the shop, it won't go back to the community service dashboard after logout.

I just tested it from the community service dashboard and it works normally. Can you send me the community service this behavior occurred with?

**Comment by RubenMattan** [comment]
@stevendepaepe does this answer your issue?
