### ISSUE TITLE
Agenda shows events from the day before

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#572]
In the agenda (UitVlaanderen) are still events from the past.
This is for example the case in Herk-de-Stad
![image 2017-10-03 12 04 39](https://user-images.githubusercontent.com/26439611/31119937-08f9a872-a833-11e7-843e-4b693a4a303e.jpg)

**Comment by RubenMattan** [comment]
This is done on purpose because the end date is optional i thought
