### ISSUE TITLE
VAT verification in customer signup

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#573]
Some problems we need to fix:
- [x] add some delay time (3 sec) to the VAT number field (can use `sln.configureDelayedInput`)
- [x] in the backend, if the VAT number doesn't start with `BE`, and contains 9 or 10 numbers, then add `BE` or `BE0` programmatically. So basically the rule is country code "BE" + 10 numbers for BE.
- [x] strip off dots and dashes because people try to lookup VAT numbers like 0818.106.512 or 0558-967-250
- [x] if the VAT is found, by adding `BE` or stripping dashes or dots, then change the text input field to the correct format ("BE" + 10 numbers). I suggest you add the VAT number to the response of the request.
- [x] don't show an error if the VAT is unknown, instead show this warning:
  - _Your VAT number is not known by "EU VAT". Therefor, we can not automatically prefill the name and address of your company. Please check if the VAT number is correct and enter the name and address manually._
  - _Uw BTW-nummer is niet bekend in "EU VAT". Daarom kunnen we de naam en het adres van uw bedrijf niet automatisch invullen. Gelieve te controleren of het BTW-nummer correct is. Indien ja dient u manueel naam en adres in te vullen._
- [ ] don't check the VAT number when the city approves the signup request.

**Comment by OSATOM** [comment]
don't check the VAT number when the city approves the signup request.
