### ISSUE TITLE
Time difference Uit kalender

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#574]
The link from the Output Database to the Calendar application has been successful. However, there is a structural time difference of 1 hour at all events. How can we solve this? It appears that it is not possible to manually change this.
![schermafbeelding 2017-10-04 om 11 41 20](https://user-images.githubusercontent.com/26439611/31170068-0b761cac-a8fb-11e7-8ea6-e81148859f60.png)

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/575
