### ISSUE TITLE
Merchants in services list community app

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#576]
In some service functions in community dashboards not all merchants are visible
for example Diksmuide (see screen shot)
![schermafbeelding 2017-10-04 om 15 28 00](https://user-images.githubusercontent.com/26439611/31178504-9b9deca6-a919-11e7-9df8-612e0b533b4d.png)

**Comment by RubenMattan** [comment]
Fixed by https://github.com/our-city-app/oca-backend/commit/33942e7f89cfde6972750cffd55484066531361c
