### ISSUE TITLE
Connection with UitVlaanderen

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#578]
Wen we fill in de codes to make the connection with UitVlaanderen for City's we get an error.
See screenshot

![image](https://user-images.githubusercontent.com/26439611/31215855-87700b72-a9b1-11e7-9b98-1cbd5c511ab3.png)

**Comment by RubenMattan** [comment]
Reason: https://github.com/our-city-app/oca-backend/pull/510/files

@abom Please always test when you change something even something this simple
@bart-at-mobicage I fixed the problem
