### ISSUE TITLE
Merchant with simple order type can not publish

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#580]
service-93e04745-44bf-46af-9f45-f72a5bb3c399@rogerth.at can not publish because his Menu is still the default menu. However, his order type is set to "simple" meaning the menu is not used and even not visible.

**Comment by bart-at-mobicage** [comment]
Seems like after a refresh everything was ok. Maybe this happens when switching from ADVANCED to SIMPLE order types.

**Comment by RubenMattan** [comment]
I can publish simple and advanced order with default menu so thats not the issue

**Comment by RubenMattan** [comment]
switching back and forth also gives no issue

**Comment by bart-at-mobicage** [comment]
Can you reproduce it with a newly created service? If not, then we'll close with cannot reproduce.

**Comment by RubenMattan** [comment]
That was a new service, so cannot reproduce
