### ISSUE TITLE
Afval kalender Bree. Dringend!!

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#584]
Mijn vrienden hebben de app gedownload om voornamelijk de meldingen te krijgen i.v.m. huisvuil.  Hun meldingen komen binnen op maandagavond, terwijl het vuil opgehaald wordt op maandagochtend.  Hoe kan zoiets? 

My friends have downloaded the app to get the notifications in particular. garbage. Their reports arrive on Monday night, while the dirt is collected on Monday morning. How could such a thing?

**Comment by bart-at-mobicage** [comment]
Happened in the Bree app

**Comment by RubenMattan** [comment]
Need some user info (Private message)

**Comment by RubenMattan** [comment]
Message was sent on the correct date/time
