### ISSUE TITLE
Inport menu

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#586]
ik krijg telkens de volgende foutmelding tijdens het importeren:
please_check_missing_product_details

in bijlage het bestand wat ik probeer te importeren.
Ik heb de headers aangepast naar dat wat de export genereert, maar ook dat helpt niet.
ik heb de categorieën alleen bij het eerst item gezet en bij alle items, geen verschil.

Wat doe ik fout?

Met vriendelijke groet,

Menno Scholten
![schermafbeelding 2017-10-09 om 14 53 57](https://user-images.githubusercontent.com/26439611/31339007-ba633d08-ad01-11e7-91cd-8c5333e4ae11.png)

**Comment by bart-at-mobicage** [comment]
This file can not be imported. Dont know why. The error should show the wrong row (not only the number, but the name, price and unit.

[prijslijst-Ine-19092017-v2.xls.zip](https://github.com/our-city-app/oca-backend/files/1382947/prijslijst-Ine-19092017-v2.xls.zip)

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/610
