### ISSUE TITLE
Double address @ When&Where button

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#591]
It seems that we have a bug in the link between the registration and the "When&Where"-button.

Every new customers has a duplicated address in the app after registration.
Check Printscreen!

Due to this issue the services cannot be found in the "nearby-search" - so very important!

![photo_2017-10-12_09-52-41](https://user-images.githubusercontent.com/23034120/31485150-1afa51fa-af33-11e7-8561-233b84abee4a.jpg)

**Comment by bart-at-mobicage** [comment]
> Due to this issue the services cannot be found in the "nearby-search" - so very important!

That's because this service is still marked as INVISIBLE in the settings

**Comment by bart-at-mobicage** [comment]
> Every new customers has a duplicated address in the app after registration.

I checked a few new customers and none have a duplicated address. @OSATOM, can you show me the other customers you found with a duplicated address?

**Comment by bart-at-mobicage** [comment]
Fixed by #592

**Comment by OSATOM** [comment]
when & where needs to be regenerated

**Comment by bart-at-mobicage** [comment]
Will be fixed when service is published. Can not publish at the moment because the logo is still the default logo.

**Comment by OSATOM** [comment]
?? Which logo/City I need to fix?

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-17 14:59 GMT+02:00 Bart Pede <notifications@github.com>:

**Comment by bart-at-mobicage** [comment]
SENIORENLOKET

**Comment by OSATOM** [comment]
Logo aangepast!

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-18 9:31 GMT+02:00 Bart Pede <notifications@github.com>:

**Comment by OSATOM** [comment]
Issue #602 all the services that have been correct registrated but autoconnected and visible (issue #602) have all double addresses as well.
![double adress in when en where](https://user-images.githubusercontent.com/23034120/31942154-b3de81d0-b8c4-11e7-9c8f-a932c1b0c87d.jpg)
![photo_2017-10-24_14-06-33](https://user-images.githubusercontent.com/23034120/31942162-baa02e2e-b8c4-11e7-83b2-eee4585caa7c.jpg)

**Comment by RubenMattan** [comment]
Checked the following services, however only 1 had an incorrect address and it wasn't the one from the screenshot. Most services can't be published because they aren't designed yet

omgeving service-26facc1c-a76d-4692-83fe-561d6810817e@rogerth.at

erfgoed: service-e3a7e2ea-0e22-4918-adf1-eadc47ba130d@rogerth.at

Kinderdagverblijf 't: service-0e90590e-c680-4973-b2d5-c6d6efbb53de@rogerth.at

Kinderdagverblijf: service-bd62e847-b2a5-4aa8-886b-8e58f4d19789@rogerth.at

Leefmilieu: service-ae78a27b-dba9-4dc0-9f85-031208f9747c@rogerth.at

Personeel: service-2a3e1845-83bb-4461-a5e0-dd302c0eecfd@rogerth.at

Seniorenloket: service-5bdcdbe7-2084-41d2-a3c8-3b394dad4ae1@rogerth.at

Sociaal Huis: service-fc2a1ca3-5014-494d-bd96-585ee2c4c9bc@rogerth.at

Vakantieopvang Holder de Bolder: service-cfab487a-f24f-4f10-94d1-aec6906af8df@rogerth.at

Welzijnscampus gerkenberg: service-acc302f3-0a31-45df-9aa0-eed9d920fea4@rogerth.at

**Comment by OSATOM** [comment]
Yes, but they are visible and everyone of the 998 users has them in their
"Community service"-tab and the city is complaining about this from week 1
of the launch 4 weeks ago?
They all have double addresses
[image: Inline afbeelding 1][image: Inline afbeelding 2]

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-24 15:02 GMT+02:00 Ruben Mattan <notifications@github.com>:
