### ISSUE TITLE
Again : the addres doesn't create the location 

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#592]
Many but many services have correct addresses but do not create a location and so do not appear in the "nearby-search"

we took 1 screenshot (Geetbets "nearby-search and A-Z) to help to show, detect and hopefully solve the problem.
![photo_2017-10-12_09-57-38](https://user-images.githubusercontent.com/23034120/31485347-cb54963c-af33-11e7-9dc1-2370300a8770.jpg)
![photo_2017-10-12_09-58-29](https://user-images.githubusercontent.com/23034120/31485388-ee725cd0-af33-11e7-94b4-5264d8605bb5.jpg)
![photo_2017-10-12_09-58-25](https://user-images.githubusercontent.com/23034120/31485419-0576c5d8-af34-11e7-9178-e065af521cd6.jpg)

**Comment by bart-at-mobicage** [comment]
re-published the service. the location was created.
will go write a script that goes over all current services and try to add missing location

**Comment by abom** [comment]
The script in this pull request doesn't help?
https://github.com/our-city-app/oca-backend/pull/500

**Comment by bart-at-mobicage** [comment]
thx @abom, I forgot that script existed. now I don't have to write it myself :-)

**Comment by bart-at-mobicage** [comment]
Fixed
