### ISSUE TITLE
Problem with Calendar merchant

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#593]
Dit zijn de foto's van de App. Ze staan dus wel in de agenda van ons tabblad maar wanneer je op de activiteit klikt komt er niets meer te staan. Dit was vorige week wel nog het geval. Ik kan ook niet meer klikken op lees meer, ik had hier de website van kwandoo achter gestoken.

These are the pictures of the app. So they are in the tab of our tab, but when you click on the activity, there is nothing left to stand. This was the case last week. I also can not click on read more, I've left the Kwandoo website here.
![22447115_10209960372793556_668419515_n](https://user-images.githubusercontent.com/26439611/31496869-5c6d2f48-af5d-11e7-9cd2-cbd3f1f0a60f.png)
![22500906_10209960544037837_1976339350_n](https://user-images.githubusercontent.com/26439611/31496870-5dc89fb2-af5d-11e7-9f01-b532eca49e25.png)

**Comment by bart-at-mobicage** [comment]
Client error:

```
description: Bug!
ScreenBrandingException:
- Exception logged by screenBranding of service-ae9e2a1a-22ef-43a1-9096-debb1dd4816a@rogerth.at
- Service menu item name: Agenda
- Service menu item coords: [0, 2, 0]
Uncaught javascript exception in HTML-app:
isTrusted: true
message: Uncaught TypeError: Cannot read property 'id' of undefined
filename: file:///data/user/0/com.mobicage.rogerthat.be.bree/cache/branding/C32F370AEFDB6E1D55AE885B383774CE3F4A72D59A4968CAF66D4D4AC9276DF1/app.js
lineno: 330
colno: 36
error: TypeError: Cannot read property 'id' of undefined
NONE: 0
CAPTURING_PHASE: 1
AT_TARGET: 2
BUBBLING_PHASE: 3
type: error
target: [object Window]
currentTarget: [object Window]
eventPhase: 2
bubbles: false
cancelable: true
defaultPrevented: false
composed: false
timeStamp: 1953.7050000000002
srcElement: [object Window]
returnValue: true
cancelBubble: false
path: [object Window]
composedPath: function composedPath() { [native code] }
stopPropagation: function stopPropagation() { [native code] }
stopImmediatePropagation: function stopImmediatePropagation() { [native code] }
preventDefault: function preventDefault() { [native code] }
initEvent: function initEvent() { [native code] }


errorMessage: java.lang.Exception
	at com.mobicage.rogerthat.util.logging.L.logToServer(L.java:151)
	at com.mobicage.rogerthat.util.logging.L.bug(L.java:114)
	at com.mobicage.rogerthat.util.ActionScreenUtils.logError(ActionScreenUtils.java:290)
	at com.mobicage.rogerthat.plugins.friends.ActionScreenActivity$JSInterface.logError(ActionScreenActivity.java:334)
	at com.mobicage.rogerthat.plugins.friends.ActionScreenActivity$JSInterface.invoke(ActionScreenActivity.java:221)
	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)


mobicageVersion: 1.3473

occurenceCount: 1

platform: 1

platformVersion: OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/08242149:user/release-keys (-) 25 (-) ONEPLUS A3003
```

**Comment by RubenMattan** [comment]
For some reason this service does not have any calenders...

**Comment by RubenMattan** [comment]
Manually created calendar and moved all existing events to that calendar

**Comment by RubenMattan** [comment]
Tested and it works again for this service

**Comment by stevendepaepe** [comment]
I checked, i think this is not ok yet
![IMAGE 2017-11-10 14:21:31.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46c1b9bb04a7c3fbdfb8e80ef50cbdc5790676277356f27123d4a164fd52690e050a1de853524d41f5ff8d2ca1b23477de0803bc836d5f26c63f45a8b8864aad1da862da11d1e9e1d30695aa2f2ff58a88453f1b04188afd5d35a99a4ccf59e406.jpg)
![IMAGE 2017-11-10 14:21:37.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46c1b9bb04a7c3fbdfb8e80ef50cbdc5790676277356f27123d2a164fd52690e050a1de853524d41f5ff8d2ca1b23477de0803bc836d5f26c63f45a8b8864aad1da862da11d1e9e1d30695aa2f2ff58a88453f1b04188afd5d35a99049cd5fe406.jpg)

**Comment by stevendepaepe** [comment]
maybe this is related to issue 568

**Comment by stevendepaepe** [comment]
Jeugd Bree
Kan ik momenteel niet controleren want er staat niks in de agenda nu
