### ISSUE TITLE
Problem to place message on facebook

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#596]
Ik wilde mijn nieuwsbericht ook delen via Facebook, Er blijft gewoon een blauw balkje draaien, ik heb de pagina moeten vernieuwen om terug te gaan. Dit werkt dus ook niet voor ons. Jeugd Bree

I also wanted to share my news article via Facebook, just keep a blue bar, I need to refresh the page to go back. This does not work for us either. Youth Bree

**Comment by bart-at-mobicage** [comment]
![screen shot 2017-10-13 at 11](https://user-images.githubusercontent.com/17762105/31538997-85d1671e-b007-11e7-9308-12556ae53fc6.png)
