### ISSUE TITLE
Registration Problem in Dashboard City

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#599]
Ik was net in het dashboard aan het kijken en zag dat ik al enkele registratie-aanvragen heb gehad. Ik heb die goedgekeurd, al lijkt het ook dat die na goedkeuring niet verdwijnen uit de lijst want ik heb ook al gehad dat er al een aanvraag is geweest op die naam. Kan het inderdaad zijn dat ik twee keer op dezelfde aanvraag heb geklikt en dat die niet uit overzicht verdwijnt nadat ik de eerste keer goedgekeurd heb.

I was just watching the dasboard and saw that I already had some registration requests. I approved that, although it seems that after approval it did not disappear from the list because I have already had an application for that name. Could it actually be that I clicked twice on the same application and that does not disappear from the list after I first approved.

**Comment by OSATOM** [comment]
Messages were gone when refreshing the page

**Comment by RubenMattan** [comment]
Channel/connection issue
