### ISSUE TITLE
auto connected community services

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#602]
- [x] auto connected service isn't removed when disabled in city dsahboard
- [x] community shouldn't be set as auto connected on creation
- [x] community should be set as auto connected when set to VISIBLE
- [x] community should be removed as auto connected when set to INVISIBLE

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/318
https://github.com/our-city-app/oca-backend/pull/626
