### ISSUE TITLE
broadcast flow has problems with uploading photo

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#603]
Sometimes, there are problems with the photo ratio

Also, suggest to take the photo in landscape (mention it in the text of the message).

**Comment by abom** [comment]
Can we do anything other than specifying the **ratio** to the PhotoUploadWidget?

**Comment by abom** [comment]
Another question, the following message is shown, or what kind of problems happen when uploading the photo?

> Could not get the photo of the news item!

**Comment by abom** [comment]
When uploading the image, the cropper is shown after selecting or taking a picture, but the ratio at the end is not 16:6

`INFO     2017-11-01 11:12:49,602 news.py:416] Image has an invalid ratio. (expected 16:6, got 72:26)`

**Comment by stevendepaepe** [comment]
the suggention to take the foto  in landscape is not there yet
