### ISSUE TITLE
noodnummers.be@rogerth.at

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#604]
Please make it search visible for every Belgium City-App (not autoconnected)

**Comment by abom** [comment]
What i'm thinking of is just adding this service (or a predefined list) to the search results of find service API, regardless of the search parameters, is that a good approach?

**Comment by bart-at-mobicage** [comment]
I think it's enough to add every (new) city app to the list of supported apps of the service identity of noodnummers (`ServiceIdentity.appIds`). We cannot hardcode this in the code, so we'll have to create a configuration in the server settings for this.

**Comment by abom** [comment]
@bart-at-mobicage 
I thought of using service callbacks when a new app created (like a hook, but we are going to separate rogerthat and oca), but couldn't figure out a proper way to do it.

**Comment by RubenMattan** [comment]
I am not a fan of using server settings for this, we should do this manually or control center should add the add id on creating of new app

**Comment by abom** [comment]
@RubenMattan @bart-at-mobicage Suggested we register a hook on app creation for example and do this on OCA instead, or control center use the API key of noodnummers to add the newly created app to it, or doing it using server settings.

**Comment by bart-at-mobicage** [comment]
@stevendepaepe, this can be configured in app center. You can also configure it when creating a new app.

**Comment by abom** [comment]
This PR need to be merged https://github.com/rogerthat-platform/plugin-rogerthat-control-center/pull/223
