### ISSUE TITLE
Not possible to make movies in chat to friends

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#608]
In IOS The app closes when trying to make a movie
In Android i get a white screen
![image 2017-10-16 14 55 27](https://user-images.githubusercontent.com/26439611/31612996-0cf5ccfe-b282-11e7-984b-75acbabf1d64.jpg)

**Comment by bart-at-mobicage** [comment]
https://github.com/rogerthat-platform/rogerthat-android-client/issues/265
https://github.com/rogerthat-platform/rogerthat-ios-client/issues/164

**Comment by RubenMattan** [comment]
Will be fixed when we deploy new versions of the apps
