### ISSUE TITLE
Action Button - Agenda - in Newsmessage

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#617]
- [x] it is only in English on iOS - should be translated 
- [x] text should be updated to:
> EN: To be able to use this action button you need to connect to xxx. Do you want to connect to xxx?

> NL: Om deze actieknop te kunnen gebruiken moet je xxx volgen. Wil je xxx nu volgen?

![image](https://user-images.githubusercontent.com/23034120/31768391-80569c60-b4cf-11e7-8a0b-73cee2157e13.png)

**Comment by stevendepaepe** [comment]
Nu volg je automatisch als je op de actie knop drukt, was dit zo bedoeld?

**Comment by bart-at-mobicage** [comment]
@stevendepaepe, this is not changed. Only the translation was added. Can you double check if you weren't connected before clicking the action button?

**Comment by stevendepaepe** [comment]
i disconnected and when i push the action button i connect automatically

**Comment by bart-at-mobicage** [comment]
Are you testing on Android or iOS? Because this issue was about the missing translation on iPhone...

**Comment by stevendepaepe** [comment]
android

**Comment by stevendepaepe** [comment]
Als ik in android op agenda druk kom ik op de agenda en ben ik automatisch volger zonder bericht.

**Comment by RubenMattan** [comment]
The popup to connect should not be shown...

https://github.com/rogerthat-platform/rogerthat-android-client/issues/75

**Comment by bart-at-mobicage** [comment]
That issue was for something else. It was to skip the confirmation when clicking the `Follow` button.

**Comment by RubenMattan** [comment]
Check the commits...

**Comment by RubenMattan** [comment]
change on iOS
https://github.com/rogerthat-platform/rogerthat-ios-client/pull/180

**Comment by bart-at-mobicage** [comment]
Alright, so @stevendepaepe, the popup has been removed on iOS.

**Comment by stevendepaepe** [comment]
The popup in English is still there in IOS

**Comment by bart-at-mobicage** [comment]
Which app and which version?

**Comment by stevendepaepe** [comment]
Sylvie moet testen met laatste versie van de app!

**Comment by Sylviecraeye** [comment]
Zowel bij IOS als bij Android, krijg je geen vraag meer. Onmiddellijk door naar de agenda.
Maar ook die staat leeg. Er mist dus "Er zijn geen geplande evenementen"

![IMAGE 2017-12-07 10:32:13.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f2f0fa0f0ef30014334eab/125516c66e82c728ace21e0d46c1b9bb04a7c3fbdfb8e80ef50fbdc47e0676237357f17121d6a164fd52690e050a1de853524d41f5ff8d2ca1b23477de0803bc836d5f26c63f45a8b8864aad1da862da11d1e9e1d30695aa2f2ff58a86453f1b041a8ffc5434a39d42ca5be406.jpg)
