### ISSUE TITLE
Registration - Rephrase and changes

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#622]
90% of the merchant do not know what is ment by "Ondernemer" we would like to change that to "contactpersoon"

1/ Please add extra fields in query "Onderneming/Vereniging" 
 - email (copy this email to "contactpersoon" query)
 - website
 - facebook
 - telefoonnummer (copy this email to "contactpersoon" query)
 - naam = change this into "naam handelszaak/vereniging"

2/ Please delete following fields in query "Contactpersoon"
  - website
 - facebook pagina

![image](https://user-images.githubusercontent.com/23034120/31877924-98a8b378-b7d8-11e7-8a40-2b835a7b1ebd.png)
![image](https://user-images.githubusercontent.com/23034120/31877929-9dee01a8-b7d8-11e7-87a6-b60afc679c69.png)

**Comment by stevendepaepe** [comment]
Nog wat problemen bij registratie:
Bij de aanmaak van een dienst neemt de app de naam en het adres van de ondernemer over en niet van de onderneming!
Ook worden na goedkeuring nog 2 mails gestuurd waarvan de 2e weer met zo een lange link is
Deze 2 mails zouden in 1 mail moeten komen een de lay out van de laatste mail kan beter (zoals de mail met de verifiëren knop)

Some problems with registration:
When creating a service, the app takes over the name and address of the entrepreneur and not the company!
Also, 2 more emails will be sent after approval, the 2nd of which is such a long link
These 2 mails should be sent in 1 mail. The layout of the last mail may be better (such as the mail with the Verify button)
![image 2017-10-24 11 30 25](https://user-images.githubusercontent.com/26439611/31935282-bb9f2700-b8ae-11e7-9421-cea0f5f06f8a.jpg)
![image 2017-10-24 11 30 30](https://user-images.githubusercontent.com/26439611/31935288-be6907ee-b8ae-11e7-8d25-e8b87b071b21.jpg)
![schermafbeelding 2017-10-24 om 10 09 44](https://user-images.githubusercontent.com/26439611/31935315-cb4a93a6-b8ae-11e7-871f-1d53a9f71bae.png)
![image 2017-10-24 11 31 02](https://user-images.githubusercontent.com/26439611/31935329-d198a022-b8ae-11e7-86fe-45092dbf8211.jpg)
![image 2017-10-24 11 31 06](https://user-images.githubusercontent.com/26439611/31935333-d45b8e78-b8ae-11e7-84e5-d349aedf7cff.jpg)
![schermafbeelding 2017-10-24 om 10 33 40](https://user-images.githubusercontent.com/26439611/31935335-d6542b22-b8ae-11e7-91d7-68b9ac902e3a.png)

**Comment by abom** [comment]
Don't know if this is related, the URL parameters seem to be encoded twice, e.g. **%3D** became **%253D**.

```

Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/rogerthat/pages/login.py", line 108, in parse_and_validate_data
    data, user = self.parse_data(email, data)
  File "/base/data/home/apps/e~rogerthat-server/55.404931684938331203/rogerthat/pages/login.py", line 97, in parse_data
    data = base64.decodestring(data)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/base64.py", line 328, in decodestring
    return binascii.a2b_base64(s)
Error: Incorrect padding
```

**Comment by bart-at-mobicage** [comment]
I created #629. It contains improvements for the set-password URL.

**Comment by abom** [comment]
Please when you provide any non-English terms, provide the translation as well.
You didn't specify where to show this new information, we internally have **Customer**, **Contact** and the **service** itself.

**Comment by bart-at-mobicage** [comment]
To Summarise...

In the **Enterprise/Association** step.
- [ ] Rename Enterprise to Enterprise/Association (NL: Onderneming/Vereniging)
- [ ] Add email, phone number, website and facebook (NL: E-mail, Telefoonnummer, Website, Facebook pagina)

In the **Contact** step.
- [ ] Rename Entrepreneur to Contact (NL: Contactpersoon)
- [ ] Delete website and facebook
- [ ] Copy email and phone number from step 1

When creating the customer
- [ ] Use name, email, website, facebook, address from the enterprise/association step

When creating the contact
- [ ] Use name, email, phone from the contact step

When creating the service
- [ ] Use name, address, email, phone from the enterprise/association step

**Comment by abom** [comment]
Still some fields like the address of the Enterprise/Association step and the zip code of the contact step for example.

**Comment by stevendepaepe** [comment]
we just have to skip the first email after verification and put this content together with login en password in one mail
![Schermafbeelding 2017-11-10 om 14.37.41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46db979226908ea889ebba46a859f99a2e0675237853ee7a21c8b278ff4d76415e5b50af46465b45eee59b6be4e96625d91819e7c3685672c23a16a8b0854beb09eb728b4fd7b6bede48c0ec6837fb99cd1e604a5a45d0b50877b29359c95ffc4ae44c55a7113762e67f33794f8653.png)
![Schermafbeelding 2017-11-10 om 14.37.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46db979226908ea889ebba46a859f99a2e0675237853ee7a21c8b278ff4d76415e5b50af46465a46eee59b6be4e96625d91819e7c3685672c23a16a8b0854beb09eb728b4fd7b6bede48c0ec6837fb99cd1e604a5a45d0b50877b29359c95ffc4ae44c55a7113762e4753f7a468653.png)

**Comment by abom** [comment]
@bart-at-mobicage If the user is an existing user, login information email won't be sent, what to do in this case?

**Comment by bart-at-mobicage** [comment]
- [ ] Let's update the new mail template in that case, and leave out the password.

EN

> Dear %(name)s,
> 
> Your OUR CITY APP service has been successfully created.
> 
> You may login on %(login_url)s with login %(login)s.
> 
> Kind regards,
> The OUR CITY APP team

The changed line in NL: 

> U kan inloggen op %(login_url)s met login %(login)s.

- [ ] Also, update the email sender to `info@onzestadapp.be` in NL and  `info@ourcityapps.com` in all other languages (see `the_our_city_app_coach_email_address` in the solutions code as example)

**Comment by abom** [comment]
@bart-at-mobicage For the second point, i don't know how the user will know he must reset his password to login without explicitly guide him to do so.

**Comment by bart-at-mobicage** [comment]
In case they already have an account, then I think they will remember their credentials. If they don't, then they'll see the "forgot password" link and I hope they'll use it.
