### ISSUE TITLE
PROBLEMS WITH AUTOCONNECTED SERVICES - TELEGRAM GEERT/RUBEN/ 20/10/2017

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#623]
**dus: onderstaande services zijn disabled by the city - staan 2 keer in de app en staan 2 keer in the shop. Wat moet er gebeuren : deze services moeten uit de app - users ontkoppelen en deze services moeten ook uit de shop want de klant moet nu telkens kiezen tussen de juiste en de "disabled" service. APP STADEN**

service-0adae987-c1d3-4e93-bde1-e4a8e1aa931d@rogerth.at = Bib Staden

service-f22ab5c4-5547-432b-be7c-84a4c887723c@rogerth.at = Communicatie & beleidsondersteuning Staden

service-34f36083-362e-4409-8e11-8a24d973b3d6@rogerth.at = Financiën Staden

service-2a25acdb-7d07-4721-b663-17f2db000975@rogerth.at = Financiën Staden (idd het zijn er 2 van financiën)

service-edcab882-1899-4332-a10d-7787adc65946@rogerth.at = Gemeenteschool Staden

service-995e01e0-8394-4681-9aed-8430b1b3bba7@rogerth.at = Personeel & HRM Staden

service-db1f1453-e1e8-4db7-b15f-391f7361ed4f@rogerth.at = Politie – lokaal commissariaat Staden

service-d61e6572-5486-47db-977e-04d3a8871355@rogerth.at = Vrije Tijd Staden

service-0538faca-f068-40cd-87a5-9e010c387ed7@rogerth.at = Wonen & Omgeving Staden

**DUS: deze services zijn correct aangemakt, maar omdat het AUTOCONNECTED services zijn worden ze toch zichtbaar zonder te publiceren. MAW de autoconnect overruled onze eiegen regels in het dashboard van een dienst. WAT MOET ER GEBEUREN: autonnected services moeten zoals alle andere services NIET ZICHTBAAR zijn als ze niet volgens de regels zijn opgemaakt. BREE-APP**

omgeving service-26facc1c-a76d-4692-83fe-561d6810817e@rogerth.at

erfgoed: service-e3a7e2ea-0e22-4918-adf1-eadc47ba130d@rogerth.at

Kinderdagverblijf 't: service-0e90590e-c680-4973-b2d5-c6d6efbb53de@rogerth.at

Kinderdagverblijf: service-bd62e847-b2a5-4aa8-886b-8e58f4d19789@rogerth.at

Leefmilieu: service-ae78a27b-dba9-4dc0-9f85-031208f9747c@rogerth.at

Personeel: service-2a3e1845-83bb-4461-a5e0-dd302c0eecfd@rogerth.at

Seniorenloket: service-5bdcdbe7-2084-41d2-a3c8-3b394dad4ae1@rogerth.at

Sociaal Huis: service-fc2a1ca3-5014-494d-bd96-585ee2c4c9bc@rogerth.at

Vakantieopvang Holder de Bolder: service-cfab487a-f24f-4f10-94d1-aec6906af8df@rogerth.at

Welzijnscampus gerkenberg: service-acc302f3-0a31-45df-9aa0-eed9d920fea4@rogerth.at

![image](https://user-images.githubusercontent.com/23034120/31880441-ca2f7a46-b7e0-11e7-8e91-da0d4f644ca4.png)

![image](https://user-images.githubusercontent.com/23034120/31880467-e21fe870-b7e0-11e7-94d1-509faddc5124.png)

**DUS: onderstaande services zijn disabled by the city - deze staan geen 2 keer in de shop. Wat moet er gebeuren : deze services moeten uit de app - users ontkoppelen en deze services moeten ook uit de shop . BREE APP**

Autonoom Gemeentebedrijf Bree = service-45b7bdba-ff96-4939-b69d-2939d39cd0b1@rogerth.at

service-33779dd0-162d-4a17-ae7d-320a1cd1bac2@rogerth.at = College Burgemeester en Schepenen  Bree

service-24d2c251-19e0-4cb6-a362-75cb420f80f6@rogerth.at = Parkeren Bree

**Comment by RubenMattan** [comment]
Cleaned:
- [x] service-0adae987-c1d3-4e93-bde1-e4a8e1aa931d@rogerth.at

**Comment by RubenMattan** [comment]
The following services are still visible, however they do not have any branding/items

service-edcab882-1899-4332-a10d-7787adc65946@rogerth.at = gemeenteschool staden
service-db1f1453-e1e8-4db7-b15f-391f7361ed4f@rogerth.at = Politie – lokaal commissariaat Staden

service-d61e6572-5486-47db-977e-04d3a8871355@rogerth.at = Vrije Tijd Staden

service-0538faca-f068-40cd-87a5-9e010c387ed7@rogerth.at = Wonen & Omgeving Staden

**Comment by RubenMattan** [comment]
Problem found the cleanup of a solution does not work for only 1 location

**Comment by RubenMattan** [comment]
Cleanup done successful this time!

**Comment by OSATOM** [comment]
Do I put the other issue on connected services in an other issue? 

DUS: deze services zijn correct aangemaakt, maar omdat het AUTO-CONNECTED services zijn worden ze toch zichtbaar zonder te publiceren. MAW de auto-connect overruled onze eigen regels in het dashboard van een dienst. WAT MOET ER GEBEUREN: auto-connected services moeten zoals alle andere services NIET ZICHTBAAR zijn als ze niet volgens de regels zijn opgemaakt. BREE-APP

**Comment by RubenMattan** [comment]
this is the other issue

https://github.com/our-city-app/oca-backend/issues/602
