### ISSUE TITLE
Geetbets/Diksmuide - duplicate search results in A-Z

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#624]
@Geetbets - autoconnected 4 services - search nearby 3 services - search A-Z 4 Services double so 8 services shown 

![geetbets nearby](https://user-images.githubusercontent.com/23034120/31935544-69108712-b8af-11e7-9070-357a01293340.jpg)
![geetbets a-z](https://user-images.githubusercontent.com/23034120/31935545-692e5cb0-b8af-11e7-8d79-63e89dbb3432.jpg)
![geetbets autoconnected stadsdiensten](https://user-images.githubusercontent.com/23034120/31935546-694a7de6-b8af-11e7-9a5c-7e31ffcbc010.jpg)

**Comment by bart-at-mobicage** [comment]
Not really critical. Sylvie knows how to workaround it, she already did it for Staden and Bree.

The issue is also already fixed. However, all iOS apps still need to be built. Will happen this week when all open iOS issues are fixed.
