### ISSUE TITLE
E-SHOP ISSUES & FEATURES BY MERCHANTS WHO IS USING THIS TO INCREASE HIS BUSINESS

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#634]
26 Oct 2017 11:30:19
Beste,

Graag had ik volgende punten snel aangepast gezien voor onze werking sneller te doen verlopen. 

Bij onze laatste 3 bestellingen kregen we geen pushmelding van de inkomende bestellingen. Kunnen jullie dit nazien aub. 

* Aanpassing van standaard bericht ‘uw bestelling is klaar om opgehaald te worden” graag veranderen in uw bestelling is klaar in 5 min om opgehaald te worden. 
of de functie in je dashboard om dit standaard bericht aan te passen. 
Het is onmogelijk om dit bericht voor iedere klant aan te passen per bestelling. 

* Een knop in je bestelling Dashboard waarbij je manueel of zelf moet doorgeven dat je de bestelling hebt ontvangen en dat de klant dan een bericht krijgt van bevestiging. Nu gebeurt dit automatisch maar door de problemen met de pushmelding die niet door kwamen stonden de klanten hier om hun bestelling op te halen die nog niet eens gezien was. 

* Het standaard geluid van de inkomende bestellingen kunnen aanpassen want deze nu is veel te stil zelfs op maximum volume is dit bijna niet hoorbaar in volle service in de zaak. 

Bedankt om hier even bij stil te staan,

Met vriendelijke groeten,

Deklerck miguel 
Frituur Colyny

Dear,

I would have liked to change the following points quickly, given that our operation could be done faster.

For our last 3 orders we did not receive a push notification of the incoming orders. Can you see this please?

* Customization of default message "Your order is ready to be picked up" Please change your order is finished in 5 min to be picked up.
or the function in your dashboard to customize this default message.
It is impossible to customize this message for each customer per order.

* A button in your order Dashboard, which means that you must either manually or by yourself have received the order and that the customer will receive a confirmation message. Now this happens automatically but due to the problems with the push notification that did not occur, the customers were here to pick up their order that had not been seen yet.

* Customize the default sound of incoming orders as it is now not loud enough even at maximum volume, this is almost impossible to here in full service in the case.

Thank you for your response,

With best regards,

Deklerck miguel
Frituur Colyny

**Comment by bart-at-mobicage** [comment]
- [ ] Make the "Your order is ready to be picked up" message customisable
- [ ] Add the option to require a confirmation
  - in the order settings, add this option
  - in the message flow, say the following:
    - You order has been sent to xxx. You will receive a message confirming your order.
    - Uw bestelling is doorgestuurd naar xxx. U zal nog een bericht ontvangen ter bevestiging van uw bestelling.
  - in the order inbox, add the possibility to mark an order as CONFIRMED
- [x] Won't fix the problem with the sound. The merchant should use boxes.

**Comment by abom** [comment]
> Add the option to require a confirmation

@bart-at-mobicage Cannot get exactly what's meant by this new option.
Currently, the metchant can send a confirmation message manually if he wants via the **Reply** button in **Orders** tab (_Dashboard_) , also in the advanced order, the confirmation is sent automatically.

The new option:

- Should be added as a check box to the order settings, e.g. `Manual Confirmation`?
- Disable the automatic confirmation of advanced order if set?
- Just a add a new button to send `Confirmed` message as a reply in the inbox and set the status of the order to **Received**?
- Add this message to both the simple and advanced flow at the end? `You order has been sent to xxx. You will receive a message confirming your order.`

**Comment by bart-at-mobicage** [comment]
Hi @abom, your interpretation is correct. 

Let's call the label "Confirming incoming orders" with the options "Automatic/Manual"
In Dutch: Bevestiging van binnenkomende bestellingen - Automatisch/Manueel
