### ISSUE TITLE
Trash Calendar Sint-Truiden

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#639]
When there is an "space" in a streetname the trashcalendar doesn't search for housenumbers!

**Comment by RubenMattan** [comment]
This is not a bug on our end.

**Comment by OSATOM** [comment]
Who has to solve this?

<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-30 14:33 GMT+01:00 Ruben Mattan <notifications@github.com>:

**Comment by RubenMattan** [comment]
You need to check with limburg.net if the street is connected and the street has house numbers

**Comment by OSATOM** [comment]
Pieter found this bug and is going to solve this in the other
Trashcalendars so i do not think it is Limburg.net?!


<http://www.onzestadapp.be>

TOM VAN HECKE / CEO & Co-Founder
tom@onzestadapp.be / +32 (0)474 79 25 80

ONZE STAD APP
+32 (0)9 324 25 64
Antwerpsesteenweg 199080 Lochristi
www.onzestadapp.be
info@onzestadapp.be

[image: Twitter] <https://twitter.com/onzestadapp> [image: Facebook]
<https://www.facebook.com/onzestadapp> [image: Youtube]
<https://www.youtube.com/c/OnzestadappBe-Vlaanderen>

Bekijk hier de Sint-Truiden-App-Movie! <https://youtu.be/x8xJvfTNc7U>


2017-10-30 15:01 GMT+01:00 Ruben Mattan <notifications@github.com>:

**Comment by RubenMattan** [comment]
As i said its not a bug, limburg.net returns an empty list
