### ISSUE TITLE
Issues adding app users & roles

### ISSUE THREAD

**Issue by samyongo** [our-city-app/oca-backend#640]
Hi,

Maybe I m doing it wrong but I have tried a number of way and it's not working.
I m getting the erreur **" Please provide an existing user"**
What I'm trying to do is to add users to manage just the agenda part of the application.

Regards,

Sam Yongo

**Comment by abom** [comment]
Hi Sam,
Did you check that the user is connected to the service your are trying to add the roles for?
Also, it's an auto-connected service or the user connected manually?

**Comment by bart-at-mobicage** [comment]
We improved the text in the popup
