### ISSUE TITLE
Uitkalender

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#653]
Enkel 2 van de 10 events zijn zichtbaar in de uitkalender van Lo-Reninge.
In Uit in Vlaanderen, staan de events nochtans met een startuur.

![schermafbeelding 2017-11-10 om 11 14 40](https://user-images.githubusercontent.com/33022464/32659602-c20650c2-c61f-11e7-8d19-894e6841e954.png)

Only 2 out of 10 events are visible in Lo-Reninge's calendar.
In Out in Flanders, however, the events are held with a start time.

**Comment by RubenMattan** [comment]
@bart-at-mobicage Just checked the logs we have 0/8 now, but al these events cannot be added.

**Comment by bart-at-mobicage** [comment]
Another one. They said it was created at Oct 27.
I didn't find the event in the logs, but I didn't search very well.

https://www.anzegem.be/agenda/e/theatervoorstelling-boeing-boeing-door-lust-in-t-s/4615ebba-9f9e-4b87-8627-1a44414ad8c9

**Comment by RubenMattan** [comment]
The event was not listed by 'city:Ingooigem' but i was by '8570 Ingooigem'
