### ISSUE TITLE
ADD ADMINISTRATOR

### ISSUE THREAD

**Issue by OSATOM** [our-city-app/oca-backend#656]
It is to difficult to ad an administrator. 
It should be very easy especially for associations this is really a big cobblestone to use the app.

So I propose to add a field @ app permissions &users with following description
------ Add Administrator field ------ Attention this person will have full acces to your app!

![schermafbeelding 2017-11-14 om 10 05 07](https://user-images.githubusercontent.com/23034120/32771792-2a4802aa-c924-11e7-98c8-44570ca745a5.png)

Thanks

**Comment by bart-at-mobicage** [comment]
Duplicate: #466
