### ISSUE TITLE
double address

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#657]
there are still double addresses at some municipal services
 
![2017-11-15 11 35 02](https://user-images.githubusercontent.com/33022464/32831565-0a0dd57a-c9f9-11e7-8152-322a2db14d7d.jpg)
![2017-11-15 11 35 16](https://user-images.githubusercontent.com/33022464/32831588-19409ece-c9f9-11e7-9e99-a243084e561a.jpg)
![2017-11-15 11 35 29](https://user-images.githubusercontent.com/33022464/32831593-1b3f4338-c9f9-11e7-9d25-bbac985f083e.jpg)

**Comment by abom** [comment]
@stevendepaepe I think the fix will be for future services created from city dashboard, current duplicated address should be fixed manually, right @bart-at-mobicage?

**Comment by bart-at-mobicage** [comment]
I wrote an explorer script to fix the address in the settings and to provision, but made a mistake causing the provision not to happen. Didn't have time yet to finish.

**Comment by stevendepaepe** [comment]
Not ok yet
![IMAGE 2017-11-23 15:46:00.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46c1b9bb04a7c3fbdfb8e80ef50cbdc67a0676267350f57120d5a164fd52690e050a1de853524d41f5ff8d2ca1b23477de0803bc836d5f26c63f45a8b8864aad1da862da11d1e9e1d30695aa2f2ff58a88453f1b04198dfb5536a6984dc85ee406.jpg)
![IMAGE 2017-11-23 15:47:11.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46c1b9bb04a7c3fbdfb8e80ef50cbdc67a0676267350f47121d4a164fd52690e050a1de853524d41f5ff8d2ca1b23477de0803bc836d5f26c63f45a8b8864aad1da862da11d1e9e1d30695aa2f2ff58a88453f1b04198dfb5531a39842cd50e406.jpg)
![IMAGE 2017-11-23 15:47:20.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46c1b9bb04a7c3fbdfb8e80ef50cbdc67a0676267350f47122d5a164fd52690e050a1de853524d41f5ff8d2ca1b23477de0803bc836d5f26c63f45a8b8864aad1da862da11d1e9e1d30695aa2f2ff58a88453f1b04198dfb5531a4994cc85fe406.jpg)
