### ISSUE TITLE
App download problem as a user

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#659]
This person can not fill in email adres to get the Herk-de-Stad app on her phone.
Even before she can fill in her email she gets an error message. 
So after klicking on register with email.
![img_1342](https://user-images.githubusercontent.com/26439611/32895412-47bc6d36-cae0-11e7-9ec8-7ab43fc2236f.PNG)

Iphone 4S

**Comment by bart-at-mobicage** [comment]
That person needs to click on the EMAIL field and enter his/her email address before clicking the "Aanmelden met e-mail" button

**Comment by stevendepaepe** [comment]
Steven
 
Die foutmelding komt blijkbaar al nog voor ze de kans krijgt om op aanmelden te duwen. Ze geraakt dus niet op het lijntje om het mailadres in te geven.
 
Met vriendelijke groeten
 
Maarten Snoeks
Dienst Communicatie

**Comment by bart-at-mobicage** [comment]
de foutmelding wordt enkel getoond wanneer er op de knop geduwd wordt, of op de RETURN of ENTER toest rechtsonder op het keyboard
