### ISSUE TITLE
It's unclear that a friend needs to be selected when trying instead of publishing

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#665]
![schermafbeelding 2017-11-20 om 12 14 48](https://user-images.githubusercontent.com/26439611/33015832-78ab54fc-cdec-11e7-8240-17b1bb032840.png)
![schermafbeelding 2017-11-20 om 12 13 22](https://user-images.githubusercontent.com/26439611/33015835-7df9ca24-cdec-11e7-9592-81b6f2e520ec.png)
![schermafbeelding 2017-11-20 om 12 13 06](https://user-images.githubusercontent.com/26439611/33015846-85a223f2-cdec-11e7-89c9-97ea832ba068.png)

**Comment by RubenMattan** [comment]
<img width="896" alt="screen shot 2017-11-20 at 12 32 36" src="https://user-images.githubusercontent.com/1122760/33016467-f5200602-cdee-11e7-87ab-9c22729bbc14.png">
<img width="896" alt="screen shot 2017-11-20 at 12 31 48" src="https://user-images.githubusercontent.com/1122760/33016469-f6cfc87a-cdee-11e7-8e15-e10d916d956c.png">

**Comment by bart-at-mobicage** [comment]
We can improve the error message and/or the description. It's not clear for the user that he needs to follow first.

**Comment by abom** [comment]
The same problem happens with every user search dialog
Related: https://github.com/our-city-app/oca-backend/issues/640

**Comment by abom** [comment]
I will change the message to 

> This will publish the changes to only the following friends, you can select a friend by entering the name or email.

What about other places, like the add roles dialog.

**Comment by bart-at-mobicage** [comment]
EN
> This will publish the changes to only the following followers. You can select a follower by entering his name or email.
NL
> Hiermee kunt u de wijzigingen eerst uitproberen bij bepaalde volgers. Selecteer een volger door de naam of het e-mailadres in te geven.

**Comment by abom** [comment]
Yes, better that "friend", specially for the services, users follow services.
