### ISSUE TITLE
mail characters

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#673]
Een vraagje: bij het maken van een nieuwsberichtje kan je kiezen om een e-mailadres toe te voegen. (actieknop) Dit staat waarschijnlijk standaard beperkt tot 15 karakters. Kan dit veld standaard groter worden? We hebben nl. een gemeente met naam Langemarke-poelkapelle.

when creating a news item you can choose to add an e-mail address. (action button) This is probably limited to 15 characters by default. Can this field become larger by default?
We have a municipality with a name  Langemarke-poelkapelle
Thanks

**Comment by bart-at-mobicage** [comment]
The Dutch translation is too long for the button (max 15). Changing it from "E-mail verzenden" to "Mailen".
