### ISSUE TITLE
News item priority

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#679]
# GOAL

In the news stream the news articles sent by the community services are sinking under the news articles sent by merchant/association/care services.

# Description

We want to change the news article priorities such that news articles sent by community services are displayed higher than those of merchant/association/care services.

_In the ideal world the new sort priorities should be:_
1. `(05)` _News articles sent by community services_
2. `(10)` _Sponsored news articles_
3. `(20)` _News articles liked by friends_
4. `(30)` _News articles sent by connected services_
5. `(40)` _News articles sent by other services_
6. `(45)` _News articles that don't match the target audience_
7. `(50)` _Read news articles_

However, we're taking a shortcut and will give case 1 and 2 the same priority. This will only take 1 minute to implement. We'll evaluate later. If we need to roll it back it will also take only 1 minute.

1. `(10)` News articles sent by community services or Sponsored news articles
2. `(20)` News articles liked by friends
3. `(30)` News articles sent by connected services
4. `(40)` News articles sent by other services
5. `(45)` News articles that don't match the target audience
6. `(50)` Read news articles

# Implementation

- [x] When calling `news.publish` set `sticky=True` if the organization type of the service/customer is COMMUNITY_SERVICE.

### Remarks

- [x] We should not use these priorities in apps with custom organization types (like ae-veda)

**Comment by stevendepaepe** [comment]
Once read the news from the communities they should not stay on top of the stream.

**Comment by bart-at-mobicage** [comment]
Fixed for newly created news items.
I modified the existing news items. This will fix it for new installs or users that don't the news items on their phone yet.

**Comment by stevendepaepe** [comment]
Not ok yet
![IMAGE 2018-01-09 11:10:18.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46c1b9bb04a7c3fbdfb8e70ef40cbdc4700676227355f37121dda164fd52690e050a1de853524d41f5ff8d2ca1b23477de0803bc836d5f26c63f45a8b8864aad1da862da11d1e9e1d30695aa2f2ff58a88453f1b041d8df65f33a29942ce5de406.jpg)

**Comment by bart-at-mobicage** [comment]
> Not ok yet

Because it was posted less than 3 weeks before the one of Sleeplife (20 days, 10 hours and 9 minutes time difference) it's still higher in the feed.

**Comment by bart-at-mobicage** [comment]
Or did you reinstall the lochristi app?
