### ISSUE TITLE
Place icons and 4th row icons

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#680]
I think the space between the banner and first row icons is to narrow.
I would also be nice to make a 4th row visible on each page.
![image 2017-11-28 11 21 49](https://user-images.githubusercontent.com/26439611/33314565-54774e68-d42e-11e7-81c9-f1961a93d84f.jpg)

**Comment by RubenMattan** [comment]
Put on hold, as a 4th row is not the best solution for every device.
