### ISSUE TITLE
Registreren met welkomst bericht in app op tel

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#684]
Deze knop werkt maar een keer, dus als iemand daar op klikt om zich te registreren als handelaar maar er op dat moment niet mee door gaat kan hij deze knop op een later tijdstip niet meer gebruiken.

**Comment by bart-at-mobicage** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/issues/343

**Comment by stevendepaepe** [comment]
Register with welcome message in app on phone

This button only works once, so if someone clicks on it to register as a merchant but is not going through it at that moment, he can not use this button at a later date.
