### ISSUE TITLE
Functionaliteiten pag in dashboard

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#685]
Het moet mogelijk zijn om alle functionaliteiten te activeren in het dashboard, dus ook afspraak, herstelling,... wij krijgen hier veel vragen over.

**Comment by stevendepaepe** [comment]
Functionalities page in dashboard

It must be possible to activate all functionalities in the dashboard, including appointment, repair, ... we get a lot of questions about this.

**Comment by bart-at-mobicage** [comment]
@stevendepaepe, can you prepare a list of the remaining modules, with the EN and NL description that has to be shown? Make sure the description is consistent with the functionalities that already exist.

English descriptions:
![screen shot 2017-12-01 at 11 46 53](https://user-images.githubusercontent.com/17762105/33479427-5c854bf8-d68d-11e7-9159-0445f57880ea.png)

I've requested the images from Roel.

**Comment by Sylviecraeye** [comment]
Afspraken
Laat alle app gebruikers een afspraak maken
Appointments
Allow all app users make an appointment

Herstellingen
Laat alle app gebruikers een herstelling doorgeven
Reparations
Allow all app users report their reparations

Groepschat (enkel voor verenigingen)
Laat alle app gebruikers in groep communiceren
Group chat (only for associations)
Allow all app users communicate in groups

**Comment by bart-at-mobicage** [comment]
@abom, I will receive the images from Roel tonight. In the mean time, can you add these functionalities already?

**Comment by bart-at-mobicage** [comment]
I received the images a bit sooner
![2017-12-12 14 37 03](https://user-images.githubusercontent.com/17762105/33887409-fb4947de-df49-11e7-880a-ba9046bee127.jpg)
![2017-12-12 14 37 10](https://user-images.githubusercontent.com/17762105/33887410-fb621958-df49-11e7-8e81-5f44559431b9.jpg)
![2017-12-12 14 37 13](https://user-images.githubusercontent.com/17762105/33887411-fb7bc970-df49-11e7-826a-0bdc321d0433.jpg)

**Comment by RubenMattan** [comment]
@bart-at-mobicage think the 'Group chat' icon is missing/incorrect

**Comment by bart-at-mobicage** [comment]
the group chat image is the same as ask question and is already in the project. I updated my previous comment.

**Comment by RubenMattan** [comment]
Ok, because Sylvie only posted 3 new modules/translations

**Comment by bart-at-mobicage** [comment]
@Sylviecraeye, are we going to skip the GROUP PURCHASE module?

**Comment by Sylviecraeye** [comment]
Yes, almost anyone use this

Verstuurd vanaf mijn iPhone
