### ISSUE TITLE
Meldingskaart Diksmuide

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#686]
Meldingskaart
Vaak krijgen zij meldingen binnen waar mensen geen uitleg bij geven, een ook geen foto nemen. Kan het eerste veldje ‘omschrijving van de melding’ eventueel verplicht gemaakt worden?

Notification card
They often receive reports that people do not give an explanation or don't take pictures about of the reports. Can the first field 'description of the report' be made mandatory?

**Comment by lucasvanhalst** [comment]
Op iedere stap is er een knopje 'Open validation editor' (onder 'Form settings'). Daarin kan er gechecked worden of de stap ingevult is of niet.

Text line / single select / date / photo :
```javascript
function run(result) {
    return result.value ? true : 'Please fill in the field';
}
```

Multi select:
```javascript
function run(result) {
    return result.values.length ? true: 'Please select a value';
}
```

je kan de text natuurlijk aanpassen

**Comment by bart-at-mobicage** [comment]
We will add a `required` checkbox to a Form in the message flow designer. So if you can wait until next app update, then the javascript validation blocks defined above aren't needed.

**Comment by bart-at-mobicage** [comment]
In the steps that should be required, click on "Form Settings" > "Open validation editor" > "Snippets".
Then change the "Error message" into the message you want to show (in the main language of the service).
Click "Select" and "Close".
When all steps are changed, save the message flow. Close the message flow designer and publish the changes.
