### ISSUE TITLE
After this service is disabled and all users are disconnected this service remains on my phone

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#687]
![schermafbeelding 2017-11-30 om 15 26 54](https://user-images.githubusercontent.com/26439611/33435638-f1ff4806-d5e2-11e7-868b-3e7929550c5b.png)
![schermafbeelding 2017-11-30 om 15 25 13](https://user-images.githubusercontent.com/26439611/33435639-f4e185b6-d5e2-11e7-8007-98f864df6ec4.png)
![image 2017-11-30 15 27 31](https://user-images.githubusercontent.com/26439611/33435646-fc710c84-d5e2-11e7-8904-419c6863cf5d.jpg)

**Comment by bart-at-mobicage** [comment]
duplicate of https://github.com/rogerthat-platform/rogerthat-backend/issues/472
