### ISSUE TITLE
Possibility to customize the homescreen with a branding

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#689]
We have to come up with a way to use a branding as homescreen. The branding will contain buttons that will call `rogerthat.util.open` to open the different functionalities in the app.

This has to be configurable per app. Branding should be updatable via the backlog. The app's type still has to be `App.TYPE_CITY_APP`.

**Comment by RubenMattan** [comment]
Implementation on RT side is done see https://waffle.io/rogerthat-platform/home?milestone=2.1.X%20-%20Custom%20Homescreen
