### ISSUE TITLE
Payment improvements

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/oca-backend#693]
Payment step text:
- [x]  Add 'pay upfront to save time in our shop'

Payment memo:
- [x] Change to 'Payment ${rogerthat.user.name} via ${rogerthat.system.appName} app'

Pay widget:
- [x] Show a checkmark with text 'successfully paid x euro' 
- [ ] ~Show amount inside the pay button~ not really possible

Order flow received: 
- [x] Add transaction id and provider to SolutionOrder
- [x] Add paid amount to 'description' from SolutionOrder
 
Dashboard:
- [ ] Add instructions for setting up payconiq (search payconiq uitleg tekstje + example email how to get started ... TODO) + sample email text with 'send email' button
- [x] Add description to 'Enabled' button
- [x] Add description to 'Optional' button

**Comment by stevendepaepe** [comment]
[Template onze stad app (1).docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59edb5f11ea39f00118d4b68/125516c66e82c728ace21e0d46dc9197338e82bd8aa9b04dbe58b0873d4723332814b36b38d4aa6af3006b1300051bff054a5556f9f08f2fa1b138788d085fe5803f5f74943d13f8bc821bea13a632c91edbe2e3d7158abd7f37ed998e46341f00198af65e3da69c49c151ff59ac.docx)

**Comment by bart-at-mobicage** [comment]
@Sylviecraeye will make the instructions more clear. Then we can finalize this feature.

**Comment by Sylviecraeye** [comment]
the adapted document has been sent to Johan (payconiq) for verification / confirmation

**Comment by bart-at-mobicage** [comment]
> [Payconiq Online Overeenkomst FR - Belfius (1).pdf](https://github.com/our-city-app/oca-backend/files/1660351/Payconiq.Online.Overeenkomst.FR.-.Belfius.1.pdf)
> [Payconiq Online Overeenkomst NL - KBC.pdf](https://github.com/our-city-app/oca-backend/files/1660355/Payconiq.Online.Overeenkomst.NL.-.KBC.pdf)
> [SDD mandaat FR.pdf](https://github.com/our-city-app/oca-backend/files/1660357/SDD.mandaat.FR.pdf)
> [SDD mandaat NL.pdf](https://github.com/our-city-app/oca-backend/files/1660358/SDD.mandaat.NL.pdf)
> [Payconiq Online Overeenkomst NL - ING.pdf](https://github.com/our-city-app/oca-backend/files/1660359/Payconiq.Online.Overeenkomst.NL.-.ING.pdf)
> [Payconiq Online Overeenkomst NL - Belfius.pdf](https://github.com/our-city-app/oca-backend/files/1660361/Payconiq.Online.Overeenkomst.NL.-.Belfius.pdf)
> [Payconiq Online Overeenkomst FR - KBC.pdf](https://github.com/our-city-app/oca-backend/files/1660364/Payconiq.Online.Overeenkomst.FR.-.KBC.pdf)
> [Payconiq Online Overeenkomst FR - ING.pdf](https://github.com/our-city-app/oca-backend/files/1660366/Payconiq.Online.Overeenkomst.FR.-.ING.pdf)
> [Payconiq Online Overeenkomst FR - Belfius (1).pdf](https://github.com/our-city-app/oca-backend/files/1660367/Payconiq.Online.Overeenkomst.FR.-.Belfius.1.pdf)
> 
> [inschrijvingsdoc. Payconiq.pdf](https://github.com/our-city-app/oca-backend/files/1660381/inschrijvingsdoc.Payconiq.pdf)
> 
> 
> In het inschrijvingsdoc. staat de uitleg.
>

**Comment by bart-at-mobicage** [comment]
I think the content of the "inschrijvingsdoc.pdf" is what we need to show in the dashboard. And then give 3 bank choices: Belfius / KBC / Other, which will download the contract in the service it's language.

**Comment by RubenMattan** [comment]
Just read the instructions, for me its not clear what i need to do with the agreement/sepa document.
Also point 3 is incorrect they need to fill in these credentials thereself

**Comment by bart-at-mobicage** [comment]
They need to send an email with their id, the signed agreement and sepa to johan.boeckstijns
He will reply and include the tokens which they need to enter in the dashboard.

**Comment by RubenMattan** [comment]
Please provide a new instructions pdf
