### ISSUE TITLE
Empty agenda

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#696]
Bij Chiro Jooniek in Staden staat agenda leeg ipv "Er zijn geen geplande evenementen"

At Chiro Jooniek in Staden, the agenda is empty instead of "There are no scheduled events"

![2017-12-07 10 31 35](https://user-images.githubusercontent.com/33022464/33716735-8e9ade40-db57-11e7-9d0c-28e8c58cb94e.jpg)

**Comment by bart-at-mobicage** [comment]
possibly fixed by e2be236

**Comment by bart-at-mobicage** [comment]
I had to regenerate the `Agenda` branding. Seems to be fixed now.
