### ISSUE TITLE
Tablet does not scan any more. Urgent!!

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#708]
The tablet from the service: service-779fe4a8-4211-4634-aead-af7b58d544c7@rogerth.at
does not scan any more. It is a tablet that we delivered and blocked.
They use it a lot so it is urgent!

**Comment by stevendepaepe** [comment]
![26175171_10213768669507119_1430289975_n](https://user-images.githubusercontent.com/26439611/34380479-f5446b2a-eb01-11e7-9dc6-0fffc0144741.jpg)
![26105123_10213768669547120_954622202_o](https://user-images.githubusercontent.com/26439611/34380480-f6f3329e-eb01-11e7-9376-2cd24818521e.jpg)

**Comment by stevendepaepe** [comment]
The slides still appear,

But if I want to scan, I can no longer enter a discount amount.

Only the e-mail address again and again

**Comment by abom** [comment]
@stevendepaepe The problem still exists?

**Comment by stevendepaepe** [comment]
Yes it does

**Comment by bart-at-mobicage** [comment]
osa-loyalty app not yet uploaded because of #716

**Comment by lucasvanhalst** [comment]
Need to update the app in the playstore and upload a new version to the locked devices
