### ISSUE TITLE
Forwarding messages

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#715]
It should be possible to forward questions in the dashboard, asked in an app, to another service.

**Comment by bart-at-mobicage** [comment]
In Bree there are 20 community services. People often ask questions to the common community service. They want to be able to forward the question to the correct community service (eg. the library community service). The library community service must be able to respond to that question.

Should only be possible for community services. We need a "Forward" button, next to the "Reply" button.
