### ISSUE TITLE
osa-loyalty-2.1.3619.A-release.apk

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#716]
- [ ] When you go to the dashboard and back you lose the scan window
- [ ] Dashboard keeps flashing yellow even when there are no unread messages anymore!
- [ ] When a message (new order) comes in the tablet makes no noise.

**Comment by lucasvanhalst** [comment]
@stevendepaepe I can not reproduce the last 2 points, do you have any more details?

**Comment by stevendepaepe** [comment]
The sound was on because it made sound when i opened the app.
The tablet was on for a few minutes.

**Comment by lucasvanhalst** [comment]
Found a fix for the scan window not showing, but I can't reproduce the rest
