### ISSUE TITLE
shopping cart or ecommerce

### ISSUE THREAD

**Issue by samyongo** [our-city-app/oca-backend#718]
Hi,

Now that our API worked. Do we have shopping cart somewhere that can be easily integrated at Kinshasa App if not what are my option.

Regards,

Sam Yongo

**Comment by bart-at-mobicage** [comment]
Hi @samyongo,

I think the advanced order module is the thing you are looking for. 
We have a Dutch tutorial video available: https://www.youtube.com/watch?v=hHOkurV4IIE
I know it's Dutch, but shows the result in the app etc...
