### ISSUE TITLE
Events not in the agenda (Staden)

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#723]
Evenementen van de Harmonie De Verenigde Staden worden niet gesynchroniseerd met de Uit-databank. Ze zijn wel zichtbaar op www.uitinvlaanderen.be. Concreet gaat het over volgende evenementen:
o   Lenteconcert (28 april 2018)
o   Aperitiefconcert (24 juni 2018)
o   Parkconcert (23 augustus 2018)
o   De Slimste Stadenaar (20 oktober 2018)

Events of the Harmonie The United Staden are not synchronized with the Out database. They are visible on www.uitinmidwest.be. Specifically, it concerns the following events:
o Spring concert (28 April 2018)
o Aperitif concert (24 June 2018)
o Park concert (23 August 2018)
o The Smartest Stadenaar (October 20, 2018)

![schermafbeelding 2018-01-05 om 11 07 11](https://user-images.githubusercontent.com/33022464/34604732-2fa5c6fc-f209-11e7-95df-119689008ffe.png)

**Comment by RubenMattan** [comment]
Possible issue:

```js
message: Uncaught ReferenceError: Map is not defined
```

**Comment by bart-at-mobicage** [comment]
I contacted UiT support. I don't know what we're doing wrong.

**Comment by bart-at-mobicage** [comment]
> Ik heb het hier even bekeken. Op dit moment lijkt voor die events die je aankaart het probleem: datetype=next3months .
Je filtert immers latere resultaten weg...
> 
> Er speelt immers nog iets anders ook; jullie filteren nu op city: en dan de deelgemeente,
maar sinds de komst van de vernieuwde databank worden deelgemeenten weggeschreven als 
deelgemeente (hoofdgemeente). Dus je dient best steeds de hoofdgemeente toe te voegen achter iedere deelgemeente op volgende wijze:
8840 Oostnieuwkerke (Staden)

**Comment by bart-at-mobicage** [comment]
Add the format to the input popup (as a descriptive text above the input field)

NL: 

> Gebruik het volgende formaat bij het ingeven van een deelgemeente:
> postcode deelgemeente (hoofdgemeente)
> 
> Bvb 8840 Oostnieuwkerke (Staden)
