### ISSUE TITLE
Keep spinning when i want to follow a new merchand

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#724]
Bij het volgen van een nieuwe handelaar of vereniging, blijf het wieltje draaien/spinnen.
Getest in verschillende app's.
bv Staden, Sint-Truiden, Diksmuide.
Bij Staden ook al de melding gekregen van een gebruiker.

When following a new merchand or association, keep running / spinning the wheel.
Tested in different app's.
eg Staden, Sint-Truiden, Diksmuide.
At Staden also received the notification from a user.

**Comment by bart-at-mobicage** [comment]
Because of  #725
