### ISSUE TITLE
Merchants on map with or without loyalty

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#726]
When Loyalty function is not active, the terminal still says: has terminal: Yes
So the merchant is still on the map with loyalty
https://rogerth.at/customers/map/be-berlare
![schermafbeelding 2018-01-05 om 12 27 00](https://user-images.githubusercontent.com/26439611/34607483-2ac88100-f214-11e7-82e5-1aceee58509a.png)
![schermafbeelding 2018-01-05 om 12 26 46](https://user-images.githubusercontent.com/26439611/34607486-2cdec2ec-f214-11e7-8bd3-dd80cff9e291.png)

**Comment by bart-at-mobicage** [comment]
Create a migration script as well.

**Comment by abom** [comment]
That's because the loyalty module was disabled or enabled in dashboard (not the shop).
