### ISSUE TITLE
Push messages waste calendar Bree

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#730]
Bree wants to automatically turn on the push messages in the waste calendar for all users.

**Comment by RubenMattan** [comment]
Not going to auto enable all types of trash reminders. User should enable this their self, however we are discussing how we can put these reminders in a flow.

**Comment by RubenMattan** [comment]
@stevendepaepe or @bart-at-mobicage any updates?

**Comment by bart-at-mobicage** [comment]
Bree agreed. Deadline: end of April

**Comment by RubenMattan** [comment]
Will be fixed when a new version of the branding is published
