### ISSUE TITLE
Payconiq

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#741]
[Payconiq Online Overeenkomst FR - Belfius (1).pdf](https://github.com/our-city-app/oca-backend/files/1660351/Payconiq.Online.Overeenkomst.FR.-.Belfius.1.pdf)
[Payconiq Online Overeenkomst NL - KBC.pdf](https://github.com/our-city-app/oca-backend/files/1660355/Payconiq.Online.Overeenkomst.NL.-.KBC.pdf)
[SDD mandaat FR.pdf](https://github.com/our-city-app/oca-backend/files/1660357/SDD.mandaat.FR.pdf)
[SDD mandaat NL.pdf](https://github.com/our-city-app/oca-backend/files/1660358/SDD.mandaat.NL.pdf)
[Payconiq Online Overeenkomst NL - ING.pdf](https://github.com/our-city-app/oca-backend/files/1660359/Payconiq.Online.Overeenkomst.NL.-.ING.pdf)
[Payconiq Online Overeenkomst NL - Belfius.pdf](https://github.com/our-city-app/oca-backend/files/1660361/Payconiq.Online.Overeenkomst.NL.-.Belfius.pdf)
[Payconiq Online Overeenkomst FR - KBC.pdf](https://github.com/our-city-app/oca-backend/files/1660364/Payconiq.Online.Overeenkomst.FR.-.KBC.pdf)
[Payconiq Online Overeenkomst FR - ING.pdf](https://github.com/our-city-app/oca-backend/files/1660366/Payconiq.Online.Overeenkomst.FR.-.ING.pdf)
[Payconiq Online Overeenkomst FR - Belfius (1).pdf](https://github.com/our-city-app/oca-backend/files/1660367/Payconiq.Online.Overeenkomst.FR.-.Belfius.1.pdf)

[inschrijvingsdoc. Payconiq.pdf](https://github.com/our-city-app/oca-backend/files/1660381/inschrijvingsdoc.Payconiq.pdf)

In het inschrijvingsdoc. staat de uitleg.

**Comment by bart-at-mobicage** [comment]
#693
