### ISSUE TITLE
Tablet blocked

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#742]
When the customer wants to go to his dashboard via his tablet. He gets a screen where he has to enter a code.
Keurslager De Bruycker

![image 2018-01-25 13 17 43](https://user-images.githubusercontent.com/33022464/35387947-221bdc3c-01d2-11e8-8199-47d668812a23.jpg)

**Comment by bart-at-mobicage** [comment]
See https://github.com/rogerthat-platform/rogerthat-android-client/pull/15/commits/0325e4d0b8193d54ac47d1706e6be9b39b2795d9

Only use CustomTab when isExternalUrl is true and url starts with http(s).
Otherwise, stay inside the app and open in a 2nd web view

**Comment by RubenMattan** [comment]
I guess https://github.com/rogerthat-platform/rogerthat-android-client/commit/2c8c09307ca1139ea51f7c3cb312bb48bc6b302c is the commit what caused the problem

**Comment by RubenMattan** [comment]
Revered the 2 commits https://github.com/rogerthat-platform/rogerthat-android-client/pull/324
