### ISSUE TITLE
Empty dashboard agenda page in calendar Herne

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#749]
![schermafbeelding 2018-02-09 om 11 37 52](https://user-images.githubusercontent.com/26439611/36023810-0195bbb4-0d8e-11e8-8870-cd908740d040.png)
![image 2018-02-09 11 40 39](https://user-images.githubusercontent.com/26439611/36023823-0e616ba4-0d8e-11e8-89c0-7d0cbd45be97.jpg)

**Comment by bart-at-mobicage** [comment]
cannot reproduce + it's ok in their dashboard now
