### ISSUE TITLE
Failed to set prospect status

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/oca-backend#75]
POST /internal/shop/rest/prospects/set_status
URL being requested: POST https://www.googleapis.com/calendar/v3/calendars/primary/events?alt=json&sendNotifications=true
Refreshing due to a 401 (attempt 1/2)
Refreshing access_token
Failed to retrieve access token: {
  "error" : "invalid_grant"
}

**Comment by lucasvanhalst** [comment]
Same cause as #74
