### ISSUE TITLE
besteleenheid  order

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#757]
Kan de besteleenheid losgekoppeld worden van de prijs.  Vb bij kippenfilet wil ze graag de prijs per kilo vermelden, maar de besteleenheid per stuk.  

The order unit can be disconnected from the price. With chicken fillet she wants to mention the price per kilo, but the order unit per item.

**Comment by bart-at-mobicage** [comment]
Useful when using payconiq too. Imagine you order meat eg. 400g chicken fillet, but the chicken fillet is 300g, then you paid for 400g, but you receive 300g.

**Comment by bart-at-mobicage** [comment]
Oh, I was wrong. You are totally right. We don't know how much that item will cost since we don't know the weight. So it shouldn't be possible to order using the e-shop.
