### ISSUE TITLE
Setup instructions layout

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#765]
- [x] Rename "SDD Mandaat" in the download link to "SEPA Mandaat", because this is how it's called in the setup instructions
- [x] The setup instructions are now downloadable in the form of a PDF. I got the remarks that it would be nicer if this is a separate page. It was also not clear for Steven that the green cog symbol was a button that could be pressed. Create a new tab called "Mobile payments" next to "Order" (under "Settings"). Then we could show the setup instructions in the page itself (so no more pdf), with buttons for the documents that need to be downloaded.
  - 1 ....................................  
..................  
.....
    - A [ [SEPA Mandaat](https://github.com/our-city-app/oca-backend/blob/55f811a96371d0376e4b70eedf85d15e65afe901/src/static/files/payment/payconiq/mandate-nl.pdf) ]
    - B [ [Belfius](https://github.com/our-city-app/oca-backend/blob/55f811a96371d0376e4b70eedf85d15e65afe901/src/static/files/payment/payconiq/agreement-belfius-nl.pdf) ] [ [KBC](https://github.com/our-city-app/oca-backend/blob/55f811a96371d0376e4b70eedf85d15e65afe901/src/static/files/payment/payconiq/agreement-kbc-nl.pdf) ] [ [Other](https://github.com/our-city-app/oca-backend/blob/55f811a96371d0376e4b70eedf85d15e65afe901/src/static/files/payment/payconiq/agreement-ing-nl.pdf) ]
  - 2 .............  
.........
  - 3 .......................
  - 4 ..........................  
...........  
Merchant ID: [ textfield ]  
Account Key: [ textblock ]  

So the above in a separate page instead of the current popup. 
![screen shot 2018-02-27 at 09](https://user-images.githubusercontent.com/17762105/36722609-3ca069d8-1bae-11e8-8299-0a9a53953657.png)

**Comment by abom** [comment]
https://github.com/our-city-app/oca-backend/pull/601/commits/e720d8ced4b4e877cc75305a74aaaa2ac7253bc0 and https://github.com/our-city-app/oca-backend/pull/601/commits/5e01020a39e889973832ffd4b8f99eed23709766

**Comment by bart-at-mobicage** [comment]
2 small remarks

- let's auto-save the merchant id and account key fields (so no SAVE button anymore)
- let's change the rows of the account key field to 5
