### ISSUE TITLE
Wrong tekst in step 3 

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#767]
Tekst in step 3 is the same as in step 3
It should be:
Stap 3: Uw eigen app is een feit!
Als uw stad/gemeente uw aanvraag goedkeurt, krijg je via mail een login voor je dashboard.
Nu kan je aan de slag, succes!
![schermafbeelding 2018-03-01 om 11 33 37](https://user-images.githubusercontent.com/26439611/36841107-9667aa22-1d47-11e8-8e96-c162a3b0ac9b.png)

**Comment by abom** [comment]
Will use the text of step 3 from https://github.com/our-city-app/oca-backend/issues/528#issuecomment-331874739

> Wanneer de stad/gemeente uw registratie aanvaardt, zal u een e-mail ontvangen met uw login en wachtwoord. U kan nu uw eigen invulling geven aan uw applicatie. VEEL SUCCES en WELKOM!
