### ISSUE TITLE
Need a version check in the order flow with payment

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#783]
- [x] Add `Features.PAY_WIDGET` (iOS: 1.2637, Android 1.3874) to rogerthat-backend
- [x] If payment is optional, then skip the pay step on an old phone
- [x] If payment isn't optional, then show `message_feature_not_supported` (see `flowcode_check_feature` in `advanced_order.xml`)

**Comment by abom** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/303/commits/df1b92d228796239f36ef01d1be8bd796abd889e and https://github.com/our-city-app/oca-backend/pull/601/commits/cc059a24669aa969b2652a6e4f35a24990ac5518.
