### ISSUE TITLE
Report card integration with 3P

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#785]
Issues reported using the report card in the city app need to be saved into 3P

The software of 3P runs on an internal network of the city. We'll need to be able to save xml files on a certain path on the fileserver on this network. The 3P software will check for new xml files on startup to import new issues. An example of such a file: [werkopdracht.zip](https://github.com/our-city-app/oca-backend/files/1806487/werkopdracht.zip)

- [ ] Create a GAE application that receives the flow results and saves the reports in the datastore
  - Make sure the code can be reused by multiple services
  - [ ] Place an xml file per report (filename: <id>.xml) in a google cloud storage bucket. This directory will be synced by the community service using `gsutil rsync -r data gs://rogerthat-3p-<SIK>/data`.
  - [ ] Create a mail receiver in the GAE application such that we can send updates to the user. Use an email address per report and use this in the `requestor.email` field. 3P sends status updates to this email address.

More info:

> 1/ We hebben een voorbeeld gekregen van een Workorder in XML formaat (zie bijlage), waarvoor dank. Hebben jullie ook een XSD van de xml-structuur, die wij zouden kunnen gebruiken?
> **—> Zie bijlage, gemaakt op basis van de werkopdracht.xml**
> 
> 2/ Hoe moeten wij de werkopdrachten klaarzetten? 
> - In de voorbeeld-XML zat 1 werkopdracht, hoe halen jullie meerdere werkopdrachten op?
> - Kunnen jullie die ophalen via HTTPS requests (met bvb Basic authentication?) of moet dit via FTP gebeuren?
> **—> Elke werkopdracht is 1 bestand.**
> **—> 3P moet eraan kunnen via een lokale netwerk (verkenner) bij het bestuur.  Dus eventueel via script van FTP kopiëren naar een map op het netwerk.**
> 
> 3/ lambert72X en lambert72Y: zijn deze velden optioneel? Of moeten we de lat/long coördinaten ook  converteren naar lambert72, zodat we deze ook kunnen in de xml steken?
> **—> Deze velden zijn inderdaad optioneel**
> 
> 4/ externID: daar mogen wij insteken wat wij willen? Bvb de ID van de aanvraag in ons systeem?
> **—> Klopt**
> 
> 5/ attachments: hoe moeten we deze definiëren? In de voorbeeld-xml staat "5.xml" als attachment, mag dit ook een URL zijn naar bvb een geüploade foto? Of staat in “5.xml” de attachment gedefinieerd? Indien dit het geval is, wat is de structuur van dit xml bestand? (en eventueel het schema in een XSD file)
> **—> Dit moet inderdaad een url zijn naar de documenten, type string.**
> 
> 6/ type, urgencyType en contactmethod zijn waarschijnlijk enums? Wat zijn de mogelijke waarden van deze velden? Indien contactmethod “gsm” is, waar moet het gsm-nummer gedefinieerd worden? Want ik vind geen gsm nummer in de voorbeeld-xml.
> **—> Dit zijn vrije tekstvelden in 3P, wij matchen als dat overeenkomt met gegevens in de databank. Er is inderdaad geen gymnummer veld voorzien in het importbestand.**
> 
> 7/ description en comment: hoe worden deze velden gebruikt? Zouden we als description bvb “Melding via Onze Stad App” zetten en dan als comment de input van de gebruiker?
> **—> Description is de titel van de werkopdracht, comment is een commentaar-veld waarin bvb. Opmerkingen worden weggeschreven over het verloop van de werkopdracht.**
> 
> 8/ Worden gebruikers op de hoogte gebracht als hun melding afgehandeld is? Is dit via email of op basis van de “contactmethod”? Of kunnen wij een webcallback krijgen zodat wij een bericht kunnen sturen in onze app naar de eindgebruiker?
> **—> De gebruikers krijgen een mail zodra een opdracht is uitgevoerd, deze mail wordt vanuit 3P verstuurd. We kunnen eventueel een mail naar jullie sturen (in vast formaat) zodat jullie ook een melding kunnen geven ?**
>

While testing, use "Test" as description.

**Comment by RubenMattan** [comment]
I am code complete. So now i need an example flow for the report card and access to an 3P environment to validate if its working.

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/issues/856
