### ISSUE TITLE
Using PAYCONIQ in test mode in the osa-demo2 app

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#788]
- [x] Make it possible to mark a service to run in TEST mode: `SolutionSettings.payment_test_mode` (bool) (don't add in the UI. this will be done using explorer for now).
- Add a bool `test_mode` to the PAY widget.
  - [x] rogerthat-backend
  - [x] rogerthat-ios-client
  - [x] rogerthat-android-client
  -  ~~rogerthat-mfr-server~~
  - [x] oca-backend: in `advanced_order.xml` (make sure it's not `null`)
- [x] The app should pass the `test_mode` bool to `rogerthat-payment`.
- [x] The payment provider code should receive this `test_mode` param when creating a transaction, such that it can send the request to `dev.payconiq.com` instead of `api.payconiq.com`

**Comment by RubenMattan** [comment]
Pay widget is not implemented for rogerthat-mfr. Had discussed this with geert 8 months ago and we didn't need to do that, since we want to ditch that.

**Comment by RubenMattan** [comment]
@lucasvanhalst still needs to pass the test_mode from context to the create transaction for payconiq

**Comment by RubenMattan** [comment]
Code complete. Need to be tested now

**Comment by RubenMattan** [comment]
order with payment disabled works

**Comment by RubenMattan** [comment]
order with payment enabled but optional without payment works

**Comment by RubenMattan** [comment]
order with payment enabled and required works
