### ISSUE TITLE
Remove the possibility to buy presence in another app

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#790]
- [x] Create migration for all existing services such that only Rogerthat and the main app remain
- [x] ~Remove this functionality from the shop (Business Admin)~
- [x] Remove this functionality from the dashboard shop

**Comment by bart-at-mobicage** [comment]
correction:
Bullet 1: migrate solution* service
Bullet 2: I changed my mind. just keep it in the shop (business admin) for special use cases

**Comment by RubenMattan** [comment]
3: https://github.com/our-city-app/oca-backend/commit/ce50be3f74f1bd678360cd43d52c888df3de283f

**Comment by RubenMattan** [comment]
1: https://github.com/our-city-app/oca-backend/commit/e1f57f01614d88249516ee2b557e920404fb6b4d

On my local machine i had no service that needed to be migrated. So better run dry run first
