### ISSUE TITLE
Temporarily hide all JOBS-related things from the dashboard

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#791]
Because the priorities have changed, we should not show anything jobs-related in the dashboard. Or if it's easy to do, move the jobs-related commits to a separate branch.

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/748/commits/59783a3fd816ec836dbefcb481d2b08399f5a9a6
