### ISSUE TITLE
Create a city-select widget in the target audience step

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#797]
Let merchants etc choose from a map (using Mapael like https://rogerth.at/unauthenticated/osa/flanders)

- Show the flanders map if the default app id of the service starts with "be-"
  - Create a mapping of countries and maps (json files)
  - If a country is not in the mapping, then just show a flat list with app names and checkmarks
- if the default app id is not in the list of cities, then skip the city-select widget (eg. for be-elisabeth-begijnhof)
- by default, pre-select the main city.
- gray out unsupported cities
- when hovering over a city, show the city name, and the reach (Eg. "Lochristi\nReach: 4831")
- use the new property of the `news.publish` api call

**Comment by abom** [comment]
In this case, what should app_ids and feeds properties of NewsItem contain?
As i got, app_ids should only contain current app id + rogerthat, and the list of the selected city apps should be set via feeds (NewsFeeds) property?

**Comment by RubenMattan** [comment]
So there are 2 new properties on news.publish:
- tags: a list of strings. A way for the service to identify and list news items
- feed_names: a list of objects see example [{'app_id': 'be-loc', 'name': null, 'app_id': 'be-berlare', 'name': 'regional_news'}] (feed name null == default == news)

app_ids of a news item should contain all id's of the apps where the item should be visible in.
Note: i would not add rogerthat to these app_ids anymore @bart-at-mobicage  what is your opinion?

feed_names is null for the default app_id all the others should be 'regional_news'.
