### ISSUE TITLE
Nuke secondary color

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#80]
* Nuke it from BOB and all build.yamls
* Auto-generate the secondary color in the prepare_build script of iOS, just like on android

**Comment by lucasvanhalst** [comment]
Don't think primary colour and accent colour should be the same though on android, perhaps a lighter variant of the primary would work

**Comment by siddiquagig** [comment]
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!
