### ISSUE TITLE
'SUBMIT' button in the advanced order flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#802]
<img src="https://user-images.githubusercontent.com/17762105/37713616-ba06647a-2d17-11e8-893a-a2f78eff5f11.jpg" width="200px"/>

In the past, this was the last step of the flow, so the button is called "SUBMIT". But now, there's a PAY step behind it, so this button should be called "NEXT" and the button in the PAY step should have been "SUBMIT".

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/803
