### ISSUE TITLE
Need some extra stats

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#804]
Need the following time-based graphs
- [x] City-app count (if possible incl. their name)
  - I think the data for this one can be logged when a `ShopApp` is being created
- [x] Total user count per city per day/week/month/year
  - A log entry in `finish_registration`?
- [x] Active user count per city per day/week/month/year
  - Based on api calls executed by distinct users?
- [x] Merchant/Care institution/Association count per city
  - A log entry when a Customer is created?
- [x] Merchants that have e-shop

- Create migration to set creation_time on App: `Customer.all().order('-creation_time')` and get default_app_id
- Create migration for initial app count based on App.creation_time

**Comment by lucasvanhalst** [comment]
- use App model
    - use creation_date to add points (one point per app)
    - tags: app_type
    - values: id (app id like be-loc)
    - For a graph: use cummulative_sum, e.g. `SELECT cumulative_sum(count("app_id")) FROM "created-apps" GROUP BY time(1d)`

**Comment by bart-at-mobicage** [comment]
More stats requested:
- [ ] time-based graph with amount of merchants that use the loyalty within range 
  - eg. like the daily/weekly/monthly graph in FB analytics
- [ ] time-based graph with loyalty actions
  - Scans
  - Redeems
  - Created paper loyalty cards

**Comment by RubenMattan** [comment]
The pipeline job fails

<Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>rogerthat-server@appspot.gserviceaccount.com does not have storage.objects.create access to oca-mr.</Details>

**Comment by RubenMattan** [comment]
I granted Storage Admin to that bucket, and removed alls jobs but 1
