### ISSUE TITLE
Agenda branding: Can not add multi-date event to the phone's calendar

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#81]
* email does not arrive
* Happened with event "Kerstavond" for the service "Gemeente Laarne"

**Comment by abom** [comment]
Fixed in #305?

**Comment by abom** [comment]
@bart-at-mobicage Still valid?

**Comment by bart-at-mobicage** [comment]
@abom, can you try to see if you can add a reminder for a multi-date event? if you see an email sent out with an .ics attachment (double-check the content) then you can close this issue with comment "Can not reproduce".

**Comment by abom** [comment]
Can not reproduce

**Comment by abom** [comment]
Can not reproduce
