### ISSUE TITLE
icoontjes verplaatsen

### ISSUE THREAD

**Issue by stevendepaepe** [our-city-app/oca-backend#815]
Het zou moeten mogelijk zijn om icoontjes te verplaatsen of ze automatisch te laten aansluiten ongeacht de actieve functies of statische inhoud.
Zoals het nu is wordt de app onoverzichtelijk
![img_20180327_193648](https://user-images.githubusercontent.com/26439611/38243206-0c51ec58-3737-11e8-8211-aba92e403541.jpg)
![img_20180327_193652 1](https://user-images.githubusercontent.com/26439611/38243209-0db1d928-3737-11e8-9d48-3a8d81d9a67c.jpg)

**Comment by abom** [comment]
How did we create this service? normal signup won't enable all of the functionalities.

**Comment by bart-at-mobicage** [comment]
I thought so too, but we've seen lot's of services with all functionalities.

Eg. `service-578a67a4-a788-4719-ac44-a370aefa10f2@rogerth.at` created at Apr 11.

**Comment by abom** [comment]
The problem happens only when approving service creation from mobile.
