### ISSUE TITLE
Joyn loyalty functionality

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#820]
We are partnering up with Joyn in BE. They will be our partner when it comes to loyalty systems. Existing BE merchants can still use the OCA loyalty system if they want. However, they should have the possibility to switch to Joyn loyalty. They cannot use both loyalty systems at once. New BE merchants can only go for the Joyn loyalty, and not the OCA loyalty anymore. However, they can still choose to download the OCA Terminal app to receive notifications when an inbox message arrives, or to show slides or to quickly open their dashboard and website.

- [ ] Update the title of the existing 'loyalty' functionality on the "Functionalities" page
  - customer outside BE or 'loyalty' in modules
    - EN: OCA Loyalty
    - NL: OSA Klantenkaart
  - else (customer in BE and 'loyalty' not in modules)
    - EN title: OCA Terminal
    - NL title: OSA Terminal
    - EN description: 
    - NL description: 
- [ ] The Settings > Loyalty page
  - customer outside BE or 'loyalty' in modules
    - Rename to "OCA Loyalty"
  - else (customer in BE and 'loyalty' not in modules)
    - Rename to "OCA Terminal"
    - Hide all scan/loyalty related stuff
- [ ] Add a new functionality: `SolutionModule.JOYN = 'joyn'`
  - Only show this for customers in Belgium
  - title:
    - EN: Joyn Loyalty
    - EN: Joyn Klantenkaart
  - description:
    - EN: Reward your loyal customers with your digital customer card
    - NL: Beloon je trouwe klanten met je digitale klantenkaart
  - image: 
![func_joyn](https://user-images.githubusercontent.com/17762105/38420098-fd2d57d0-39a2-11e8-9619-cc1e6e844cdb.png)
  - [ ] When activating the Joyn functionality, check if the loyalty functionality is enabled. If so, show a confirmation that the OCA Loyalty functionality will be disabled. Disable it after confirming.
- [ ] When people try to send a coupon, and they don't have the 'loyalty' or 'joyn' module
  - customer outside BE: keep current code (request loyalty system)
  - customer inside BE: explain they can activate the JOYN module and signup for Joyn at 
    - NL: https://www.joyn.be/nl/for-merchants
    - FR: https://www.joyn.be/fr/for-merchants
    - other: https://www.joyn.be/en/for-merchants
- [ ] Right now, for customers that don't see the Functionalities page (app without signup), the loyalty tab is always shown, even if they don't have the loyalty module.
  - In case the merchants lives in BE (regardless of signup enabled), explain how to become a Joyn merchant. Show a description and a button on this page.
    - Description
      - NL: De oplossing voor lokale handelaars die willen groeien
      - FR: La solution au service des commerçants locaux qui veulent grandir
      - other: The solution for local merchants who want to grow
    - Button
      - NL: Word Joyn-handelaar --> https://www.joyn.be/nl/for-merchants
      - FR: Devenir commerçant Joyn  --> https://www.joyn.be/fr/for-merchants
      - other: Become a Joyn merchant -- > https://www.joyn.be/en/for-merchants
- [ ] ~Add the action `'Joyn Loyalty'` when publishing, such that endusers can see clearly which merchants use this module.~
  - ~NL: Joyn Klantenkaart~

**Comment by RubenMattan** [comment]
In short BE customers can no longer signup for our loyalty but need to use joyn.
When enabled/disabled a link to joyn website will be shown.

**Comment by RubenMattan** [comment]
actions can only be added to a service when there is a menu item present

**Comment by bart-at-mobicage** [comment]
Ok, we'll have to move that part to #824

**Comment by RubenMattan** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/456
https://github.com/our-city-app/oca-backend/pull/841
