### ISSUE TITLE
Add link to Joyn app in sidebar of all existing BE city apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#822]
- [ ] If the app is not found on the phone, we probably show something like "The app is not installed". Update this to "The app is not installed or not up to date".
- [x] Add to `build.yaml` for all BE city apps
  - Sidebar menu item label: `Joyn Loyalty`
  - links to `joyn://` to all apps with app_id starting with `be-`
    - Commit these changes on a branch, such that we can merge this in when the Joyn app is released.
  - links to `joyn-acc://` to all apps with app_id starting with `osa-`
    - the changes for these demo apps can be pushed to master
- [ ] Send an apk file of `osa-demo2` to Joyn (via Slack)
  - mention that only the sidebar link is implemented and that the QR scan is not yet implemented.

**Comment by RubenMattan** [comment]
osa- = DEV apps

**Comment by RubenMattan** [comment]
@bart-at-mobicage What icon?

**Comment by bart-at-mobicage** [comment]
Should be those added in https://github.com/our-city-app/oca-backend/issues/824

Don't know if we might recolor them, probably not.

**Comment by RubenMattan** [comment]
Android design ok?
<img width="533" alt="screen shot 2018-04-09 at 14 49 43" src="https://user-images.githubusercontent.com/1122760/38498619-4b4cd81e-3c05-11e8-95d7-b574fe117d84.png">

**Comment by bart-at-mobicage** [comment]
I think we have to generate a circle, because now it's not consistent with the other icons.

**Comment by RubenMattan** [comment]
android and ios are ready for this on open_app branch.
What position will this new item have in the sidebar?

**Comment by bart-at-mobicage** [comment]
- Oops, there's no label next to the icon
- The URL scheme wasn't added to `LSApplicationQueriesSchemes` in `rogerthat_Info.plist`
  - osa-demo2[42252:8391757] -canOpenURL: failed for URL: "joyn-acc://" - error: "This app is not allowed to query for scheme joyn-acc"
- I gave the icon a bit more breathing space by increasing the padding

![menu_icon_joyn.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573c1ff4a6fa830e003f5019/125516c66e82c728ace21e0d46e5919436bd8aaa80e78049ab44fed665043761260ea62864c7b96aea1b2d5558584aa4460c0b4cadab892bf4b63e248e5c0fb8c3714d36976345f3e5db55ea43a82a994e8dbcbd8f4ec3eb3922e58a8d4e381e1755.png)

![Screen Shot 2018-04-10 at 09.51.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573c1ff4a6fa830e003f5019/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a378e60c2e50415e4ebe5d4a1f06a3a3dc78e2a436628f550de9d66a5b7cc16945a4e9d01fbf53ba22df4b85b2e99850d2aa6c7bb3d4d216744b470a83ed5f37aa984eca5bf54fe64f57a1113261f43b.png)

**Comment by RubenMattan** [comment]
Updated text and icon. 
I will add a new property for all `LSApplicationQueriesSchemes ` in build.yaml

**Comment by RubenMattan** [comment]
Created an issue for newly created apps https://github.com/rogerthat-platform/plugin-rogerthat-control-center/issues/268
