### ISSUE TITLE
Product list when payment is enabled

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#826]
- [x] When enabling mobile payments and there are items with `visible_with_pay==False`, then show a warning text because these products will not be shown in the e-shop anymore.
  - `visible_with_pay` is False when there is no price, or the step unit is totally different from unit (eg. price per kg, and step_unit == 'piece')

- [x] Right now, I think when price is set per "kg" and the step unit is "g", then these products are skipped too. Double-check if this is the case. 
  - If this is the case, then I want to change that. We could use `step_unit_conversion` to calculate the price.

**Comment by bart-at-mobicage** [comment]
@RubenMattan, can you review the second bullet of the ticket.

**Comment by RubenMattan** [comment]
Right now every item with a step unit is skipped.

**Comment by abom** [comment]
Related to https://github.com/our-city-app/oca-backend/issues/757, there will be two units, one for pricing and another one for ordering, they can be the same, but products with a price unit that's different from ordering unit [will be skipped too](https://github.com/our-city-app/oca-backend/issues/757#issuecomment-379237634) when payment is required.
