### ISSUE TITLE
Strange behaviour with confirmation step in e-shop flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#828]
The confirmation step has waitForFollowUp==True, but I think it shouldn't be waiting for an incoming reply. Because it's possible that the reply arrives while the message is open.

**Comment by bart-at-mobicage** [comment]
![img_5216](https://user-images.githubusercontent.com/17762105/40660274-c92aec36-6350-11e8-98c5-60162edb6495.jpg)

![img_5215](https://user-images.githubusercontent.com/17762105/40660269-c6d464e4-6350-11e8-94b1-2cf4404df55b.jpg)

These are the 2 confirmation messages that are shown. I think we can keep the first one and get rid of the 2nd one.

**Comment by abom** [comment]
The message depends on the confirmation type, so in case of automatic conformation, we should get rid of the second message?
