### ISSUE TITLE
Agenda branding: multi-date event with different hours not shown well

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#83]
Eg. event "Kerstavond" in Gemeente Laarne.
* has 2 different dates
* has 2 different start and end times

In the event list, only the first date is shown
In the detail view, only the start hours are shown

**Comment by siddiquagig** [comment]
Hi,

Can we have a ETC of this issue so we can update.

Else If the issue is resolved please put the state_resolved label and close the issue.

Thanks!
