### ISSUE TITLE
Paying for new budget 

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#832]
> €50.00 (VAT excl) for 10000 views. The amount of views is determined 2 weeks after publishing a news item and is decreased from the available budget. If the amount of views is exceeded, then this merchant will have a negative balance, which will be decreased from the next €50.00 that he pays.

- [x] So, the merchant needs to pay upfront with his creditcard if he has <= 0 views left on his budget. The price is €50.00 (VAT excl) for 10000 views.
  - There should be a `Product` model for this. See `add_all_products`.
  - Create an order and an invoice. Execute the invoice automatically.
- [x] Add a page in the dashboard shop where people can top up their budget.
  - [x] Also show the progress of the budget on this page

**Comment by lucasvanhalst** [comment]
Where should the current budget be shown? I don't think putting it under 'shop' makes a lot of sense, that's not where I would search for such a thing.

**Comment by lucasvanhalst** [comment]
>  Also show the progress of the budget on this page

Is this stored on the Budget model as well?

**Comment by bart-at-mobicage** [comment]
> Where should the current budget be shown? I don't think putting it under 'shop' makes a lot of sense, that's not where I would search for such a thing.

Maybe in the News history then

>> Also show the progress of the budget on this page

> Is this stored on the `Budget` model as well?

ok. `Budget.total`?

**Comment by lucasvanhalst** [comment]
See #839 but not sure if it's enough. Currently only the current budget is shown on the shop page of the budget product. I think it would make more sense if show this under 'billing', along with a list of all `BudgetTransaction`'s

**Comment by lucasvanhalst** [comment]
part of #748
