### ISSUE TITLE
Budget modeling

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#833]
- [x] add a `Budget` model, which has a `balance` property
- [x] add a `BudgetTransaction` model
  - each time the budget cron runs or each time new budget is bought, a `BudgetTransaction` instance should be created. update the `Budget` model as well.
    - `BudgetTransaction` should have `time` (datetime), `amount`(int), `context_type`(str with predefined type), `context_key` (ndb.key) properties

**Comment by abom** [comment]
https://github.com/our-city-app/oca-backend/pull/748/commits/24e5a20dfa80dacdb04a1df4933f94c2fbdd5344

Till now, don't know for sure when a new budget is bought to create the first transaction. Also, i think i shouldn't update the balance of Budget, the balance should be the sum of all transactions?
So, we should have something like initial_balance and/or current_balance, or even remove that Budget model at all.

**Comment by bart-at-mobicage** [comment]
> Till now, don't know for sure when a new budget is bought to create the first transaction.

This will be the user that buys 10k views in the shop.

> Also, i think i shouldn't update the balance of Budget, the balance should be the sum of all transactions?

I'd create 1 bizz method, which should be used by the dashboard shop and the cron: `def update_budget(service_user, amount)`. Which will transactionally create the BudgetTransaction, and update the budget (`balance = sum((t.amount for t in BudgetTransaction.all().ancestor(service_user))) + amount`).

The budget will act like a cache for the total, might probably get more properties in the future.

Btw, amount will be in cents. So 50 EUR ==> `budget.amount = 5000`.

**Comment by abom** [comment]
#748.
