### ISSUE TITLE
Check budget in news wizard

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#836]
- In the city-select step, show a warning if the user wants to select a city while his balance is negative
- show a warning and a button which goes to the shop

**Comment by lucasvanhalst** [comment]
You can check broadcastSettings.news_settings.tags,  if it includes 'free_regional_news' they can always send regional news regardless of budget. Otherwise, the current budget will have to be fetched

**Comment by abom** [comment]
#748.
