### ISSUE TITLE
This customer has no default calendar!

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#840]
Customer with service email `service-9db2581d-0512-4f87-a192-b6ba673e2ec0@rogerth.at` has no default calendar. They have 2 "normal" calendars with name 'default' though.
The customer was created at Wed Mar 21.

Other ones: 
- `service-c0f8fd5d-d2bb-4d7c-aef3-d92c5a3e7cbd@rogerth.at` (created @ Tue Mar 20)
  - Has 1 "normal" calendar with name 'default'
- `service-087843a5-182c-4c5e-a904-182d50662c8b@rogerth.at` (created @ Wed Mar 21)
  - Has 5 "normal" calendars with name 'default'

**Comment by bart-at-mobicage** [comment]
`service-f9b1398a-d116-418f-aafb-68b224447f17@rogerth.at` has no default calendar as well. The result is that the events aren't visible by default in the app, because only the default calendar is shown by default. The other calendars are opt-in.

**Comment by bart-at-mobicage** [comment]
I ran the `create_default_solution_calendars` migration, the following services were modified:
```
service-c0f8fd5d-d2bb-4d7c-aef3-d92c5a3e7cbd@rogerth.at
service-9b67efc9-6d62-4560-b201-f19879c5a479@rogerth.at
service-9db2581d-0512-4f87-a192-b6ba673e2ec0@rogerth.at
service-886995f9-0173-4ed5-b78f-79ecf9ae50f5@rogerth.at
service-8fb0af35-810a-4ab8-8911-70e0aeed070c@rogerth.at
service-087843a5-182c-4c5e-a904-182d50662c8b@rogerth.at
service-113f2164-e94a-42da-bc5d-ee59189d74cc@rogerth.at
service-0445d20c-d985-4e3d-b4f9-8c34562dd319@rogerth.at
```

`service-f9b1398a-d116-418f-aafb-68b224447f17@rogerth.at` wasn't migrated o.O

**Comment by abom** [comment]
I think this problem is probably related to the old transactions/provisioning problem, because _sln_settings.provisioned_modules_ is not set too, which means **provisioning.provision_all_modules()** has failed.

![screenshot from 2018-05-23 12-32-17](https://user-images.githubusercontent.com/511438/40419348-5de96c7e-5e85-11e8-9f1d-990673ce1301.png)

So, the modules are there but need to be published again (found some test services locally with the same issue, and they were created while testing the transactions/provisioning problem).

**Comment by abom** [comment]
Also the creation date of these services are nearly the same time of that problem.

> service-c0f8fd5d-d2bb-4d7c-aef3-d92c5a3e7cbd@rogerth.at
> service-9b67efc9-6d62-4560-b201-f19879c5a479@rogerth.at
> service-9db2581d-0512-4f87-a192-b6ba673e2ec0@rogerth.at
> service-886995f9-0173-4ed5-b78f-79ecf9ae50f5@rogerth.at
> service-8fb0af35-810a-4ab8-8911-70e0aeed070c@rogerth.at
> service-087843a5-182c-4c5e-a904-182d50662c8b@rogerth.at
> service-113f2164-e94a-42da-bc5d-ee59189d74cc@rogerth.at
> service-0445d20c-d985-4e3d-b4f9-8c34562dd319@rogerth.at

**Comment by bart-at-mobicage** [comment]
Ok, good to hear it's already fixed. I'd provision these services and then this issue is resolved, I guess?

**Comment by abom** [comment]
@bart-at-mobicage yes, it should be resolved after provisioning.
