### ISSUE TITLE
City select widget improvements

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#844]
- [x] Is it possible to change some colors?
  - `#FFFFFF`: Unsupported app, can not be selected
  - `#F4F4E9`: Supported app, can be selected (not changed, this is the default color in Mapael, I guess)
  - `#5BC4BF`: App that is selected
  - `#A3E135`: When hovering (not changed)
- [x] Add a legend that explains these color codes
  - `#5BC4BF`: 
    - EN: You have selected this city app
    - NL: Je hebt deze stad app geselecteerd
  - `#F4F4E9`: 
    - EN: They own our city app
    - NL: Zij hebben onze stad app
  - `#FFFFFF`: 
    - EN: Will they be next to own our city app?
    - NL: Zijn zij de volgende met onze stad app?
- [x] I changed the modal size to fit the entire screen. But when zooming the map, the full potential height isn't used yet. I think you can achieve this by changing the height of `#map_container .map svg` to 100%

**Comment by abom** [comment]
For this one

> I changed the modal size to fit the entire screen. But when zooming the map, the full potential height isn't used yet. I think you can achieve this by changing the height of #map_container .map svg to 100%

Did you mean the full potential height of the modal or the map? i only extended the modal body so that the footer should be always at the bottom.
The data of the map itself define a fixed width and height.
