### ISSUE TITLE
Wrong deadline in sandwich flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#845]
Dashboard says you can order until 11AM.

![img_5174](https://user-images.githubusercontent.com/17762105/38779531-02ac822a-40ca-11e8-848b-115f301131a0.PNG)

**Comment by abom** [comment]
Leap time is enabled with **20 minutes**.

**Comment by abom** [comment]
Another thing, whether it's enabled or not, it's added/subtracted from the ordering times.
Is that intended?

**Comment by bart-at-mobicage** [comment]
You are right. I was confused because we were able to order until 11:00 in the past. Probably they enabled leap time. I think the leap time setting only makes sense in case a takeaway timestamp is asked. But that's not an issue that needs to be tackled right now.

I think for now we can just go to the `message_cannot_order_now` step in the beginning of the flow if the user orders after 10:40 (`sandwichSettings.time_until - sandwichSettings.leap_time`)
