### ISSUE TITLE
Regional news reach

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#846]
- [x] ~News sent to your main city-app should be for free.~
- [x] Show the regional reach in the news history, when you press "Reach" (this is the reach in apps != main app)
- [x] Create an inbox message when subtracting news reach from the budget
- [x] When showing the balance of the budget, show views instead of euros. Same for transactions.

**Comment by abom** [comment]
The reach of the news sent to main city-app is not considered? what is the problem with it exactly?

**Comment by bart-at-mobicage** [comment]
Ok, you can ignore that part. I didn't know that solutionNewsItem.app_ids didn't include the main app.
