### ISSUE TITLE
Recurrent paid feature for RSS

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#848]
The RSS feature should only be visible for community services if they pay 120 EUR/year.
- [ ] Create a product that will be billed once a year and costs 120 EUR. See `APPL` product for an example.
- [ ] The RSS-related fields should only be rendered in the dashboard if the community service has paid for this product.
  - I was thinking about creating an Enum "`PaidFeatures`". When and order is created, and the order has the RSS product, then add `PaidFeatures.RSS_SYNC` to `SolutionSettings.paid_features`.

**Comment by RubenMattan** [comment]
I would not limit this feature to community services only.

Note: the moment this feature is disabled we should put dry_runned to False

**Comment by RubenMattan** [comment]
I just had a look on how recurrent billing is done right now, Apparently this only works for subscription orders. So refactoring this will best be done by someone who knows that code.

In my opinion charges should be grouped (at least per day), so that a user is not busy paying all those expenses.
