### ISSUE TITLE
Optimisation of 3P integration

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#856]
- [x] Create a windows batch script that does the following:
  - touch gs://bucket/reports/__syncing when starting to sync
    - [x] don't create new incident files when this file is there. maybe by throwing an exception such that the defer retries automatically with a backoff (but don't log the exception as an error).
  - sync gs://bucket/reports
  - delete gs://bucket/reports/*

This should work on unix:
```bash
LOCAL_PATH=/path/to/3p/dir

echo "" | gsutil cp - gs://rogerthat-3p-testing/reports/__syncing
gsutil rsync -r gs://rogerthat-3p-testing/reports $LOCAL_PATH
rm $LOCAL_PATH/__syncing
gsutil -m rm gs://rogerthat-3p-testing/reports/*
```

**Comment by bart-at-mobicage** [comment]
```bat
SET LOCAL_PATH="/path/to/3p/dir"

echo "" | gsutil cp - gs://rogerthat-3p-testing/reports/__syncing
gsutil rsync -r gs://rogerthat-3p-testing/reports $LOCAL_PATH
del %LOCAL_PATH%/__syncing
gsutil rm gs://rogerthat-3p-testing/reports/*
```

**Comment by bart-at-mobicage** [comment]
> Als ik het script uitvoer lukt dit, maar als ik het een tweede keer uitvoer kopieert hij opnieuw de bestanden.
- [ ] Find out what goes wrong. Run our unix script a few times to see how it behaves.

> De code ‘encoding = utf8’ mag niet in de xml staan.
- [ ] Rm `encoding-"utf-8"` from the xml

**Comment by RubenMattan** [comment]
He only had read access. I have added permission to create and delete files now

**Comment by bart-at-mobicage** [comment]
> Om de meldingen juist binnen te krijgen zou er in het veld urgentie altijd  “melding” moeten staan.
> Zo kan dienst communicatie dit in 3P controleren en aan de juiste dienst toewijzen.

**Comment by RubenMattan** [comment]
Above comments are in production now
