### ISSUE TITLE
Payment: Billing the transaction cost of 0.15 EUR if order amount is less than x EUR

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#857]
- [ ] Add a setting to add the transaction cost of 0.15 EUR on top of the order price if the order price is less than x EUR.
- [ ] Show a note in the advanced order step:
  - EN: A transaction cost of 0.15 EURO is charged for payments under %s EUR.
  - NL: Bij betalingen onder de %s EUR wordt een transactiekost van 0,15 EURO aangerekend.

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/863
