### ISSUE TITLE
Regional news in demo apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#864]
Customers with country BE, but with a demo main app
- ... should see the city-select map. They should be able to select extra cities, however, when publishing, the news item should only be published in the default news feed of the demo main app.
- ... should also need to buy budget. However (just like any other signed orders of demo apps) no invoice should be created. No need to couple a creditcard either.

Priority critical because they want to create a tutorial video and also show this functionality in the future with the OSA bakker demo customer.

**Comment by abom** [comment]
https://github.com/rogerthat-platform/rogerthat-backend/pull/465 and https://github.com/our-city-app/oca-backend/pull/748/commits/ce652a754cd11056e4fdb1897502630a1fbcb4a1
