### ISSUE TITLE
Order multiple sandwiches in 1 flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#866]
Since we have a possible transaction fee which is billed to the enduser, we should make it possible to order multiple sandwiches before entering the pay step.

- [ ] Add "Do you want to order another sandwich" --> Yes/No
- [ ] Don't know if this is already the case, but make sure the transaction fee setting is respected in the sandwich flow as well

**Comment by RubenMattan** [comment]
This flow to order a sandwich is okay if you only order 1 or 2 sandwiches, but if you want to order more this is not really easy to use...

**Comment by RubenMattan** [comment]
Well just implement it like this for now
