### ISSUE TITLE
Problems with our loyalty card system

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#867]
ik denk dat er een probleem is met ons klantenkaartsysteem
k heb de terminal gedownload op de tablet, de QR code kunnen scannen en dan is het zwart.
Ik krijg ook geen kader om te scannen.

I think there is a problem with our loyalty card system
k have downloaded the terminal on the tablet, can scan the QR code and then it is black.
I also get no frame to scan.

**Comment by Sylviecraeye** [comment]
Ook op mijn tablet Demo OSA Bakker is het oog om te scannen weg. Dus kan ik ook daar niet meer scannen.

Also on my tablet Demo OSA Bakker is the eye to scan gone. So I can't scan anymore.

**Comment by RubenMattan** [comment]
duplicate of https://github.com/our-city-app/oca-backend/issues/716
