### ISSUE TITLE
Joyn Coupon remarks

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#869]
During the BAM there were some questions/remarks
- Add a help text to the coupon URL text input field
  - NL: Copy/paste hier de URL van uw coupon die u aangemaakt hebt in uw Joyn portaal.
- Is the "Activate" button backwards compatible?

**Comment by RubenMattan** [comment]
https://github.com/our-city-app/oca-backend/pull/877

Not backwards compatible iirc
