### ISSUE TITLE
Payconiq remark

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#870]
During the BAM there were was a remark:
- Add a help text next to or underneath the transaction fee input field
  - NL: Indien dit op 0 staat, wordt er geen transactiekost aangerekend.
  - EN: If this is 0, no transaction cost will be charged.

See PR #863

**Comment by abom** [comment]
https://github.com/our-city-app/oca-backend/pull/863/commits/44eb6e60d13730bdb7f28490681715562a0fdb68
