### ISSUE TITLE
Signing up a trial service doesn't work

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#88]
Method "service.trial_signup" does not exist

![screen shot 2016-11-21 at 11 13 40](https://cloud.githubusercontent.com/assets/17762105/20478731/a02fe2ca-afdb-11e6-8a43-2be42e7ab4e6.png)

**Comment by RubenMattan** [comment]
rogerthat-platform/rogerthat-backend/#45
