### ISSUE TITLE
Apply trash calendar change to all city services

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#881]
Apply https://github.com/our-city-app/plugin-limburgnet-trash/commit/bd84ff3614a56cd6637494ae42818afc4909c56b to all existing trash calendars
- [x] be-alken
- [x] be-bocholt2
- [x] be-borgloon
- [x] be-bree
- [x] be-diepenbeek
- [x] be-diksmuide
- [x] be-halen
- [x] be-heers
- [x] be-herk-de-stad
- [x] be-lanaken
- [x] be-lo-reninge
- [x] be-neerpelt
- [x] be-sint-truiden
- [x] be-veurne
- [ ] be-vleteren

**Comment by RubenMattan** [comment]
be-vleteren is not ready yet
