### ISSUE TITLE
Missing translation in customer signup

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#902]
![screen shot 2018-05-25 at 10 52 57](https://user-images.githubusercontent.com/17762105/40535494-964756d2-6009-11e8-9fe2-1d14c49afa02.png)

**Comment by lucasvanhalst** [comment]
That's actually not a translation from us, it's from https://chromium.googlesource.com/chromium/src.git/+/62.0.3178.1/content/app/strings/translations/content_strings_en-GB.xtb#50 and uses the browser language

Works the same way as customer signup, does it need to be changed?
