### ISSUE TITLE
Our app is stuck when Payconiq makes the user re-login  

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#912]
The wallet keeps spinning until the server sends a confirmation that the transactions is completed or canceled.

If the Payconiq app isn't used for a while, then Payconiq makes the user login again, but then the transaction isn't shown in Payconiq. When going back to our app, the user sees a never ending spinner and can't do anything but killing the app.

**Comment by lucasvanhalst** [comment]
FIY fixing this will require every app to be rebuild

**Comment by lucasvanhalst** [comment]
You should now be able to dismiss the loading spinner
