### ISSUE TITLE
Error happened when publishing news via message flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#921]
Sunday, service-4b2dfeb8-9f6c-44de-a347-b1ac48d2eeed@rogerth.at tried to create a news item via message flow, but an error occurred

**Comment by abom** [comment]
Cannot figure out where is the problem exactly, it's better to have more input.

**Comment by lucasvanhalst** [comment]
can't find any logs @bart-at-mobicage they're probably gone already

**Comment by bart-at-mobicage** [comment]
Apparently the photo step keeps spinning forever. This was fixed already, but the app needs to be updated. It has build problems though, so need to investigate further :\
