### ISSUE TITLE
Weblink doesn't update for Android user

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#925]
Service `service-cee7f49b-f2c2-416a-bf0f-ff0aa769ab02@rogerth.at` has a static content with a web link: Nieuw (EN: New). The link points to a google slide show. Every Monday, they update this link. One of the Android users doesn't receive this update. When he presses the icon in the app, he still sees the old link. Even after 3 days. Another user (iOS) does receive the updated link.

The user is `f68df3fdbe72b5386822ff15986fdd2b:be-halle`.

Can you investigate if this user receives the new URL in an updateFriend request?

**Comment by RubenMattan** [comment]
Its broken because of https://github.com/rogerthat-platform/rogerthat-backend/commit/a8dfddb8f5988f3491c54d7fa93105262a6801b0 the updates where to close to each other. So the phone skipped the seconds update because the version was the same.

**Comment by RubenMattan** [comment]
Deploying master & publishing again should fix the issue
