### ISSUE TITLE
Missing translation in sidebar?

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#926]
The configuration looks the same as Lochristi, but in Niel it's called "Regional/Local News" instead of "Regionaal/Lokaal Nieuws".

Are there other apps which have the same problem?

![image-1](https://user-images.githubusercontent.com/17762105/40789807-99d5224a-64f3-11e8-874a-467e7a62de88.jpg)

![image-1](https://user-images.githubusercontent.com/17762105/40789888-d241a6ee-64f3-11e8-9297-60f1dd6d0a04.jpg)

**Comment by RubenMattan** [comment]
be-niel is the only one, the translations where not added to the build.yaml and android crashed on it but ios didn't apperently.

I already fixed this 7 days ago, so just rebuild and everything will be ok
