### ISSUE TITLE
privacy voorwaarden” en “algemene voorwaarden” first in English

### ISSUE THREAD

**Issue by Sylviecraeye** [our-city-app/oca-backend#928]
We ontvangen klachten dat de “privacy voorwaarden” en “algemene voorwaarden” eerst in het Engels getoond worden, en dan pas - via een klik op de pijl - in het Nederlands.
Kan dit gewijzigd worden: dus Nederlands (en dan Engels)?

We receive complaints that the "privacy conditions" and "general conditions" are first shown in English, and only then - via a click on the arrow - in Dutch.
Can this be changed: ie Dutch (and then English)?

**Comment by bart-at-mobicage** [comment]
I suggest to use the browser language if the `l` query param is missing in `https://rogerth.at/legal?doc=privacy-policy`, with a fallback to EN if we cannot define the browser language.

**Comment by bart-at-mobicage** [comment]
Apparently it's still always in English
