### ISSUE TITLE
Refactoring trash calendar projects into 1 project with plugins per backend

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#937]
_Edit: suggestion not to use a plugin per backend to reduce overhead, but to have a module per backend (just like we had a module per payment provider in rogerthat-backend)_

In several cities we have a trash calendar integration. The day before a citizen needs to put his trash on the street for collection, he receives a message in the city app. When the citizen first opens the trash calendar html5 app, he is asked for his street. This is sent via system.api_call to the trash plugin. Then based on the street he needs to select his house number. Then the trash plugin knows enough to build the citizen's trash collection calendar. The citizen also needs to select for which types a trash he wants to receive a notification.

Right now we have different GAE projects for the trash calendars. The business code and models are the same. The difference is the communication with a separate backend to get trash collection moments. We want to have 1 project, and every backend (IVVO, Limburg.net, and in the future IVAREM, Mirom, ...) should have his own _module_ (~plugin~), implementing some interface methods to list streets, house numbers (optionally, because not every backend needs this) and collections moments of the trash. 

There also should be an admin page where new cities can be added. First you select the _module_ (~plugin~), then you need to enter the API and SIK keys and some info required by the _module_ (~plugin~) (Eg. limburg.net requires a [NIS code](https://www.socialsecurity.be/portail/glossaires/dmfa.nsf/c866fca44ad35ce0c12568640030dbe2/929dd92c89b39474c125808100310754/$FILE/AN2001-3-1Nl1.pdf) per city).

These project we have now (I'll grant you access)
- rogerthat-be-neerpelt-trash
  - Our first trash calender project. Under the hood it uses the same backend as rt-limburg-net-trash (Limburg.net)
  - Cities:
    - Neerpelt
- rt-limburg-net-trash
  - Generic version of rogerthat-be-neerpelt-trash: https://github.com/our-city-app/plugin-limburgnet-trash
  - Cities:
    - Alken
    - Bocholt
    - Borgloon
    - Bree
    - Diepenbeek
    - Halen
    - Heers
    - Herk-de-Stad
    - Sint-Truiden
    - Beringen
  - To be added:
    - Geetbets
    - Lanaken
- ivvo-afval-kalender, ivvo-afval-kalender-diksmuide, ivvo-afval-kalender-lo-reninge
  - Created by a 3rd party developer: https://github.com/combusbvba
  - Copied from rt-limburg-net-trash and modified to support IVVO
  - Should have made it generic to support multiple services in 1 GAE project, but failed to do so
  - Cities:
    - Veurne
    - Diskmuide
    - Lo-Reninge
  - To be added:
    - Vleteren

Vleteren should be integrated with IVVO too, but we dont want to ask the 3rd party developer anymore. 

Let's do this cleanup first. Once ready, we'll have to check how we migrated the models from the existing GAE projects to the new one.

Later, adding different backends like #850 (IVAREM) and #731 (MIROM) should be easy.

**Comment by RubenMattan** [comment]
So i guess setup needs to be like this:
- 1 rogerthat_api plugin
- 1 interactive explorer plugin
- 1 trash calendar plugin that receives callbacks from rogerthat_api and delivers them to the correct plugin. So this plugin just forwards based on plugin name
- x number of plugins for every type of calendar

**Comment by bart-at-mobicage** [comment]
Repo created: https://github.com/our-city-app/plugin-trash-calendar
