### ISSUE TITLE
Payconiq transaction visible in Payconiq portal, not in OCA dashboard

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#948]
Search Mobicage google drive for "Logs - Payconiq missing orders for payments".

Looks like both iPhones didn't receive the kick to update the payment step. I suggest to do a `getTransaction` call or so. 5 seconds after the app returns to the foreground and no `updateTransaction` is received.

**Comment by lucasvanhalst** [comment]
all apps need to be updated for the workaround to take effect
