### ISSUE TITLE
How to avoid javascript errors when new version is deployed

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#969]
Maybe we can show a banner showing that the user needs to reload the page.

This is to prevent errors like #968.

**Comment by lucasvanhalst** [comment]
reloading won't do much as long as the cache isn't busted. files are cached for 10 minutes by default so as long as they have an old version this will keep happening

**Comment by bart-at-mobicage** [comment]
#968 was a real error, unrelated to files being updated while user was in browser
