### ISSUE TITLE
The Joyn tab should not be visible for services outside BE

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/oca-backend#973]
There are a few merchants of CDR that were 'interested' in joyn.

**Comment by lucasvanhalst** [comment]
It looks like that service has the 'joyn' module, which is why it shows up. Did we accidentally add that to all services?

**Comment by lucasvanhalst** [comment]
can this be closed?

**Comment by bart-at-mobicage** [comment]
Probably manually added by sam
